<?php
// Generated by Cursor prompt — module: Finans (ExpenseCategory) — date: 2026-03-15

namespace App\Modules\Finans\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ExpenseCategory extends Model
{
    protected $table = 'expense_categories';

    protected $fillable = [
        'company_id', 'name', 'limit_per_item', 'requires_receipt', 'is_active',
    ];

    protected $casts = [
        'limit_per_item'  => 'decimal:2',
        'requires_receipt'=> 'boolean',
        'is_active'       => 'boolean',
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(\App\Modules\Sirket\Models\Company::class);
    }

    public function expenses(): HasMany
    {
        return $this->hasMany(ExpenseRequest::class, 'category_id');
    }

    public function scopeForCompany($query, int $companyId)
    {
        return $query->where('company_id', $companyId);
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}
