<?php
// Generated by Cursor prompt — module: Companies — date: 2026-03-15

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CompaniesSeeder extends Seeder
{
    public function run(): void
    {
        $companies = [
            [
                'name'       => 'Miysoft Teknoloji A.Ş.',
                'domain'     => 'miysoft.com.tr',
                'tax_number' => '1234567890',
                'tax_office' => 'Ataşehir',
                'phone'      => '+90 216 000 0001',
                'email'      => 'info@miysoft.com.tr',
                'address'    => 'Ataşehir Bulvarı No:1',
                'city'       => 'İstanbul',
                'country'    => 'TR',
                'timezone'   => 'Europe/Istanbul',
                'locale'     => 'tr',
                'status'     => 'active',
                'settings'   => json_encode(['working_days' => [1,2,3,4,5], 'work_start' => '09:00', 'work_end' => '18:00']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Demo KOBİ Ltd. Şti.',
                'domain'     => 'demokobic.com',
                'tax_number' => '9876543210',
                'tax_office' => 'Kadıköy',
                'phone'      => '+90 216 000 0002',
                'email'      => 'info@demokobic.com',
                'address'    => 'Kadıköy Merkez No:5',
                'city'       => 'İstanbul',
                'country'    => 'TR',
                'timezone'   => 'Europe/Istanbul',
                'locale'     => 'tr',
                'status'     => 'trial',
                'settings'   => json_encode(['working_days' => [1,2,3,4,5], 'work_start' => '08:30', 'work_end' => '17:30']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Örnek Holding A.Ş.',
                'domain'     => 'ornekholding.com.tr',
                'tax_number' => '1122334455',
                'tax_office' => 'Şişli',
                'phone'      => '+90 212 000 0003',
                'email'      => 'iletisim@ornekholding.com.tr',
                'address'    => 'Şişli Merkez Cad. No:10',
                'city'       => 'İstanbul',
                'country'    => 'TR',
                'timezone'   => 'Europe/Istanbul',
                'locale'     => 'tr',
                'status'     => 'active',
                'settings'   => json_encode(['working_days' => [1,2,3,4,5,6], 'work_start' => '09:00', 'work_end' => '19:00']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Anadolu Üretim San. A.Ş.',
                'domain'     => 'anadoluuretim.com',
                'tax_number' => '5566778899',
                'tax_office' => 'Çerkezköy',
                'phone'      => '+90 282 000 0004',
                'email'      => 'bilgi@anadoluuretim.com',
                'address'    => 'OSB Mah. Fabrika Cd. No:20',
                'city'       => 'Tekirdağ',
                'country'    => 'TR',
                'timezone'   => 'Europe/Istanbul',
                'locale'     => 'tr',
                'status'     => 'active',
                'settings'   => json_encode(['working_days' => [1,2,3,4,5], 'work_start' => '07:00', 'work_end' => '16:00']),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name'       => 'Test Şirketi B.V.',
                'domain'     => 'testsirketi.io',
                'tax_number' => '0011223344',
                'tax_office' => 'Ankara',
                'phone'      => '+90 312 000 0005',
                'email'      => 'test@testsirketi.io',
                'address'    => 'Çankaya Cd. No:99',
                'city'       => 'Ankara',
                'country'    => 'TR',
                'timezone'   => 'Europe/Istanbul',
                'locale'     => 'tr',
                'status'     => 'inactive',
                'settings'   => json_encode(['working_days' => [1,2,3,4,5]]),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($companies as $company) {
            DB::table('companies')->updateOrInsert(['domain' => $company['domain']], $company);
        }

        // Her şirkete departman ve pozisyon ekle
        $companyIds = DB::table('companies')->pluck('id');

        foreach ($companyIds as $companyId) {
            // Departmanlar
            $departments = ['İnsan Kaynakları', 'Muhasebe', 'Bilgi Teknolojileri', 'Satış', 'Üretim', 'Lojistik'];
            foreach ($departments as $dept) {
                DB::table('departments')->updateOrInsert(
                    ['company_id' => $companyId, 'name' => $dept],
                    ['is_active' => true, 'created_at' => now(), 'updated_at' => now()]
                );
            }

            // Pozisyonlar
            $positions = ['Genel Müdür', 'Müdür', 'Uzman', 'Asistan', 'İşçi', 'Stajyer'];
            foreach ($positions as $pos) {
                DB::table('positions')->updateOrInsert(
                    ['company_id' => $companyId, 'title' => $pos],
                    ['is_active' => true, 'created_at' => now(), 'updated_at' => now()]
                );
            }
        }

        $this->command->info('Şirketler, departmanlar ve pozisyonlar oluşturuldu.');
    }
}
