<?php
// Generated by Cursor prompt — MİYSOFT PTS — date: 2026-03-15

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        $this->call([
            RolesPermissionsSeeder::class,
            CompaniesSeeder::class,
            PersonelsSeeder::class,
        ]);
    }
}
