<?php
// Generated by Cursor prompt — module: Personel — date: 2026-03-15

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Crypt;

class PersonelsSeeder extends Seeder
{
    public function run(): void
    {
        $faker = \Faker\Factory::create('tr_TR');

        $companies = DB::table('companies')->pluck('id');
        $genders   = ['M', 'F'];
        $statuses  = ['active', 'active', 'active', 'active', 'on_leave', 'terminated'];

        foreach ($companies as $companyId) {
            $departments = DB::table('departments')->where('company_id', $companyId)->pluck('id');
            $positions   = DB::table('positions')->where('company_id', $companyId)->pluck('id');

            // Her şirkete 10 personel (toplamda 50 personel)
            for ($i = 0; $i < 10; $i++) {
                $firstName = $faker->firstName();
                $lastName  = $faker->lastName();
                $gender    = $genders[array_rand($genders)];
                $nationalId = (string) $faker->randomNumber(8) . str_pad((string)$faker->randomNumber(3), 3, '0');

                DB::table('personels')->insert([
                    'company_id'        => $companyId,
                    'first_name'        => $firstName,
                    'last_name'         => $lastName,
                    'email'             => strtolower(Str::ascii($firstName) . '.' . Str::ascii($lastName)) . $faker->randomNumber(3) . '@' . $faker->domainName(),
                    'phone'             => $faker->phoneNumber(),
                    'national_id_enc'   => Crypt::encryptString($nationalId),
                    'national_id_hash'  => hash('sha256', $nationalId),
                    'birth_date'        => $faker->dateTimeBetween('-55 years', '-22 years')->format('Y-m-d'),
                    'gender'            => $gender,
                    'department_id'     => $departments->random(),
                    'position_id'       => $positions->random(),
                    'salary'            => $faker->randomFloat(2, 15000, 80000),
                    'currency'          => 'TRY',
                    'hire_date'         => $faker->dateTimeBetween('-10 years', '-3 months')->format('Y-m-d'),
                    'status'            => $statuses[array_rand($statuses)],
                    'is_active'         => true,
                    'attributes'        => null,
                    'created_at'        => now(),
                    'updated_at'        => now(),
                ]);
            }
        }

        $this->command->info('50 personel başarıyla oluşturuldu.');
    }
}
