{{-- Generated by Cursor prompt — Personel Evrak Yükleme/Görüntüleme UI — date: 2026-03-15 --}}
<div class="space-y-4">

    {{-- Yükleme Alanı --}}
    <div class="border-2 border-dashed border-gray-200 rounded-xl p-5 hover:border-[#02E0FB] hover:bg-[#02E0FB]/5 transition-all cursor-pointer"
         id="docDropZone"
         onclick="document.getElementById('docFileInput').click()"
         ondragover="event.preventDefault(); this.classList.add('border-[#02E0FB]')"
         ondrop="handleDocDrop(event)">
        <div class="text-center">
            <svg class="w-10 h-10 text-gray-300 mx-auto mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/>
            </svg>
            <p class="text-sm text-gray-500">Belge yüklemek için tıklayın veya sürükleyin</p>
            <p class="text-xs text-gray-400 mt-1">PDF, JPG, PNG, DOCX — Max 10MB</p>
        </div>
    </div>

    {{-- Yükleme Formu --}}
    <form id="docUploadForm" class="hidden space-y-3 bg-gray-50 rounded-xl p-4 border border-gray-200">
        <input type="file" id="docFileInput" name="file" class="hidden" accept=".pdf,.jpg,.jpeg,.png,.docx"
            onchange="previewDocFile(this)">

        <div>
            <p class="text-sm font-medium text-gray-700 mb-1">Seçilen Dosya:</p>
            <div class="flex items-center gap-3 p-3 bg-white rounded-lg border border-gray-200">
                <svg class="w-8 h-8 text-[#02E0FB] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/>
                </svg>
                <div>
                    <p class="text-sm font-medium text-gray-800" id="docFileName">—</p>
                    <p class="text-xs text-gray-400" id="docFileSize">—</p>
                </div>
            </div>
        </div>

        <div class="grid grid-cols-2 gap-3">
            <div>
                <label class="block text-xs font-medium text-gray-600 mb-1">Belge Türü <span class="text-red-500">*</span></label>
                <select name="type" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                    <option value="">— Seçiniz —</option>
                    @foreach(['Kimlik Kartı','Pasaport','İkametgah','Diploma','Sertifika','Sabıka Kaydı','Sağlık Raporu','Sözleşme','SGK Belgesi','Diğer'] as $type)
                    <option value="{{ $type }}">{{ $type }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label class="block text-xs font-medium text-gray-600 mb-1">Son Geçerlilik Tarihi</label>
                <input type="date" name="expiry_at" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
            </div>
        </div>

        <div class="flex gap-2 justify-end">
            <button type="button" onclick="cancelDocUpload()" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button type="button" onclick="uploadDocument({{ $personel->id }})" class="px-4 py-2 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg">Yükle</button>
        </div>
    </form>

    {{-- Mevcut Belgeler Listesi --}}
    <div>
        <h4 class="text-sm font-semibold text-gray-700 mb-3">Yüklü Belgeler</h4>
        <div id="docsList" class="space-y-2">
            @forelse($personel->documents ?? [] as $doc)
            <div class="flex items-center justify-between p-3 bg-white rounded-xl border border-gray-100 hover:shadow-sm transition-shadow group" id="doc-{{ $doc->id }}">
                <div class="flex items-center gap-3">
                    <div class="w-9 h-9 rounded-lg bg-[#02E0FB]/10 flex items-center justify-center shrink-0">
                        @php
                        $ext = pathinfo($doc->file_path, PATHINFO_EXTENSION);
                        $icon = match(strtolower($ext)) {
                            'pdf' => '📄', 'jpg', 'jpeg', 'png' => '🖼️', 'docx', 'doc' => '📝', default => '📎'
                        };
                        @endphp
                        <span class="text-lg">{{ $icon }}</span>
                    </div>
                    <div>
                        <p class="text-sm font-medium text-gray-800">{{ $doc->type }}</p>
                        <p class="text-xs text-gray-400">
                            {{ $doc->original_name ?? basename($doc->file_path) }}
                            @if($doc->expiry_at)
                            · Son: {{ \Carbon\Carbon::parse($doc->expiry_at)->format('d.m.Y') }}
                            @if(\Carbon\Carbon::parse($doc->expiry_at)->isPast())
                                <span class="text-red-500 font-semibold">⚠ Süresi Dolmuş</span>
                            @elseif(\Carbon\Carbon::parse($doc->expiry_at)->diffInDays(now()) <= 30)
                                <span class="text-yellow-500 font-semibold">⏰ Yakında Bitiyor</span>
                            @endif
                            @endif
                        </p>
                    </div>
                </div>
                <div class="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                    <a href="{{ route('admin.personel.documents.download', $doc->id) }}"
                       class="p-1.5 text-gray-400 hover:text-[#02E0FB] hover:bg-blue-50 rounded-lg transition-colors" title="İndir">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                    </a>
                    <button onclick="deleteDocument({{ $doc->id }})"
                        class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors" title="Sil">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                    </button>
                </div>
            </div>
            @empty
            <div class="text-center py-8 text-gray-400 bg-gray-50 rounded-xl border border-dashed border-gray-200">
                <p class="text-3xl mb-2">📂</p>
                <p class="text-sm">Henüz belge yüklenmemiş</p>
            </div>
            @endforelse
        </div>
    </div>
</div>

<script>
function previewDocFile(input) {
    if (!input.files.length) return;
    const file = input.files[0];
    document.getElementById('docFileName').textContent = file.name;
    document.getElementById('docFileSize').textContent = (file.size / 1024 / 1024).toFixed(2) + ' MB';
    document.getElementById('docDropZone').classList.add('hidden');
    document.getElementById('docUploadForm').classList.remove('hidden');
}

function handleDocDrop(e) {
    e.preventDefault();
    document.getElementById('docFileInput').files = e.dataTransfer.files;
    previewDocFile(document.getElementById('docFileInput'));
}

function cancelDocUpload() {
    document.getElementById('docDropZone').classList.remove('hidden');
    document.getElementById('docUploadForm').classList.add('hidden');
    document.getElementById('docFileInput').value = '';
}

function uploadDocument(personelId) {
    const form = document.getElementById('docUploadForm');
    const type = form.querySelector('[name="type"]').value;
    if (!type) { toast('warning', 'Belge türü seçimi zorunludur.'); return; }

    const formData = new FormData();
    formData.append('file', document.getElementById('docFileInput').files[0]);
    formData.append('type', type);
    const expiry = form.querySelector('[name="expiry_at"]').value;
    if (expiry) formData.append('expiry_at', expiry);

    axios.post(`/admin/personel/${personelId}/documents`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' }
    }).then(res => {
        toast('success', res.data.message);
        cancelDocUpload();
        // Listeyi güncelle
        setTimeout(() => location.reload(), 1000);
    }).catch(err => {
        toast('error', err.response?.data?.message || 'Yükleme başarısız.');
    });
}

function deleteDocument(docId) {
    confirmDelete(`/admin/personel/documents/${docId}`, () => {
        document.getElementById(`doc-${docId}`)?.remove();
    });
}
</script>
