{{-- Generated by Cursor prompt — module: Personel — date: 2026-03-15 --}}
<form id="personelForm" class="space-y-5" novalidate>
    @csrf

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

        {{-- Ad --}}
        <div>
            <label for="first_name" class="block text-sm font-medium text-gray-700 mb-1">Ad <span class="text-red-500">*</span></label>
            <input type="text" id="first_name" name="first_name" value="{{ $personel->first_name ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                required placeholder="Personel adı">
        </div>

        {{-- Soyad --}}
        <div>
            <label for="last_name" class="block text-sm font-medium text-gray-700 mb-1">Soyad <span class="text-red-500">*</span></label>
            <input type="text" id="last_name" name="last_name" value="{{ $personel->last_name ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                required placeholder="Personel soyadı">
        </div>

        {{-- E-posta --}}
        <div>
            <label for="email" class="block text-sm font-medium text-gray-700 mb-1">E-posta</label>
            <input type="email" id="email" name="email" value="{{ $personel->email ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="ornek@sirket.com">
        </div>

        {{-- Telefon --}}
        <div>
            <label for="phone" class="block text-sm font-medium text-gray-700 mb-1">Telefon</label>
            <input type="text" id="phone" name="phone" value="{{ $personel->phone ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="+90 555 000 0000">
        </div>

        {{-- TC Kimlik No --}}
        <div>
            <label for="national_id" class="block text-sm font-medium text-gray-700 mb-1">
                TC Kimlik No
                <span class="text-xs text-gray-400 font-normal">(şifrelenip saklanır)</span>
            </label>
            <input type="text" id="national_id" name="national_id"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="{{ isset($personel) ? $personel->masked_national_id : '00000000000' }}"
                maxlength="11">
        </div>

        {{-- Doğum Tarihi --}}
        <div>
            <label for="birth_date" class="block text-sm font-medium text-gray-700 mb-1">Doğum Tarihi</label>
            <input type="date" id="birth_date" name="birth_date" value="{{ isset($personel) ? $personel->birth_date?->format('Y-m-d') : '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]">
        </div>

        {{-- Cinsiyet --}}
        <div>
            <label for="gender" class="block text-sm font-medium text-gray-700 mb-1">Cinsiyet</label>
            <select id="gender" name="gender" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                <option value="M" {{ isset($personel) && $personel->gender === 'M' ? 'selected' : '' }}>Erkek</option>
                <option value="F" {{ isset($personel) && $personel->gender === 'F' ? 'selected' : '' }}>Kadın</option>
                <option value="other" {{ isset($personel) && $personel->gender === 'other' ? 'selected' : '' }}>Diğer</option>
            </select>
        </div>

        {{-- Kan Grubu --}}
        <div>
            <label for="blood_type" class="block text-sm font-medium text-gray-700 mb-1">Kan Grubu</label>
            <select id="blood_type" name="blood_type" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                @foreach(['A+','A-','B+','B-','AB+','AB-','0+','0-'] as $bg)
                    <option value="{{ $bg }}" {{ isset($personel) && $personel->blood_type === $bg ? 'selected' : '' }}>{{ $bg }}</option>
                @endforeach
            </select>
        </div>

        {{-- Departman --}}
        <div>
            <label for="department_id" class="block text-sm font-medium text-gray-700 mb-1">Departman</label>
            <select id="department_id" name="department_id" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                @foreach($departments ?? [] as $dept)
                    <option value="{{ $dept->id }}" {{ isset($personel) && $personel->department_id == $dept->id ? 'selected' : '' }}>{{ $dept->name }}</option>
                @endforeach
            </select>
        </div>

        {{-- Pozisyon --}}
        <div>
            <label for="position_id" class="block text-sm font-medium text-gray-700 mb-1">Pozisyon</label>
            <select id="position_id" name="position_id" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                @foreach($positions ?? [] as $pos)
                    <option value="{{ $pos->id }}" {{ isset($personel) && $personel->position_id == $pos->id ? 'selected' : '' }}>{{ $pos->title }}</option>
                @endforeach
            </select>
        </div>

        {{-- Maaş --}}
        <div>
            <label for="salary" class="block text-sm font-medium text-gray-700 mb-1">Maaş</label>
            <div class="relative">
                <input type="number" id="salary" name="salary" value="{{ $personel->salary ?? '' }}" step="0.01" min="0"
                    class="w-full pl-3 pr-12 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                    placeholder="15000.00">
                <span class="absolute right-3 top-2.5 text-xs text-gray-400">TRY</span>
            </div>
        </div>

        {{-- İşe Giriş Tarihi --}}
        <div>
            <label for="hire_date" class="block text-sm font-medium text-gray-700 mb-1">İşe Giriş Tarihi</label>
            <input type="date" id="hire_date" name="hire_date" value="{{ isset($personel) ? $personel->hire_date?->format('Y-m-d') : '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]">
        </div>

        {{-- Durum --}}
        <div>
            <label for="status" class="block text-sm font-medium text-gray-700 mb-1">Durum</label>
            <select id="status" name="status" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="active" {{ !isset($personel) || $personel->status === 'active' ? 'selected' : '' }}>Aktif</option>
                <option value="on_leave" {{ isset($personel) && $personel->status === 'on_leave' ? 'selected' : '' }}>İzinde</option>
                <option value="terminated" {{ isset($personel) && $personel->status === 'terminated' ? 'selected' : '' }}>Ayrılmış</option>
                <option value="suspended" {{ isset($personel) && $personel->status === 'suspended' ? 'selected' : '' }}>Askıda</option>
            </select>
        </div>
    </div>

    {{-- Belgeler --}}
    <div class="border-t border-gray-100 pt-4 mt-2">
        <div class="flex items-center justify-between mb-3">
            <h4 class="text-sm font-semibold text-gray-700">Belgeler</h4>
            <button type="button" onclick="addDocumentEntry()"
                class="text-xs font-medium text-[#02E0FB] hover:text-cyan-600 transition-colors flex items-center gap-1">
                <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/>
                </svg>
                Belge Ekle
            </button>
        </div>

        {{-- Mevcut Belgeler --}}
        @if(isset($personel) && $personel->documents && $personel->documents->count() > 0)
        <div class="mb-4">
            <h5 class="text-xs font-medium text-gray-500 uppercase tracking-wider mb-2">Mevcut Belgeler</h5>
            <div class="space-y-2">
                @foreach($personel->documents as $doc)
                <div class="flex items-center justify-between p-3 bg-gray-50 rounded-xl border border-gray-100 group" id="doc-{{ $doc->id }}">
                    <div class="flex items-center gap-3">
                        <div class="w-8 h-8 rounded-lg bg-[#02E0FB]/10 flex items-center justify-center shrink-0">
                            @php
                            $ext = pathinfo($doc->file_path, PATHINFO_EXTENSION);
                            $icon = match(strtolower($ext)) {
                                'pdf' => '📄', 'jpg', 'jpeg', 'png' => '🖼️', 'docx', 'doc' => '📝', 'xlsx', 'xls', 'csv' => '📊', default => '📎'
                            };
                            @endphp
                            <span class="text-base">{{ $icon }}</span>
                        </div>
                        <div>
                            <p class="text-sm font-medium text-gray-800">{{ $doc->type }}</p>
                            <p class="text-xs text-gray-400">{{ $doc->original_name ?? basename($doc->file_path) }}</p>
                        </div>
                    </div>
                    <div class="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                        <a href="{{ route('admin.personel.documents.view', $doc->id) }}"
                           class="p-1.5 text-gray-400 hover:text-[#02E0FB] hover:bg-blue-50 rounded-lg transition-colors" title="Görüntüle" target="_blank">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                        </a>
                        <a href="{{ route('admin.personel.documents.download', $doc->id) }}"
                           class="p-1.5 text-gray-400 hover:text-[#02E0FB] hover:bg-blue-50 rounded-lg transition-colors" title="İndir">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                        </a>
                        <button onclick="deleteDocument({{ $doc->id }})"
                            class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors" title="Sil">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                        </button>
                    </div>
                </div>
                @endforeach
            </div>
        </div>
        @endif

        {{-- Yeni Belge Ekleme Alanı --}}
        <div id="documentEntries" class="space-y-2">
            <p class="text-xs text-gray-400 text-center py-3 bg-gray-50 rounded-lg border border-dashed border-gray-200" id="docEmptyMessage">Henüz belge eklenmedi. "Belge Ekle" butonuna tıklayarak belge yükleyebilirsiniz.</p>
        </div>

        <p class="text-xs text-gray-400 mt-2 flex items-center gap-1">
            <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
            Personel kaydedilirken belgeler otomatik olarak yüklenecektir. PDF, JPG, PNG, DOCX, XLSX — Max 10MB
        </p>
    </div>
</form>
