{{-- Generated by Cursor prompt — module: Personel — date: 2026-03-15 --}}
<form id="personelForm" class="space-y-5" novalidate>
    @csrf

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

        {{-- Ad --}}
        <div>
            <label for="first_name" class="block text-sm font-medium text-gray-700 mb-1">Ad <span class="text-red-500">*</span></label>
            <input type="text" id="first_name" name="first_name" value="{{ $personel->first_name ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                required placeholder="Personel adı">
        </div>

        {{-- Soyad --}}
        <div>
            <label for="last_name" class="block text-sm font-medium text-gray-700 mb-1">Soyad <span class="text-red-500">*</span></label>
            <input type="text" id="last_name" name="last_name" value="{{ $personel->last_name ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                required placeholder="Personel soyadı">
        </div>

        {{-- E-posta --}}
        <div>
            <label for="email" class="block text-sm font-medium text-gray-700 mb-1">E-posta</label>
            <input type="email" id="email" name="email" value="{{ $personel->email ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="ornek@sirket.com">
        </div>

        {{-- Telefon --}}
        <div>
            <label for="phone" class="block text-sm font-medium text-gray-700 mb-1">Telefon</label>
            <input type="text" id="phone" name="phone" value="{{ $personel->phone ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="+90 555 000 0000">
        </div>

        {{-- TC Kimlik No --}}
        <div>
            <label for="national_id" class="block text-sm font-medium text-gray-700 mb-1">
                TC Kimlik No
                <span class="text-xs text-gray-400 font-normal">(şifrelenip saklanır)</span>
            </label>
            <input type="text" id="national_id" name="national_id"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="{{ isset($personel) ? $personel->masked_national_id : '00000000000' }}"
                maxlength="11">
        </div>

        {{-- Doğum Tarihi --}}
        <div>
            <label for="birth_date" class="block text-sm font-medium text-gray-700 mb-1">Doğum Tarihi</label>
            <input type="date" id="birth_date" name="birth_date" value="{{ isset($personel) ? $personel->birth_date?->format('Y-m-d') : '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]">
        </div>

        {{-- Cinsiyet --}}
        <div>
            <label for="gender" class="block text-sm font-medium text-gray-700 mb-1">Cinsiyet</label>
            <select id="gender" name="gender" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                <option value="M" {{ isset($personel) && $personel->gender === 'M' ? 'selected' : '' }}>Erkek</option>
                <option value="F" {{ isset($personel) && $personel->gender === 'F' ? 'selected' : '' }}>Kadın</option>
                <option value="other" {{ isset($personel) && $personel->gender === 'other' ? 'selected' : '' }}>Diğer</option>
            </select>
        </div>

        {{-- Kan Grubu --}}
        <div>
            <label for="blood_type" class="block text-sm font-medium text-gray-700 mb-1">Kan Grubu</label>
            <select id="blood_type" name="blood_type" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                @foreach(['A+','A-','B+','B-','AB+','AB-','0+','0-'] as $bg)
                    <option value="{{ $bg }}" {{ isset($personel) && $personel->blood_type === $bg ? 'selected' : '' }}>{{ $bg }}</option>
                @endforeach
            </select>
        </div>

        {{-- Departman --}}
        <div>
            <label for="department_id" class="block text-sm font-medium text-gray-700 mb-1">Departman</label>
            <select id="department_id" name="department_id" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                @foreach($departments ?? [] as $dept)
                    <option value="{{ $dept->id }}" {{ isset($personel) && $personel->department_id == $dept->id ? 'selected' : '' }}>{{ $dept->name }}</option>
                @endforeach
            </select>
        </div>

        {{-- Pozisyon --}}
        <div>
            <label for="position_id" class="block text-sm font-medium text-gray-700 mb-1">Pozisyon</label>
            <select id="position_id" name="position_id" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">Seçiniz</option>
                @foreach($positions ?? [] as $pos)
                    <option value="{{ $pos->id }}" {{ isset($personel) && $personel->position_id == $pos->id ? 'selected' : '' }}>{{ $pos->title }}</option>
                @endforeach
            </select>
        </div>

        {{-- Maaş --}}
        <div>
            <label for="salary" class="block text-sm font-medium text-gray-700 mb-1">Maaş</label>
            <div class="relative">
                <input type="number" id="salary" name="salary" value="{{ $personel->salary ?? '' }}" step="0.01" min="0"
                    class="w-full pl-3 pr-12 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                    placeholder="15000.00">
                <span class="absolute right-3 top-2.5 text-xs text-gray-400">TRY</span>
            </div>
        </div>

        {{-- İşe Giriş Tarihi --}}
        <div>
            <label for="hire_date" class="block text-sm font-medium text-gray-700 mb-1">İşe Giriş Tarihi</label>
            <input type="date" id="hire_date" name="hire_date" value="{{ isset($personel) ? $personel->hire_date?->format('Y-m-d') : '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]">
        </div>

        {{-- Durum --}}
        <div>
            <label for="status" class="block text-sm font-medium text-gray-700 mb-1">Durum</label>
            <select id="status" name="status" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="active" {{ !isset($personel) || $personel->status === 'active' ? 'selected' : '' }}>Aktif</option>
                <option value="on_leave" {{ isset($personel) && $personel->status === 'on_leave' ? 'selected' : '' }}>İzinde</option>
                <option value="terminated" {{ isset($personel) && $personel->status === 'terminated' ? 'selected' : '' }}>Ayrılmış</option>
                <option value="suspended" {{ isset($personel) && $personel->status === 'suspended' ? 'selected' : '' }}>Askıda</option>
            </select>
        </div>
    </div>
</form>
