{{-- Generated by Cursor prompt — module: Personel — date: 2026-03-15 --}}
@extends('layouts.app')

@section('title', 'Personel Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Personel Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Personel Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">Tüm personelleri görüntüleyin ve yönetin.</p>
    </div>
    <div class="flex items-center gap-2">
        @can('personel.export')
        <button onclick="exportPersonel('excel')" class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
            <svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg>
            Excel
        </button>
        @endcan
        @can('personel.create')
        <button onclick="openCreateModal()" class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
            Yeni Personel
        </button>
        @endcan
    </div>
@endsection

@section('content')

{{-- Filtreler --}}
<div class="bg-white rounded-xl border border-gray-100 p-4 mb-5 shadow-sm">
    <div class="grid grid-cols-1 md:grid-cols-4 gap-3">
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Departman</label>
            <select id="filterDept" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($departments ?? [] as $dept)
                    <option value="{{ $dept->id }}">{{ $dept->name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Durum</label>
            <select id="filterStatus" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                <option value="active">Aktif</option>
                <option value="terminated">Ayrılmış</option>
                <option value="on_leave">İzinde</option>
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Arama</label>
            <input type="text" id="filterSearch" placeholder="Ad, soyad veya e-posta..." class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div class="flex items-end">
            <button onclick="reloadTable()" class="w-full px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">
                Filtrele
            </button>
        </div>
    </div>
</div>

{{-- Personel Tablosu --}}
<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm" id="personelTable">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Personel</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Departman</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Pozisyon</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">İşe Giriş</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Durum</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">İşlemler</th>
                </tr>
            </thead>
            <tbody id="personelTableBody" class="divide-y divide-gray-50">
                <tr>
                    <td colspan="6" class="px-4 py-8 text-center text-gray-400 text-sm">Yükleniyor...</td>
                </tr>
            </tbody>
        </table>
    </div>

    {{-- Pagination --}}
    <div class="px-4 py-3 border-t border-gray-100 flex items-center justify-between">
        <div class="text-xs text-gray-500" id="tableInfo">— kayıt gösteriliyor</div>
        <div class="flex items-center gap-1" id="tablePagination"></div>
    </div>
</div>

{{-- Personel Detay Kartı Alanı --}}
<div id="personelCardArea" class="mt-5 hidden"></div>

@endsection

@push('scripts')
<script src="{{ asset('js/admin/personel.js') }}"></script>
<script>
    const PERSONEL_URLS = {
        list:   '{{ route("admin.personel.index") }}',
        create: '{{ route("admin.personel.create") }}',
        store:  '{{ route("admin.personel.store") }}',
        edit:   (id) => `/admin/personel/${id}/edit`,
        update: (id) => `/admin/personel/${id}`,
        destroy:(id) => `/admin/personel/${id}`,
        card:   (id) => `/admin/personel/${id}/card`,
        export: '{{ route("admin.personel.exportExcel") }}',
    };

    loadPersonelTable();

    function loadPersonelTable(page = 1) {
        const params = {
            page,
            search: document.getElementById('filterSearch').value,
            department_id: document.getElementById('filterDept').value,
            status: document.getElementById('filterStatus').value,
        };
        axios.get(PERSONEL_URLS.list, { params }).then(res => {
            renderTable(res.data);
        });
    }

    function renderTable(data) {
        const tbody = document.getElementById('personelTableBody');
        if (!data.data.length) {
            tbody.innerHTML = `<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">Kayıt bulunamadı</td></tr>`;
            return;
        }
        tbody.innerHTML = data.data.map(p => `
            <tr class="hover:bg-gray-50 transition-colors">
                <td class="px-4 py-3">
                    <div class="flex items-center gap-3">
                        <div class="w-9 h-9 rounded-full bg-[#02E0FB]/20 text-[#02E0FB] font-bold flex items-center justify-center text-sm">
                            ${p.first_name[0]}${p.last_name[0]}
                        </div>
                        <div>
                            <p class="font-medium text-gray-800">${p.first_name} ${p.last_name}</p>
                            <p class="text-xs text-gray-400">${p.email || '—'}</p>
                        </div>
                    </div>
                </td>
                <td class="px-4 py-3 text-gray-600">${p.department?.name || '—'}</td>
                <td class="px-4 py-3 text-gray-600">${p.position?.title || '—'}</td>
                <td class="px-4 py-3 text-gray-600">${p.hire_date ? new Date(p.hire_date).toLocaleDateString('tr-TR') : '—'}</td>
                <td class="px-4 py-3">
                    <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${statusBadge(p.status)}">
                        ${statusLabel(p.status)}
                    </span>
                </td>
                <td class="px-4 py-3">
                    <div class="flex items-center justify-end gap-1">
                        <button onclick="openCardView(${p.id})" class="p-1.5 text-gray-400 hover:text-[#02E0FB] hover:bg-blue-50 rounded-lg transition-colors" title="Kart Görünümü">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"/><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z"/></svg>
                        </button>
                        <button onclick="openEditModal(${p.id})" class="p-1.5 text-gray-400 hover:text-amber-500 hover:bg-amber-50 rounded-lg transition-colors" title="Düzenle">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                        </button>
                        <button onclick="confirmDelete(PERSONEL_URLS.destroy(${p.id}), () => loadPersonelTable())" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg transition-colors" title="Sil">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                        </button>
                    </div>
                </td>
            </tr>
        `).join('');
        document.getElementById('tableInfo').textContent = `${data.total} kayıttan ${data.data.length} gösteriliyor`;
    }

    function statusBadge(s) {
        return {
            active: 'bg-green-100 text-green-700',
            terminated: 'bg-red-100 text-red-700',
            on_leave: 'bg-yellow-100 text-yellow-700',
            suspended: 'bg-gray-100 text-gray-600',
        }[s] || 'bg-gray-100 text-gray-600';
    }

    function statusLabel(s) {
        return { active: 'Aktif', terminated: 'Ayrılmış', on_leave: 'İzinde', suspended: 'Askıda' }[s] || s;
    }

    function reloadTable() { loadPersonelTable(1); }

    function openCreateModal() {
        axios.get(PERSONEL_URLS.create).then(res => {
            document.getElementById('modalTitle').textContent = 'Yeni Personel Ekle';
            document.getElementById('modalBody').innerHTML = res.data.html;
            document.getElementById('modalFooter').innerHTML = `
                <button onclick="closeModal()" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
                <button onclick="submitPersonelForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg">Kaydet</button>
            `;
            openModal();
        });
    }

    function openEditModal(id) {
        axios.get(PERSONEL_URLS.edit(id)).then(res => {
            document.getElementById('modalTitle').textContent = 'Personel Düzenle';
            document.getElementById('modalBody').innerHTML = res.data.html;
            document.getElementById('modalFooter').innerHTML = `
                <button onclick="closeModal()" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
                <button onclick="submitPersonelForm('${PERSONEL_URLS.update(id)}', 'PUT')" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg">Güncelle</button>
            `;
            openModal();
        });
    }

    function submitPersonelForm(url = PERSONEL_URLS.store, method = 'POST') {
        const form = document.getElementById('personelForm');
        const data = Object.fromEntries(new FormData(form).entries());
        axios({ method, url, data }).then(res => {
            closeModal();
            toast('success', res.data.message);
            loadPersonelTable();
        });
    }

    function openCardView(id) {
        axios.get(PERSONEL_URLS.card(id)).then(res => {
            const area = document.getElementById('personelCardArea');
            area.innerHTML = res.data.html;
            area.classList.remove('hidden');
            area.scrollIntoView({ behavior: 'smooth' });
        });
    }

    function exportPersonel(type) {
        window.location.href = `${PERSONEL_URLS.export}?format=${type}`;
    }

    function openModal() {
        document.getElementById('globalModal').classList.remove('hidden');
    }

    function closeModal() {
        document.getElementById('globalModal').classList.add('hidden');
    }

    document.getElementById('modalClose')?.addEventListener('click', closeModal);
    document.getElementById('modalBackdrop')?.addEventListener('click', closeModal);
</script>
@endpush
