{{-- Generated by Cursor prompt — module: Avans Yönetimi — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Avans Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Avans Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Avans Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">Personel avans taleplerini yönetin ve onaylayın.</p>
    </div>
    @can('advance.request')
    <button onclick="openCreateAdvanceModal()"
        class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
        Yeni Avans Talebi
    </button>
    @endcan
@endsection

@section('content')

{{-- KPI --}}
<div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-5">
    @foreach([
        ['id'=>'adv-pending','label'=>'Bekleyen','color'=>'yellow'],
        ['id'=>'adv-approved','label'=>'Onaylanan','color'=>'green'],
        ['id'=>'adv-rejected','label'=>'Reddedilen','color'=>'red'],
        ['id'=>'adv-repaid','label'=>'Geri Ödenen','color'=>'blue'],
    ] as $k)
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-4">
        <p class="text-xs text-gray-500">{{ $k['label'] }}</p>
        <p class="text-2xl font-bold text-gray-900 mt-0.5" id="{{ $k['id'] }}">—</p>
    </div>
    @endforeach
</div>

{{-- Filtreler + Tablo --}}
<div class="bg-white rounded-xl border border-gray-100 p-4 mb-4 shadow-sm">
    <div class="grid grid-cols-2 md:grid-cols-4 gap-3">
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Personel</label>
            <select id="advPersonel" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($personels as $p)
                    <option value="{{ $p->id }}">{{ $p->first_name }} {{ $p->last_name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Durum</label>
            <select id="advStatus" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                <option value="pending">Bekleyen</option>
                <option value="approved">Onaylanan</option>
                <option value="rejected">Reddedilen</option>
                <option value="repaid">Geri Ödenen</option>
                <option value="cancelled">İptal</option>
            </select>
        </div>
        <div class="flex items-end md:col-span-2">
            <button onclick="loadAdvances()" class="w-full px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Filtrele</button>
        </div>
    </div>
</div>

<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Personel</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">Tutar</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Gerekçe</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Tarih</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Durum</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">İşlem</th>
                </tr>
            </thead>
            <tbody id="advTableBody" class="divide-y divide-gray-50">
                <tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
            </tbody>
        </table>
    </div>
</div>

@endsection

@push('scripts')
<script>
const ADV_URLS = {
    list:    '{{ route("admin.advance.index") }}',
    create:  '{{ route("admin.advance.create") }}',
    store:   '{{ route("admin.advance.store") }}',
    approve: id => `/admin/advances/requests/${id}/approve`,
    reject:  id => `/admin/advances/requests/${id}/reject`,
    cancel:  id => `/admin/advances/requests/${id}/cancel`,
    destroy: id => `/admin/advances/requests/${id}`,
};

const statusMap = {
    pending:   { label: 'Bekliyor',      bg: 'bg-yellow-100', text: 'text-yellow-700' },
    approved:  { label: 'Onaylandı',     bg: 'bg-green-100',  text: 'text-green-700' },
    rejected:  { label: 'Reddedildi',    bg: 'bg-red-100',    text: 'text-red-700' },
    repaid:    { label: 'Geri Ödendi',   bg: 'bg-blue-100',   text: 'text-blue-700' },
    cancelled: { label: 'İptal',         bg: 'bg-gray-100',   text: 'text-gray-600' },
};

document.addEventListener('DOMContentLoaded', () => {
    loadAdvances();
    ['pending','approved','rejected','repaid'].forEach(s => {
        axios.get(ADV_URLS.list, { params: { status: s, per_page: 1 } }).then(r => {
            const el = document.getElementById(`adv-${s}`);
            if (el) el.textContent = r.data.total;
        });
    });
});

function loadAdvances(page = 1) {
    axios.get(ADV_URLS.list, { params: {
        page,
        personel_id: document.getElementById('advPersonel').value,
        status: document.getElementById('advStatus').value,
        per_page: 15,
    }}).then(res => renderAdvTable(res.data));
}

function renderAdvTable(data) {
    const tbody = document.getElementById('advTableBody');
    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">Kayıt bulunamadı</td></tr>`;
        return;
    }
    tbody.innerHTML = data.data.map(a => {
        const sc = statusMap[a.status] || { label: a.status, bg: 'bg-gray-100', text: 'text-gray-600' };
        const amount = new Intl.NumberFormat('tr-TR', { style:'currency', currency: a.currency||'TRY' }).format(a.amount);
        const date   = new Date(a.created_at).toLocaleDateString('tr-TR');
        return `
        <tr class="hover:bg-gray-50 transition-colors">
            <td class="px-4 py-3">
                <div class="flex items-center gap-2">
                    <div class="w-7 h-7 rounded-full bg-[#02E0FB]/15 text-[#02E0FB] text-xs font-bold flex items-center justify-center">
                        ${(a.personel?.first_name?.[0]||'') + (a.personel?.last_name?.[0]||'')}
                    </div>
                    <span class="font-medium text-gray-800">${a.personel?.first_name||''} ${a.personel?.last_name||''}</span>
                </div>
            </td>
            <td class="px-4 py-3 text-right font-bold text-gray-800">${amount}</td>
            <td class="px-4 py-3 text-gray-600 text-sm max-w-xs truncate">${a.reason || '—'}</td>
            <td class="px-4 py-3 text-gray-500 text-sm">${date}</td>
            <td class="px-4 py-3 text-center">
                <span class="inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${sc.bg} ${sc.text}">${sc.label}</span>
            </td>
            <td class="px-4 py-3">
                <div class="flex items-center justify-end gap-1">
                    ${a.status === 'pending' ? `
                    <button onclick="approveAdvance(${a.id})" class="p-1.5 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded-lg" title="Onayla">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
                    </button>
                    <button onclick="rejectAdvance(${a.id})" class="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg" title="Reddet">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>` : ''}
                    <button onclick="confirmDelete(ADV_URLS.destroy(${a.id}), loadAdvances)" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg" title="Sil">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                    </button>
                </div>
            </td>
        </tr>`;
    }).join('');
}

function openCreateAdvanceModal() {
    axios.get(ADV_URLS.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni Avans Talebi';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitAdvanceForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Talep Oluştur</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function submitAdvanceForm() {
    const form = document.getElementById('advanceForm');
    const data = Object.fromEntries(new FormData(form).entries());
    axios.post(ADV_URLS.store, data).then(res => {
        document.getElementById('globalModal').classList.add('hidden');
        toast('success', res.data.message);
        loadAdvances();
    });
}

function approveAdvance(id) {
    Swal.fire({ title: 'Avansı Onayla', text: 'Bu avans talebini onaylamak istiyor musunuz?', icon: 'question',
        showCancelButton: true, confirmButtonColor: '#02E0FB', cancelButtonColor: '#6B7280',
        confirmButtonText: 'Onayla', cancelButtonText: 'İptal'
    }).then(r => {
        if (r.isConfirmed) axios.post(ADV_URLS.approve(id)).then(res => { toast('success', res.data.message); loadAdvances(); });
    });
}

function rejectAdvance(id) {
    Swal.fire({ title: 'Avansı Reddet', input: 'textarea', inputPlaceholder: 'Ret gerekçesi...',
        showCancelButton: true, confirmButtonColor: '#FA6001', cancelButtonColor: '#6B7280',
        confirmButtonText: 'Reddet', cancelButtonText: 'İptal', inputValidator: v => !v && 'Gerekçe zorunludur!'
    }).then(r => {
        if (r.isConfirmed) axios.post(ADV_URLS.reject(id), { reason: r.value }).then(res => { toast('success', res.data.message); loadAdvances(); });
    });
}
</script>
@endpush
