{{-- Generated by Cursor prompt — module: Rol & Yetki Yönetimi (Production Ready) — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Rol & Yetki Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Rol & Yetki Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Rol & Yetki Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">Sistem rollerini ve modül bazlı izinleri yönetin.</p>
    </div>
    @can('role.manage')
    <button onclick="openCreateRoleModal()" class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
        Yeni Rol
    </button>
    @endcan
@endsection

@section('content')

<div class="grid grid-cols-1 lg:grid-cols-3 gap-6">

    {{-- Sol: Rol Listesi --}}
    <div class="lg:col-span-1">
        <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
            <div class="px-4 py-3.5 border-b border-gray-100">
                <h3 class="font-semibold text-gray-800">Roller</h3>
            </div>
            <div id="rolesList" class="divide-y divide-gray-50">
                <div class="p-4 text-center text-gray-400 text-sm animate-pulse">Yükleniyor...</div>
            </div>
        </div>
    </div>

    {{-- Sağ: Permission Matrix --}}
    <div class="lg:col-span-2">
        <div id="permissionPanel" class="bg-white rounded-xl border border-gray-100 shadow-sm">
            <div class="px-5 py-4 border-b border-gray-100 flex items-center justify-between">
                <div>
                    <h3 class="font-semibold text-gray-800" id="permPanelTitle">İzinler</h3>
                    <p class="text-xs text-gray-400 mt-0.5">Bir rol seçerek izinleri düzenleyin</p>
                </div>
                <button id="savePermBtn" onclick="savePermissions()" class="hidden px-4 py-2 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg transition-colors">
                    💾 Kaydet
                </button>
            </div>

            <div id="permissionContent" class="p-5">
                {{-- Başlangıç hali --}}
                <div class="flex flex-col items-center justify-center py-16 text-gray-400">
                    <svg class="w-16 h-16 text-gray-100 mb-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/>
                    </svg>
                    <p class="font-medium">Sol taraftan bir rol seçin</p>
                    <p class="text-sm mt-1">Rol izinlerini checkbox'larla düzenleyebilirsiniz</p>
                </div>
            </div>
        </div>

        {{-- Kullanıcı-Rol Atama --}}
        <div class="bg-white rounded-xl border border-gray-100 shadow-sm mt-5">
            <div class="px-5 py-4 border-b border-gray-100">
                <h3 class="font-semibold text-gray-800">Kullanıcı Rol Atamaları</h3>
                <p class="text-xs text-gray-400 mt-0.5">Kullanıcılara hızlıca rol atayın</p>
            </div>
            <div class="p-5" id="userRolePanel">
                <div class="flex flex-col md:flex-row gap-3">
                    <div class="flex-1">
                        <label class="block text-xs font-medium text-gray-500 mb-1">Kullanıcı</label>
                        <select id="assignUserId" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                            <option value="">— Kullanıcı seçin —</option>
                        </select>
                    </div>
                    <div class="flex-1">
                        <label class="block text-xs font-medium text-gray-500 mb-1">Rol</label>
                        <select id="assignRoleId" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                            <option value="">— Rol seçin —</option>
                        </select>
                    </div>
                    <div class="flex items-end">
                        <button onclick="assignRoleToUser()" class="w-full md:w-auto px-5 py-2 text-sm font-semibold text-white bg-[#FA6001] hover:bg-orange-500 rounded-lg transition-colors">
                            Ata
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
const RBAC_URLS = {
    roles:       '{{ route("admin.roles.list") }}',
    permissions: '{{ route("admin.permissions.list") }}',
    rolePerms:   id => `/admin/roles/${id}/permissions`,
    syncPerms:   id => `/admin/roles/${id}/permissions`,
    storeRole:   '{{ route("admin.roles.store") }}',
    destroyRole: id => `/admin/roles/${id}`,
    users:       '{{ route("admin.roles.users") }}',
    usersByRole: id => `/admin/roles/${id}/users`,
    assignRole:  '{{ route("admin.roles.assign-user") }}',
    revokeRole:  '{{ route("admin.roles.revoke-user") }}',
};

let selectedRoleId = null;
let allPermissions = [];
let rolePermIds    = [];

document.addEventListener('DOMContentLoaded', () => {
    loadRoles();
    loadAllPermissions();
    loadUsers();
});

function loadRoles() {
    axios.get(RBAC_URLS.roles).then(res => {
        const container = document.getElementById('rolesList');
        const roleSelect = document.getElementById('assignRoleId');

        if (!res.data.data.length) {
            container.innerHTML = `<div class="p-4 text-center text-gray-400 text-sm">Rol bulunamadı</div>`;
            return;
        }

        roleSelect.innerHTML = `<option value="">— Rol seçin —</option>`;
        container.innerHTML = res.data.data.map(r => {
            const isSystem = ['super_admin','company_admin','hr_manager','manager','employee'].includes(r.name);
            return `
            <div class="relative group/item" id="roleWrap-${r.id}">
                <button onclick="selectRole(${r.id}, '${r.name}')"
                    class="w-full flex items-center justify-between px-4 py-3.5 text-left hover:bg-[#02E0FB]/5 transition-colors"
                    id="roleItem-${r.id}">
                    <div class="flex items-center gap-3 min-w-0 flex-1">
                        <div class="w-8 h-8 rounded-lg bg-gradient-to-br from-[#02E0FB]/20 to-[#FA6001]/20 flex items-center justify-center shrink-0">
                            <svg class="w-4 h-4 text-[#02E0FB]" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z"/>
                            </svg>
                        </div>
                        <div class="min-w-0">
                            <p class="font-medium text-gray-800 text-sm truncate">${r.name}</p>
                            <p class="text-xs text-gray-400">${r.users_count ?? 0} kullanıcı</p>
                        </div>
                    </div>
                    <svg class="w-4 h-4 text-gray-300 group-hover:text-[#02E0FB] transition-colors shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/>
                    </svg>
                </button>
                ${!isSystem ? `
                <button onclick="deleteRole(${r.id}, '${r.name}')"
                    class="absolute right-2 top-1/2 -translate-y-1/2 p-1.5 text-gray-300 hover:text-red-500 hover:bg-red-50 rounded-lg opacity-0 group-hover/item:opacity-100 transition-all"
                    title="Rolü Sil">
                    <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/>
                    </svg>
                </button>` : ''}
            </div>`;
        }).join('');

        res.data.data.forEach(r => {
            roleSelect.innerHTML += `<option value="${r.id}">${r.name}</option>`;
        });
    }).catch(() => {
        document.getElementById('rolesList').innerHTML = `<div class="p-4 text-center text-red-400 text-sm">Roller yüklenemedi</div>`;
    });
}

function selectRole(roleId, roleName) {
    selectedRoleId = roleId;

    document.querySelectorAll('[id^="roleItem-"]').forEach(el => {
        el.classList.remove('bg-[#02E0FB]/10', 'border-l-4', 'border-l-[#02E0FB]');
    });
    const active = document.getElementById(`roleItem-${roleId}`);
    active?.classList.add('bg-[#02E0FB]/10', 'border-l-4', 'border-l-[#02E0FB]');

    document.getElementById('permPanelTitle').textContent = `${roleName} — Izinler`;
    document.getElementById('savePermBtn').classList.remove('hidden');

    axios.get(RBAC_URLS.rolePerms(roleId)).then(res => {
        rolePermIds = res.data.permission_ids || [];
        renderPermissions();
        loadRoleUsers(roleId);
    });
}

function loadRoleUsers(roleId) {
    axios.get(RBAC_URLS.usersByRole(roleId)).then(res => {
        const list = document.getElementById('roleUsersList');
        if (!list) return;
        if (!res.data.data.length) {
            list.innerHTML = `<span class="text-xs text-gray-400">Bu rol atanmış kullanıcı yok</span>`;
            return;
        }
        list.innerHTML = res.data.data.map(u =>
            `<span class="inline-flex items-center gap-1 px-2 py-0.5 bg-gray-100 rounded-full text-xs text-gray-700">${u.name}</span>`
        ).join(' ');
    });
}

function deleteRole(roleId, roleName) {
    Swal.fire({
        title: 'Rolü Sil',
        text: `"${roleName}" rolünü silmek istediğinize emin misiniz?`,
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#FA6001',
        cancelButtonColor: '#6B7280',
        confirmButtonText: 'Evet, Sil',
        cancelButtonText: 'İptal',
    }).then(r => {
        if (r.isConfirmed) {
            axios.delete(RBAC_URLS.destroyRole(roleId)).then(res => {
                toast('success', res.data.message);
                if (selectedRoleId === roleId) {
                    selectedRoleId = null;
                    document.getElementById('permPanelTitle').textContent = 'İzinler';
                    document.getElementById('savePermBtn').classList.add('hidden');
                    document.getElementById('permissionContent').innerHTML = `
                        <div class="flex flex-col items-center justify-center py-16 text-gray-400">
                            <p class="font-medium">Rol silindi</p>
                            <p class="text-sm mt-1">Yeni bir rol seçin</p>
                        </div>`;
                }
                loadRoles();
            }).catch(err => {
                const msg = err.response?.data?.message || 'Rol silinemedi.';
                toast('error', msg);
            });
        }
    });
}

function loadAllPermissions() {
    axios.get(RBAC_URLS.permissions).then(res => {
        allPermissions = res.data.data || [];
    }).catch(() => {});
}

function renderPermissions() {
    const content = document.getElementById('permissionContent');

    const grouped = {};
    allPermissions.forEach(p => {
        const parts  = p.name.split('.');
        const module = parts[0] || 'genel';
        if (!grouped[module]) grouped[module] = [];
        grouped[module].push(p);
    });

    const moduleLabels = {
        dashboard: 'Dashboard', personel: 'Personel', leave: 'Izin',
        attendance: 'Puantaj', shift: 'Vardiya', company: 'Sirket',
        department: 'Departman', position: 'Pozisyon', asset: 'Envanter',
        advance: 'Avans', expense: 'Masraf', travel: 'Seyahat',
        vehicle: 'Arac', visitor: 'Ziyaretci', report: 'Raporlar',
        subscription: 'Abonelik', settings: 'Ayarlar', role: 'Roller',
        permission: 'Izinler', notification: 'Bildirimler', access_admin: 'Admin Erisim',
    };

    content.innerHTML = `
        <div class="space-y-5">
            <div class="flex items-center gap-3 mb-2">
                <label class="flex items-center gap-2 cursor-pointer text-sm font-medium text-[#02E0FB]">
                    <input type="checkbox" id="selectAll" onchange="toggleAll(this.checked)" class="w-4 h-4 rounded text-[#02E0FB]">
                    Tümünü Seç / Kaldır
                </label>
                <span class="text-xs text-gray-400" id="selectedCount">0 izin seçili</span>
            </div>
            ${Object.entries(grouped).map(([module, perms]) => `
            <div class="border border-gray-100 rounded-xl overflow-hidden">
                <div class="flex items-center justify-between px-4 py-2.5 bg-gray-50 border-b border-gray-100">
                    <span class="text-sm font-semibold text-gray-700">${moduleLabels[module] || module}</span>
                    <label class="flex items-center gap-1.5 cursor-pointer text-xs text-gray-500">
                        <input type="checkbox" class="module-toggle w-3.5 h-3.5 rounded text-[#02E0FB]"
                            data-module="${module}"
                            onchange="toggleModule('${module}', this.checked)"
                            ${perms.every(p => rolePermIds.includes(p.id)) ? 'checked' : ''}>
                        Tümü
                    </label>
                </div>
                <div class="grid grid-cols-2 sm:grid-cols-3 gap-0 divide-x divide-y divide-gray-50">
                    ${perms.map(p => {
                        const action = p.name.split('.')[1] || p.name;
                        const isChecked = rolePermIds.includes(p.id);
                        return `
                        <label class="flex items-center gap-2.5 px-3 py-2.5 hover:bg-[#02E0FB]/5 cursor-pointer transition-colors" title="${p.name}">
                            <input type="checkbox" name="permissions[]" value="${p.id}"
                                class="perm-check w-4 h-4 rounded text-[#02E0FB] focus:ring-[#02E0FB]"
                                data-module="${module}"
                                ${isChecked ? 'checked' : ''}
                                onchange="updateCount()">
                            <span class="text-xs text-gray-700 font-medium truncate">${action}</span>
                        </label>`;
                    }).join('')}
                </div>
            </div>`).join('')}
            <div id="roleUsersSection">
                <div class="border border-gray-100 rounded-xl overflow-hidden">
                    <div class="px-4 py-2.5 bg-gray-50 border-b border-gray-100">
                        <span class="text-sm font-semibold text-gray-700">Bu Role Sahip Kullanıcılar</span>
                    </div>
                    <div class="px-4 py-3 flex flex-wrap gap-1.5" id="roleUsersList">
                        <span class="text-xs text-gray-400">Yükleniyor...</span>
                    </div>
                </div>
            </div>
        </div>`;

    updateCount();
}

function toggleAll(checked) {
    document.querySelectorAll('.perm-check').forEach(cb => cb.checked = checked);
    document.querySelectorAll('.module-toggle').forEach(cb => cb.checked = checked);
    updateCount();
}

function toggleModule(module, checked) {
    document.querySelectorAll(`.perm-check[data-module="${module}"]`).forEach(cb => cb.checked = checked);
    updateCount();
}

function updateCount() {
    const checked = document.querySelectorAll('.perm-check:checked').length;
    const total   = document.querySelectorAll('.perm-check').length;
    document.getElementById('selectedCount').textContent = `${checked}/${total} izin seçili`;
    document.getElementById('selectAll').checked        = checked === total;
    document.getElementById('selectAll').indeterminate  = checked > 0 && checked < total;
}

function savePermissions() {
    if (!selectedRoleId) return;
    document.getElementById('savePermBtn').disabled = true;

    const permIds = [...document.querySelectorAll('.perm-check:checked')].map(cb => parseInt(cb.value));

    axios.post(RBAC_URLS.syncPerms(selectedRoleId), { permission_ids: permIds }).then(res => {
        toast('success', res.data.message || 'Izinler kaydedildi.');
        rolePermIds = permIds;
    }).catch(err => {
        const msg = err.response?.data?.message || 'Kaydetme sırasında hata oluştu.';
        toast('error', msg);
    }).finally(() => {
        document.getElementById('savePermBtn').disabled = false;
    });
}

function loadUsers() {
    axios.get(RBAC_URLS.users).then(res => {
        const sel = document.getElementById('assignUserId');
        sel.innerHTML = `<option value="">— Kullanıcı seçin —</option>`;
        (res.data.data || []).forEach(u => {
            sel.innerHTML += `<option value="${u.id}">${u.name} (${u.email})</option>`;
        });
    }).catch(() => {});
}

function assignRoleToUser() {
    const userId = document.getElementById('assignUserId').value;
    const roleId = document.getElementById('assignRoleId').value;
    if (!userId || !roleId) { toast('warning', 'Kullanıcı ve rol seçimi zorunludur.'); return; }

    axios.post(RBAC_URLS.assignRole, { user_id: userId, role_id: roleId }).then(res => {
        toast('success', res.data.message || 'Rol atandı.');
        loadRoles();
        if (selectedRoleId) loadRoleUsers(selectedRoleId);
    }).catch(err => {
        const msg = err.response?.data?.message || 'Rol atama sırasında hata.';
        toast('error', msg);
    });
}

function openCreateRoleModal() {
    Swal.fire({
        title: 'Yeni Rol Oluştur',
        html: `
            <div class="text-left space-y-3">
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Rol Adı <span class="text-red-500">*</span></label>
                    <input type="text" id="newRoleName" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]" placeholder="ornek: finance_manager (snake_case)">
                </div>
                <div>
                    <label class="block text-sm font-medium text-gray-700 mb-1">Açıklama</label>
                    <input type="text" id="newRoleDesc" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]" placeholder="Kısa açıklama">
                </div>
            </div>`,
        showCancelButton: true,
        confirmButtonColor: '#02E0FB',
        confirmButtonText: 'Oluştur',
        cancelButtonText: 'İptal',
        preConfirm: () => {
            const name = document.getElementById('newRoleName').value.trim().toLowerCase();
            if (!name) { Swal.showValidationMessage('Rol adı zorunludur.'); return false; }
            if (!/^[a-z_]+$/.test(name)) { Swal.showValidationMessage('Rol adı yalnızca kucuk harf ve alt cizgi icerebilir.'); return false; }
            return { name, description: document.getElementById('newRoleDesc').value };
        }
    }).then(r => {
        if (r.isConfirmed) {
            axios.post(RBAC_URLS.storeRole, r.value).then(res => {
                toast('success', 'Rol oluşturuldu.');
                loadRoles();
            }).catch(err => {
                const msg = err.response?.data?.message || 'Rol oluşturulamadı.';
                toast('error', msg);
            });
        }
    });
}
</script>
@endpush
