<?php
// Generated by Cursor prompt — Service: AttendanceCalculatorService — date: 2026-03-15
// Puantaj Motoru: Giriş/Çıkış saatlerine göre aylık çalışma, eksik ve fazla mesai hesaplama

namespace App\Services;

use App\Modules\Puantaj\Models\TimeRecord;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Carbon\CarbonPeriod;

class AttendanceCalculatorService
{
    /**
     * Belirtilen ay için personelin tam puantaj özetini hesapla.
     */
    public function monthlySummary(int $personelId, int $companyId, int $year, int $month): array
    {
        $startDate = Carbon::create($year, $month, 1)->startOfMonth();
        $endDate   = $startDate->copy()->endOfMonth();

        // Şirket mesai ayarları
        $company      = DB::table('companies')->where('id', $companyId)->first();
        $settings     = json_decode($company?->settings ?? '{}', true);
        $workStart    = $settings['work_start'] ?? '09:00';
        $workEnd      = $settings['work_end']   ?? '18:00';
        $workDays     = $settings['working_days'] ?? [1, 2, 3, 4, 5]; // 1=Pzt, 7=Paz

        // Planlanan günlük çalışma dakikası
        $plannedDailyMinutes = $this->timeDiffInMinutes($workStart, $workEnd);

        // Onaylı izin günleri
        $leavedays = DB::table('leave_requests')
            ->where('personel_id', $personelId)
            ->where('status', 'approved')
            ->where('start_date', '<=', $endDate->toDateString())
            ->where('end_date', '>=', $startDate->toDateString())
            ->get();

        $leaveDates = collect();
        foreach ($leavedays as $leave) {
            $period = CarbonPeriod::create($leave->start_date, $leave->end_date);
            foreach ($period as $day) {
                $leaveDates->push($day->toDateString());
            }
        }

        // Resmi tatiller
        $holidays = DB::table('holidays')
            ->where(fn ($q) => $q->where('company_id', $companyId)->orWhereNull('company_id'))
            ->where('is_national', true)
            ->whereBetween('date', [$startDate->toDateString(), $endDate->toDateString()])
            ->pluck('date')
            ->toArray();

        // Tüm kayıtları çek
        $records = TimeRecord::where('personel_id', $personelId)
            ->where('company_id', $companyId)
            ->whereBetween(DB::raw('DATE(recorded_at)'), [$startDate->toDateString(), $endDate->toDateString()])
            ->orderBy('recorded_at')
            ->get()
            ->groupBy(fn ($r) => $r->recorded_at->toDateString());

        $dailyResults    = [];
        $totalWorkMin    = 0;
        $totalOvertimeMin= 0;
        $totalLateMin    = 0;
        $totalMissingMin = 0;
        $presentDays     = 0;
        $missingDays     = 0;
        $leaveDayCount   = 0;
        $holidayCount    = 0;

        // Ayın her gününü işle
        $period = CarbonPeriod::create($startDate, $endDate);
        foreach ($period as $date) {
            $dateStr  = $date->toDateString();
            $dayOfWeek= $date->dayOfWeekIso; // 1=Pzt, 7=Paz

            $isWorkDay  = in_array($dayOfWeek, $workDays);
            $isHoliday  = in_array($dateStr, $holidays);
            $isLeave    = $leaveDates->contains($dateStr);
            $dayRecords = $records->get($dateStr, collect());

            if ($isHoliday) { $holidayCount++; $dailyResults[$dateStr] = $this->emptyDay($dateStr, 'holiday'); continue; }
            if ($isLeave)   { $leaveDayCount++; $dailyResults[$dateStr] = $this->emptyDay($dateStr, 'leave'); continue; }
            if (!$isWorkDay){ $dailyResults[$dateStr] = $this->emptyDay($dateStr, 'weekend'); continue; }

            if ($dayRecords->isEmpty()) {
                $missingDays++;
                $totalMissingMin += $plannedDailyMinutes;
                $dailyResults[$dateStr] = $this->emptyDay($dateStr, 'absent');
                continue;
            }

            $calc = TimeRecord::calculateOvertimeAndLate($dayRecords, $workStart, $plannedDailyMinutes);

            $netWork    = $calc['net_work_minutes'];
            $overtime   = $calc['overtime_minutes'];
            $late        = $calc['late_minutes'];
            $missing     = max(0, $plannedDailyMinutes - $netWork);

            $totalWorkMin     += $netWork;
            $totalOvertimeMin += $overtime;
            $totalLateMin     += $late;
            $totalMissingMin  += $missing;

            if ($netWork > 0) $presentDays++;

            $firstIn  = $dayRecords->where('type', 'in')->sortBy('recorded_at')->first();
            $lastOut  = $dayRecords->where('type', 'out')->sortByDesc('recorded_at')->first();

            $dailyResults[$dateStr] = [
                'date'            => $dateStr,
                'day_name'        => $date->locale('tr')->isoFormat('ddd'),
                'status'          => $this->resolveStatus($calc, $netWork, $plannedDailyMinutes),
                'check_in'        => $firstIn?->recorded_at?->format('H:i'),
                'check_out'       => $lastOut?->recorded_at?->format('H:i'),
                'net_work_min'    => $netWork,
                'net_work_hours'  => round($netWork / 60, 2),
                'overtime_min'    => $overtime,
                'late_min'        => $late,
                'missing_min'     => $missing,
                'is_pair_complete'=> $calc['is_pair_complete'],
                'record_count'    => $dayRecords->count(),
            ];
        }

        $workingDaysInMonth = collect($dailyResults)->filter(fn ($d) => !in_array($d['status'] ?? '', ['weekend', 'holiday']))->count();

        $personel = \App\Modules\Personel\Models\Personel::find($personelId);

        return [
            'personel_id'            => $personelId,
            'personel_name'          => $personel ? $personel->first_name . ' ' . $personel->last_name : null,
            'year'                   => $year,
            'month'                  => $month,
            'month_name'             => $startDate->locale('tr')->isoFormat('MMMM YYYY'),
            'working_days_in_month'  => $workingDaysInMonth,
            'present_days'           => $presentDays,
            'missing_days'           => $missingDays,
            'total_work_days'        => $presentDays,
            'absent_days'            => $missingDays,
            'leave_days'             => $leaveDayCount,
            'holiday_count'          => $holidayCount,
            'total_work_hours'       => round($totalWorkMin / 60, 2),
            'total_overtime_hours'   => round($totalOvertimeMin / 60, 2),
            'total_overtime_minutes' => $totalOvertimeMin,
            'total_late_minutes'     => $totalLateMin,
            'total_missing_hours'    => round($totalMissingMin / 60, 2),
            'avg_work_hours'         => $presentDays > 0
                ? round(($totalWorkMin / 60) / $presentDays, 2) : 0,
            'efficiency_pct'         => $workingDaysInMonth > 0
                ? round(($presentDays / $workingDaysInMonth) * 100, 1) : 0,
            'daily'                  => $dailyResults,
        ];
    }

    /**
     * Şirketin tüm aktif personelleri için günlük özet (gerçek zamanlı dashboard).
     */
    public function dailyCompanySummary(int $companyId, string $date): Collection
    {
        $company   = DB::table('companies')->where('id', $companyId)->first();
        $settings  = json_decode($company?->settings ?? '{}', true);
        $workStart = $settings['work_start'] ?? '09:00';
        $plannedMin= $this->timeDiffInMinutes($workStart, $settings['work_end'] ?? '18:00');

        $records = TimeRecord::where('company_id', $companyId)
            ->whereDate('recorded_at', $date)
            ->with('personel')
            ->get()
            ->groupBy('personel_id');

        $personels = DB::table('personels')
            ->where('company_id', $companyId)
            ->where('is_active', true)
            ->whereNull('deleted_at')
            ->get();

        return $personels->map(function ($p) use ($records, $workStart, $plannedMin) {
            $dayRecs = $records->get($p->id, collect());

            if ($dayRecs->isEmpty()) {
                return [
                    'personel_id'   => $p->id,
                    'personel_name' => $p->first_name . ' ' . $p->last_name,
                    'status'        => 'absent',
                    'check_in'      => null,
                    'check_out'     => null,
                    'net_work_hours'=> 0,
                    'late_minutes'  => 0,
                    'overtime_minutes' => 0,
                    'is_pair_complete' => true,
                ];
            }

            $calc    = TimeRecord::calculateOvertimeAndLate($dayRecs, $workStart, $plannedMin);
            $firstIn = $dayRecs->where('type', 'in')->sortBy('recorded_at')->first();
            $lastOut = $dayRecs->where('type', 'out')->sortByDesc('recorded_at')->first();

            return [
                'personel_id'      => $p->id,
                'personel_name'    => $p->first_name . ' ' . $p->last_name,
                'status'           => $this->resolveStatus($calc, $calc['net_work_minutes'], $plannedMin),
                'check_in'         => $firstIn?->recorded_at?->format('H:i'),
                'check_out'        => $lastOut?->recorded_at?->format('H:i'),
                'net_work_hours'   => round($calc['net_work_minutes'] / 60, 2),
                'late_minutes'     => $calc['late_minutes'],
                'overtime_minutes' => $calc['overtime_minutes'],
                'is_pair_complete' => $calc['is_pair_complete'],
            ];
        });
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    private function timeDiffInMinutes(string $start, string $end): int
    {
        $s = Carbon::parse($start);
        $e = Carbon::parse($end);
        if ($e->lt($s)) $e->addDay();
        return $s->diffInMinutes($e);
    }

    private function resolveStatus(array $calc, int $netWork, int $plannedMin): string
    {
        if (!$calc['is_pair_complete']) return 'incomplete';
        if ($netWork === 0) return 'absent';
        if ($calc['late_minutes'] > 15) return 'late';
        if ($calc['overtime_minutes'] > 0) return 'overtime';
        if ($netWork >= $plannedMin * 0.9) return 'present';
        return 'partial';
    }

    private function emptyDay(string $date, string $status): array
    {
        return [
            'date'            => $date,
            'day_name'        => Carbon::parse($date)->locale('tr')->isoFormat('ddd'),
            'status'          => $status,
            'check_in'        => null,
            'check_out'       => null,
            'net_work_min'    => 0,
            'net_work_hours'  => 0,
            'overtime_min'    => 0,
            'late_min'        => 0,
            'missing_min'     => 0,
            'is_pair_complete'=> true,
            'record_count'    => 0,
        ];
    }
}
