{{-- Generated by Cursor prompt — module: Puantaj (Time Records) — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Puantaj Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Puantaj Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Puantaj Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">Giriş/çıkış kayıtlarını ve mesai hesaplamalarını görüntüleyin.</p>
    </div>
    <div class="flex items-center gap-2">
        @can('attendance.export')
        <button onclick="exportAttendance()"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
            <svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3M3 17V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"/></svg>
            Excel İndir
        </button>
        @endcan
        @can('attendance.create')
        <button onclick="openManualEntryModal()"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
            Manuel Kayıt
        </button>
        @endcan
    </div>
@endsection

@section('content')

{{-- Sekmeler --}}
<div class="flex gap-1 border-b border-gray-200 mb-5">
    <button onclick="setAttTab('log')" id="atab-log" class="px-4 py-2.5 text-sm font-medium border-b-2 border-[#02E0FB] text-[#02E0FB] transition-all">Giriş/Çıkış Logu</button>
    <button onclick="setAttTab('summary')" id="atab-summary" class="px-4 py-2.5 text-sm font-medium border-b-2 border-transparent text-gray-500 hover:text-gray-700 transition-all">Günlük Özet</button>
</div>

{{-- Filtreler --}}
<div class="bg-white rounded-xl border border-gray-100 p-4 mb-4 shadow-sm">
    <div class="grid grid-cols-2 md:grid-cols-5 gap-3">
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Personel</label>
            <select id="attPersonel" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($personels as $p)
                    <option value="{{ $p->id }}">{{ $p->first_name }} {{ $p->last_name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Başlangıç</label>
            <input type="date" id="attDateFrom" value="{{ today()->toDateString() }}" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Bitiş</label>
            <input type="date" id="attDateTo" value="{{ today()->toDateString() }}" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div id="logTypeFilter">
            <label class="block text-xs font-medium text-gray-500 mb-1">Tür</label>
            <select id="attType" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                <option value="in">Giriş</option>
                <option value="out">Çıkış</option>
                <option value="break_start">Mola Başlangıç</option>
                <option value="break_end">Mola Bitiş</option>
            </select>
        </div>
        <div class="flex items-end">
            <button onclick="loadAttendance()" class="w-full px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Filtrele</button>
        </div>
    </div>
</div>

{{-- LOG GÖRÜNÜMÜ --}}
<div id="view-log">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50 border-b border-gray-100">
                    <tr>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Personel</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Tür</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Kayıt Zamanı</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Kaynak</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Not</th>
                        <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">İşlem</th>
                    </tr>
                </thead>
                <tbody id="logTableBody" class="divide-y divide-gray-50">
                    <tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
                </tbody>
            </table>
        </div>
        <div class="px-4 py-3 border-t border-gray-100 flex items-center justify-between">
            <div class="text-xs text-gray-500" id="logTableInfo">—</div>
            <div id="logPagination"></div>
        </div>
    </div>
</div>

{{-- GÜNLÜK ÖZET --}}
<div id="view-summary" class="hidden">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50 border-b border-gray-100">
                    <tr>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Personel</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Giriş</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Çıkış</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Net Mesai</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Gecikme</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Fazla Mesai</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Durum</th>
                    </tr>
                </thead>
                <tbody id="summaryTableBody" class="divide-y divide-gray-50">
                    <tr><td colspan="7" class="px-4 py-8 text-center text-gray-400">Tarih seçip filtreleyiniz...</td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{{-- Manuel Kayıt Modal --}}
<div id="manualModal" class="hidden fixed inset-0 z-[110] flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-black/50" onclick="document.getElementById('manualModal').classList.add('hidden')"></div>
    <div class="relative bg-white rounded-2xl shadow-2xl w-full max-w-md z-10 p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-4">Manuel Giriş/Çıkış Kaydı</h3>
        <form id="manualForm" class="space-y-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Personel <span class="text-red-500">*</span></label>
                <select name="personel_id" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                    <option value="">— Personel seçin —</option>
                    @foreach($personels as $p)
                        <option value="{{ $p->id }}">{{ $p->first_name }} {{ $p->last_name }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Kayıt Türü <span class="text-red-500">*</span></label>
                <div class="grid grid-cols-2 gap-2">
                    @foreach(['in'=>['Giriş','green'],'out'=>['Çıkış','red'],'break_start'=>['Mola Başlangıç','yellow'],'break_end'=>['Mola Bitiş','blue']] as $val=>[$lbl,$color])
                    <label class="flex items-center gap-2 p-2.5 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-{{ $color }}-400 has-[:checked]:border-{{ $color }}-500 has-[:checked]:bg-{{ $color }}-50 transition-colors">
                        <input type="radio" name="type" value="{{ $val }}" class="w-3.5 h-3.5 text-{{ $color }}-500">
                        <span class="text-sm font-medium text-gray-700">{{ $lbl }}</span>
                    </label>
                    @endforeach
                </div>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Kayıt Tarihi ve Saati <span class="text-red-500">*</span></label>
                <input type="datetime-local" name="recorded_at" required
                    value="{{ now()->format('Y-m-d\TH:i') }}"
                    class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Not</label>
                <textarea name="note" rows="2" placeholder="Neden manuel kayıt oluşturuluyor..."
                    class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"></textarea>
            </div>
        </form>
        <div class="flex justify-end gap-3 mt-5">
            <button onclick="document.getElementById('manualModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitManualRecord()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Kaydet</button>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
const ATT_URLS = {
    list:    '{{ route("admin.attendance.index") }}',
    summary: '{{ route("admin.attendance.index") }}/daily-summary',
    store:   '{{ route("admin.attendance.record") }}',
    export:  '{{ route("admin.attendance.export") }}',
    destroy: id => `/admin/attendance/${id}`,
};

let currentAttTab = 'log';

document.addEventListener('DOMContentLoaded', loadAttendance);

function setAttTab(tab) {
    ['log','summary'].forEach(t => {
        document.getElementById(`view-${t}`).classList.toggle('hidden', t !== tab);
        const btn = document.getElementById(`atab-${t}`);
        btn.classList.toggle('border-[#02E0FB]', t === tab);
        btn.classList.toggle('text-[#02E0FB]', t === tab);
        btn.classList.toggle('border-transparent', t !== tab);
        btn.classList.toggle('text-gray-500', t !== tab);
    });
    document.getElementById('logTypeFilter').classList.toggle('hidden', tab !== 'log');
    currentAttTab = tab;
    loadAttendance();
}

function getFilters() {
    return {
        personel_id: document.getElementById('attPersonel').value,
        date_from:   document.getElementById('attDateFrom').value,
        date_to:     document.getElementById('attDateTo').value,
        type:        currentAttTab === 'log' ? document.getElementById('attType').value : undefined,
    };
}

function loadAttendance(page = 1) {
    if (currentAttTab === 'summary') {
        loadSummary();
    } else {
        loadLog(page);
    }
}

function loadLog(page = 1) {
    axios.get(ATT_URLS.list, { params: { ...getFilters(), page, per_page: 25 } }).then(res => {
        renderLogTable(res.data);
    });
}

const typeConfig = {
    in:          { label: 'Giriş',           bg: 'bg-green-100',  text: 'text-green-700',  dot: 'bg-green-500' },
    out:         { label: 'Çıkış',           bg: 'bg-red-100',    text: 'text-red-700',    dot: 'bg-red-500' },
    break_start: { label: 'Mola Başlangıç', bg: 'bg-yellow-100', text: 'text-yellow-700', dot: 'bg-yellow-500' },
    break_end:   { label: 'Mola Bitiş',     bg: 'bg-blue-100',   text: 'text-blue-700',   dot: 'bg-blue-500' },
};
const sourceConfig = {
    web:       { label: 'Web',      color: 'text-blue-600' },
    mobile:    { label: 'Mobil',    color: 'text-purple-600' },
    biometric: { label: 'Biyometrik', color: 'text-green-600' },
    manual:    { label: 'Manuel',   color: 'text-orange-600' },
};

function renderLogTable(data) {
    const tbody = document.getElementById('logTableBody');
    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400 text-sm">Kayıt bulunamadı</td></tr>`;
        return;
    }
    tbody.innerHTML = data.data.map(r => {
        const tc = typeConfig[r.type] || { label: r.type, bg: 'bg-gray-100', text: 'text-gray-600', dot: 'bg-gray-400' };
        const sc = sourceConfig[r.source] || { label: r.source, color: 'text-gray-500' };
        return `
        <tr class="hover:bg-gray-50 transition-colors">
            <td class="px-4 py-3">
                <div class="flex items-center gap-2">
                    <div class="w-7 h-7 rounded-full bg-[#02E0FB]/15 text-[#02E0FB] text-xs font-bold flex items-center justify-center">
                        ${r.personel_name?.split(' ').map(n=>n[0]).join('') || '?'}
                    </div>
                    <span class="font-medium text-gray-800 text-sm">${r.personel_name || '—'}</span>
                </div>
            </td>
            <td class="px-4 py-3">
                <span class="inline-flex items-center gap-1.5 px-2 py-1 rounded-full text-xs font-medium ${tc.bg} ${tc.text}">
                    <span class="w-1.5 h-1.5 rounded-full ${tc.dot}"></span>
                    ${tc.label}
                </span>
            </td>
            <td class="px-4 py-3 font-mono text-sm text-gray-800 font-medium">${r.recorded_at}</td>
            <td class="px-4 py-3">
                <span class="text-xs font-medium ${sc.color}">${sc.label}</span>
                ${r.is_manual ? '<span class="ml-1 text-xs text-orange-400">[MANUEL]</span>' : ''}
            </td>
            <td class="px-4 py-3 text-gray-500 text-xs max-w-xs truncate">${r.note || '—'}</td>
            <td class="px-4 py-3 text-right">
                <button onclick="confirmDelete(ATT_URLS.destroy(${r.id}), () => loadLog())" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg" title="Sil">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                </button>
            </td>
        </tr>`;
    }).join('');
    document.getElementById('logTableInfo').textContent = `${data.total} kayıt`;
}

function loadSummary() {
    const date = document.getElementById('attDateFrom').value;
    axios.get(`/admin/attendance/daily-summary`, { params: { date, personel_id: document.getElementById('attPersonel').value } }).then(res => {
        const tbody = document.getElementById('summaryTableBody');
        if (!res.data.data.length) {
            tbody.innerHTML = `<tr><td colspan="7" class="px-4 py-8 text-center text-gray-400">Bu tarihe ait kayıt bulunamadı</td></tr>`;
            return;
        }

        const statusConfig = {
            present:    { label: 'Mevcut',     bg: 'bg-green-100',  text: 'text-green-700' },
            late:       { label: 'Geç Geldi',  bg: 'bg-yellow-100', text: 'text-yellow-700' },
            overtime:   { label: 'Fazla Mesai',bg: 'bg-blue-100',   text: 'text-blue-700' },
            incomplete: { label: 'Eksik Kayıt',bg: 'bg-orange-100', text: 'text-orange-700' },
            absent:     { label: 'Devamsız',   bg: 'bg-red-100',    text: 'text-red-700' },
        };

        tbody.innerHTML = res.data.data.map(s => {
            const sc = statusConfig[s.status] || { label: s.status, bg: 'bg-gray-100', text: 'text-gray-600' };
            const lateClass = s.late_minutes > 0 ? 'text-red-600 font-semibold' : 'text-gray-400';
            const otClass   = s.overtime_minutes > 0 ? 'text-blue-600 font-semibold' : 'text-gray-400';
            return `
            <tr class="hover:bg-gray-50 transition-colors">
                <td class="px-4 py-3">
                    <div class="flex items-center gap-2">
                        <div class="w-7 h-7 rounded-full bg-[#02E0FB]/15 text-[#02E0FB] text-xs font-bold flex items-center justify-center">
                            ${s.personel_name?.split(' ').map(n=>n[0]).join('') || '?'}
                        </div>
                        <span class="font-medium text-gray-800">${s.personel_name}</span>
                    </div>
                </td>
                <td class="px-4 py-3 text-center font-mono font-medium ${s.check_in ? 'text-green-700' : 'text-gray-300'}">${s.check_in || '—'}</td>
                <td class="px-4 py-3 text-center font-mono font-medium ${s.check_out ? 'text-red-600' : 'text-gray-300'}">${s.check_out || '—'}</td>
                <td class="px-4 py-3 text-center font-semibold text-gray-800">${s.net_work_hours} sa</td>
                <td class="px-4 py-3 text-center ${lateClass}">${s.late_minutes > 0 ? s.late_minutes + ' dk' : '—'}</td>
                <td class="px-4 py-3 text-center ${otClass}">${s.overtime_minutes > 0 ? Math.round(s.overtime_minutes/60*10)/10 + ' sa' : '—'}</td>
                <td class="px-4 py-3 text-center">
                    <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${sc.bg} ${sc.text}">${sc.label}</span>
                    ${!s.is_pair_complete ? '<span class="ml-1 text-xs text-orange-500" title="Eşleşmemiş giriş/çıkış">⚠</span>' : ''}
                </td>
            </tr>`;
        }).join('');
    });
}

function openManualEntryModal() {
    document.getElementById('manualModal').classList.remove('hidden');
}

function submitManualRecord() {
    const form = document.getElementById('manualForm');
    const data = Object.fromEntries(new FormData(form).entries());
    if (!data.personel_id || !data.type || !data.recorded_at) {
        toast('warning', 'Lütfen zorunlu alanları doldurun.');
        return;
    }
    axios.post(ATT_URLS.store, data).then(res => {
        document.getElementById('manualModal').classList.add('hidden');
        toast('success', res.data.message);
        loadAttendance();
    });
}

function exportAttendance() {
    axios.get(ATT_URLS.export, { params: getFilters() }).then(res => {
        toast('info', res.data.message);
    });
}
</script>
@endpush
