{{-- Generated by Cursor prompt — module: Envanter _form — date: 2026-03-15 --}}
<form id="assetForm" class="space-y-4" novalidate>
    @csrf
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Varlık Türü <span class="text-red-500">*</span></label>
            <select name="asset_type_id" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="">— Tür seçin —</option>
                @foreach($assetTypes ?? [] as $t)
                    <option value="{{ $t->id }}" {{ isset($asset) && $asset->asset_type_id == $t->id ? 'selected' : '' }}>{{ $t->name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Varlık Adı <span class="text-red-500">*</span></label>
            <input type="text" name="name" value="{{ $asset->name ?? '' }}" required
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="Örn: Dell Latitude 5530">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Seri Numarası</label>
            <input type="text" name="serial" value="{{ $asset->serial ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] font-mono"
                placeholder="SN-XXXX-XXXX">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Barkod</label>
            <input type="text" name="barcode" value="{{ $asset->barcode ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] font-mono"
                placeholder="BC-XXXX">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Satın Alma Tarihi</label>
            <input type="date" name="purchase_date" value="{{ isset($asset) ? $asset->purchase_date?->format('Y-m-d') : '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Garanti Bitiş Tarihi</label>
            <input type="date" name="warranty_end" value="{{ isset($asset) ? $asset->warranty_end?->format('Y-m-d') : '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Alış Fiyatı (TRY)</label>
            <input type="number" name="price" value="{{ $asset->price ?? '' }}" step="0.01" min="0"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="0.00">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Konum</label>
            <input type="text" name="location" value="{{ $asset->location ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="Örn: İstanbul Ofisi, Kat 2">
        </div>
        <div class="md:col-span-2">
            <label class="block text-sm font-medium text-gray-700 mb-1">Durum</label>
            <div class="flex flex-wrap gap-2">
                @foreach(['available'=>'Müsait','maintenance'=>'Bakımda','retired'=>'Hizmet Dışı'] as $val=>$lbl)
                <label class="flex items-center gap-2 px-3 py-2 border-2 border-gray-200 rounded-lg cursor-pointer hover:border-[#02E0FB] has-[:checked]:border-[#02E0FB] has-[:checked]:bg-[#02E0FB]/5 transition-colors">
                    <input type="radio" name="status" value="{{ $val }}" class="w-3.5 h-3.5"
                        {{ (isset($asset) && $asset->status === $val) || (!isset($asset) && $val === 'available') ? 'checked' : '' }}>
                    <span class="text-sm font-medium text-gray-700">{{ $lbl }}</span>
                </label>
                @endforeach
            </div>
        </div>
    </div>
</form>
