{{-- Generated by Cursor prompt — module: Envanter & Zimmet — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Envanter Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Envanter Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-xl sm:text-2xl font-bold text-gray-900">Envanter & Zimmet</h1>
        <p class="text-xs sm:text-sm text-gray-500 mt-0.5">Şirket varlıklarını yönetin ve personele zimmetleyin.</p>
    </div>
    <div class="flex items-center gap-2">
        @can('asset.create')
        <button onclick="openCreateAssetModal()"
            class="inline-flex items-center justify-center gap-2 px-4 py-2.5 text-sm font-medium text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-xl transition-all shadow-sm w-full sm:w-auto">
            <svg class="w-4 h-4 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
            <span class="hidden sm:inline">Yeni Varlık</span>
            <span class="sm:hidden">Ekle</span>
        </button>
        @endcan
    </div>
@endsection

@section('content')

{{-- KPI Özet --}}
@php
$kpiCards = [
    ['label'=>'Toplam Varlık','id'=>'kpi-total','icon'=>'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4','bg'=>'bg-cyan-50','text'=>'text-cyan-600'],
    ['label'=>'Müsait','id'=>'kpi-available','icon'=>'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z','bg'=>'bg-green-50','text'=>'text-green-600'],
    ['label'=>'Zimmetli','id'=>'kpi-assigned','icon'=>'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z','bg'=>'bg-blue-50','text'=>'text-blue-600'],
    ['label'=>'Garanti Bitiyor','id'=>'kpi-warranty','icon'=>'M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z','bg'=>'bg-yellow-50','text'=>'text-yellow-600'],
];
@endphp
<div class="grid grid-cols-2 lg:grid-cols-4 gap-3 sm:gap-4 mb-5" id="assetKPIs">
    @foreach($kpiCards as $kpi)
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-3 sm:p-4 flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl {{ $kpi['bg'] }} flex items-center justify-center shrink-0">
            <svg class="w-5 h-5 {{ $kpi['text'] }}" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="{{ $kpi['icon'] }}"/>
            </svg>
        </div>
        <div class="min-w-0">
            <p class="text-xs text-gray-500">{{ $kpi['label'] }}</p>
            <p class="text-xl sm:text-2xl font-bold text-gray-900" id="{{ $kpi['id'] }}">—</p>
        </div>
    </div>
    @endforeach
</div>

{{-- Filtreler --}}
<div class="bg-white rounded-xl border border-gray-100 p-4 mb-4 shadow-sm">
    <div class="grid grid-cols-2 md:grid-cols-5 gap-3">
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Arama</label>
            <input type="text" id="assetSearch" placeholder="Ad, seri no, barkod..." class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Varlık Türü</label>
            <select id="assetTypeFilter" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($assetTypes as $t)
                    <option value="{{ $t->id }}">{{ $t->name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Durum</label>
            <select id="assetStatusFilter" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                <option value="available">Müsait</option>
                <option value="assigned">Zimmetli</option>
                <option value="maintenance">Bakımda</option>
                <option value="retired">Hizmet Dışı</option>
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Personel</label>
            <select id="assetPersonelFilter" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($personels as $p)
                    <option value="{{ $p->id }}">{{ $p->first_name }} {{ $p->last_name }}</option>
                @endforeach
            </select>
        </div>
        <div class="flex items-end">
            <button onclick="loadAssets()" class="w-full px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Filtrele</button>
        </div>
    </div>
</div>

{{-- Tablo --}}
<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Varlık</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Tür</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Seri No</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Zimmetli Personel</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Garanti</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Durum</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">İşlemler</th>
                </tr>
            </thead>
            <tbody id="assetTableBody" class="divide-y divide-gray-50">
                <tr><td colspan="7" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
            </tbody>
        </table>
    </div>
    <div class="px-4 py-3 border-t border-gray-100 flex items-center justify-between">
        <div class="text-xs text-gray-500" id="assetTableInfo">—</div>
        <div id="assetPagination"></div>
    </div>
</div>

{{-- Zimmet Modal --}}
<div id="assignAssetModal" class="hidden fixed inset-0 z-[110] flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-black/50" onclick="closeAssignModal()"></div>
    <div class="relative bg-white rounded-2xl shadow-2xl w-full max-w-md z-10 p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-1">Personele Zimmetle</h3>
        <p class="text-sm text-gray-400 mb-4" id="assignAssetName">—</p>
        <div class="space-y-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Personel <span class="text-red-500">*</span></label>
                <select id="assignPersonelId" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                    <option value="">— Personel seçin —</option>
                    @foreach($personels as $p)
                        <option value="{{ $p->id }}">{{ $p->first_name }} {{ $p->last_name }}</option>
                    @endforeach
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Teslim Durumu</label>
                <select id="assignCondition" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                    <option value="new">Yeni</option>
                    <option value="good" selected>İyi</option>
                    <option value="fair">Orta</option>
                    <option value="poor">Kötü</option>
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Not</label>
                <textarea id="assignNotes" rows="2" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]" placeholder="Opsiyonel..."></textarea>
            </div>
        </div>
        <div class="flex items-center justify-between mt-5">
            <button onclick="downloadZimmet()" class="flex items-center gap-2 text-xs text-gray-400 hover:text-[#02E0FB] transition-colors">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"/></svg>
                Zimmet Belgesi İndir
            </button>
            <div class="flex gap-3">
                <button onclick="closeAssignModal()" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
                <button onclick="submitAssignment()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Zimmetle</button>
            </div>
        </div>
    </div>
</div>

{{-- Global Modal (Create/Edit) --}}
<div id="globalModal" class="hidden fixed inset-0 z-50 flex items-center justify-center p-3 sm:p-4 bg-black/40">
    <div class="bg-white rounded-2xl shadow-2xl w-full max-w-2xl max-h-[90vh] overflow-y-auto p-5 sm:p-6 relative">
        <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="absolute top-3 right-3 text-gray-400 hover:text-gray-600">
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>
        <h3 id="modalTitle" class="text-lg font-semibold text-gray-800 mb-4">—</h3>
        <div id="modalBody"></div>
        <div id="modalFooter" class="flex justify-end gap-3 mt-5 pt-4 border-t border-gray-100"></div>
    </div>
</div>

{{-- İade Modal --}}
<div id="returnAssetModal" class="hidden fixed inset-0 z-[110] flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-black/50" onclick="document.getElementById('returnAssetModal').classList.add('hidden')"></div>
    <div class="relative bg-white rounded-2xl shadow-2xl w-full max-w-md z-10 p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-1">Varlık İadesi</h3>
        <p class="text-sm text-gray-400 mb-4" id="returnAssetName">—</p>
        <div class="space-y-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">İade Durumu</label>
                <select id="returnCondition" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                    <option value="good">İyi</option>
                    <option value="fair">Orta</option>
                    <option value="poor">Kötü</option>
                    <option value="damaged">Hasarlı</option>
                </select>
            </div>
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">İade Notu</label>
                <textarea id="returnNotes" rows="2" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]" placeholder="İade sebebi veya hasar notu..."></textarea>
            </div>
        </div>
        <div class="flex justify-end gap-3 mt-5">
            <button onclick="document.getElementById('returnAssetModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitReturn()" class="px-4 py-2 text-sm text-white bg-[#FA6001] hover:bg-orange-500 rounded-lg font-medium">İadeyi Onayla</button>
        </div>
    </div>
</div>

{{-- Varlık Türü Ekle Modal --}}
<div id="assetTypeModal" class="hidden fixed inset-0 z-[120] flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-black/50" onclick="closeAssetTypeModal()"></div>
    <div class="relative bg-white rounded-2xl shadow-2xl w-full max-w-sm z-10 p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-4">Yeni Varlık Türü</h3>
        <div class="space-y-4">
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">Tür Adı <span class="text-red-500">*</span></label>
                <input type="text" id="assetTypeName" placeholder="Örn: Dizüstü Bilgisayar"
                    class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
            </div>
        </div>
        <div class="flex justify-end gap-3 mt-5">
            <button onclick="closeAssetTypeModal()" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="storeAssetType()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Kaydet</button>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
const ASSET_URLS = {
    list:       '{{ route("admin.assets.list") }}',
    create:     '{{ route("admin.assets.create") }}',
    store:      '{{ route("admin.assets.store") }}',
    edit:       id => `/admin/assets/${id}/edit`,
    update:     id => `/admin/assets/${id}`,
    destroy:    id => `/admin/assets/${id}`,
    assign:     id => `/admin/assets/${id}/assign`,
    return:     id => `/admin/assets/${id}/return`,
    history:    id => `/admin/assets/${id}/history`,
    zimmetPdf:  id => `/admin/assets/assignments/${id}/pdf`,
    genSerial:  '{{ route("admin.assets.generate-serial") }}',
    genBarcode: '{{ route("admin.assets.generate-barcode") }}',
    storeType:  '{{ route("admin.assets.types.store") }}',
};

let activeAssetId = null;
let activeAssignmentId = null;

document.addEventListener('DOMContentLoaded', () => {
    loadAssets();
    loadKPIs();
});

function loadKPIs() {
    ['', 'available', 'assigned'].forEach(status => {
        const id = status ? `kpi-${status}` : 'kpi-total';
        axios.get(ASSET_URLS.list, { params: { status, per_page: 1 } })
            .then(res => { const el = document.getElementById(id); if (el) el.textContent = res.data.total; })
            .catch(() => { document.getElementById(id).textContent = '0'; });
    });
    axios.get(ASSET_URLS.list, { params: { warranty_expiring: 1, per_page: 1 } })
        .then(res => { const el = document.getElementById('kpi-warranty'); if (el) el.textContent = res.data.total; })
        .catch(() => {});
}

function loadAssets(page = 1) {
    const params = {
        page,
        search:        document.getElementById('assetSearch').value,
        asset_type_id: document.getElementById('assetTypeFilter').value,
        status:        document.getElementById('assetStatusFilter').value,
        personel_id:   document.getElementById('assetPersonelFilter').value,
        per_page: 20,
    };
    axios.get(ASSET_URLS.list, { params }).then(res => renderAssetTable(res.data)).catch(() => {
        document.getElementById('assetTableBody').innerHTML = '<tr><td colspan="7" class="px-4 py-8 text-center text-red-400 text-sm">Veri yüklenemedi.</td></tr>';
    });
}

const statusMap = {
    available:   { label: 'Müsait',       bg: 'bg-green-100', text: 'text-green-700' },
    assigned:    { label: 'Zimmetli',     bg: 'bg-blue-100',  text: 'text-blue-700' },
    maintenance: { label: 'Bakımda',      bg: 'bg-yellow-100',text: 'text-yellow-700' },
    retired:     { label: 'Hizmet Dışı', bg: 'bg-gray-100',  text: 'text-gray-500' },
};
const warrantyColorMap = {
    green: 'text-green-600', yellow: 'text-yellow-600 font-semibold', red: 'text-red-600 font-semibold', gray: 'text-gray-400',
};

function renderAssetTable(data) {
    const tbody = document.getElementById('assetTableBody');
    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="7" class="px-4 py-8 text-center text-gray-400 text-sm">Kayıt bulunamadı</td></tr>`;
        return;
    }
    tbody.innerHTML = data.data.map(a => {
        const sc = statusMap[a.status] || { label: a.status, bg: 'bg-gray-100', text: 'text-gray-600' };
        const wc = warrantyColorMap[a.warranty_status_color] || '';
        const warrantyLabel = a.warranty_end
            ? `<span class="${wc}">${new Date(a.warranty_end).toLocaleDateString('tr-TR')}</span>`
            : '<span class="text-gray-300">—</span>';

        return `
        <tr class="hover:bg-gray-50 transition-colors">
            <td class="px-4 py-3">
                <div>
                    <p class="font-medium text-gray-800">${a.name}</p>
                    ${a.barcode ? `<p class="text-xs text-gray-400 font-mono">🔖 ${a.barcode}</p>` : ''}
                </div>
            </td>
            <td class="px-4 py-3 text-gray-600 text-sm">${a.asset_type?.name || '—'}</td>
            <td class="px-4 py-3 font-mono text-xs text-gray-500">${a.serial || '—'}</td>
            <td class="px-4 py-3 text-sm">
                ${a.assigned_personel
                    ? `<div class="flex items-center gap-2">
                        <div class="w-6 h-6 rounded-full bg-blue-100 text-blue-600 text-xs font-bold flex items-center justify-center">
                            ${(a.assigned_personel.first_name?.[0]||'') + (a.assigned_personel.last_name?.[0]||'')}
                        </div>
                        <span class="text-gray-700">${a.assigned_personel.first_name} ${a.assigned_personel.last_name}</span>
                       </div>`
                    : '<span class="text-gray-300">—</span>'}
            </td>
            <td class="px-4 py-3 text-sm">${warrantyLabel}</td>
            <td class="px-4 py-3 text-center">
                <span class="inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${sc.bg} ${sc.text}">${sc.label}</span>
            </td>
            <td class="px-4 py-3">
                <div class="flex items-center justify-end gap-1">
                    ${a.status === 'available'
                        ? `<button onclick="openAssignModal(${a.id}, '${a.name}')" class="p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg" title="Zimmetle">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"/></svg>
                           </button>`
                        : ''}
                    ${a.status === 'assigned'
                        ? `<button onclick="openReturnModal(${a.id}, '${a.name}')" class="p-1.5 text-gray-400 hover:text-[#FA6001] hover:bg-orange-50 rounded-lg" title="İade Al">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"/></svg>
                           </button>`
                        : ''}
                    <button onclick="openEditAssetModal(${a.id})" class="p-1.5 text-gray-400 hover:text-amber-500 hover:bg-amber-50 rounded-lg" title="Düzenle">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                    </button>
                    <button onclick="confirmDelete(ASSET_URLS.destroy(${a.id}), loadAssets)" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg" title="Sil">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                    </button>
                </div>
            </td>
        </tr>`;
    }).join('');
    document.getElementById('assetTableInfo').textContent = `${data.total} kayıttan ${data.data.length} gösteriliyor`;
}

function openCreateAssetModal() {
    axios.get(ASSET_URLS.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni Varlık Ekle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitAssetForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Kaydet</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
        generateSerialField();
        generateBarcodeField();
    }).catch(() => toast('error', 'Form yüklenemedi.'));
}

function generateSerialField() {
    axios.get(ASSET_URLS.genSerial).then(res => {
        const el = document.getElementById('serialInput');
        if (el) el.value = res.data.serial;
    }).catch(() => {});
}

function generateBarcodeField() {
    axios.get(ASSET_URLS.genBarcode).then(res => {
        const el = document.getElementById('barcodeInput');
        if (el) el.value = res.data.barcode;
    }).catch(() => {});
}

function openCreateAssetTypeModal() {
    document.getElementById('assetTypeName').value = '';
    document.getElementById('assetTypeModal').classList.remove('hidden');
    document.getElementById('assetTypeName').focus();
}

function closeAssetTypeModal() {
    document.getElementById('assetTypeModal').classList.add('hidden');
}

function storeAssetType() {
    const name = document.getElementById('assetTypeName').value.trim();
    if (!name) { toast('warning', 'Tür adı zorunludur.'); return; }
    axios.post(ASSET_URLS.storeType, { name }).then(res => {
        closeAssetTypeModal();
        toast('success', res.data.message || 'Varlık türü oluşturuldu.');
        const opt = document.createElement('option');
        opt.value = res.data.data.id;
        opt.textContent = res.data.data.name;
        opt.selected = true;
        const sel = document.getElementById('assetTypeSelect');
        if (sel) { sel.appendChild(opt); sel.value = res.data.data.id; }
        const filter = document.getElementById('assetTypeFilter');
        if (filter) { const fo = document.createElement('option'); fo.value = res.data.data.id; fo.textContent = res.data.data.name; filter.appendChild(fo); }
    }).catch(err => {
        const msg = err.response?.data?.message || err.response?.data?.error || 'Kaydedilemedi.';
        if (err.response?.data?.errors) {
            const first = Object.values(err.response.data.errors).flat()[0];
            toast('error', first);
        } else {
            toast('error', msg);
        }
    });
}

function openEditAssetModal(id) {
    axios.get(ASSET_URLS.edit(id)).then(res => {
        document.getElementById('modalTitle').textContent = 'Varlığı Düzenle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitAssetForm('${ASSET_URLS.update(id)}','PUT')" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Güncelle</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    }).catch(() => toast('error', 'Varlık bilgileri yüklenemedi.'));
}

function submitAssetForm(url = ASSET_URLS.store, method = 'POST') {
    const form = document.getElementById('assetForm');
    if (!form) return;
    const data = Object.fromEntries(new FormData(form).entries());
    axios({ method, url, data }).then(res => {
        document.getElementById('globalModal').classList.add('hidden');
        toast('success', res.data.message);
        loadAssets();
        loadKPIs();
    }).catch(err => {
        const msg = err.response?.data?.message || err.response?.data?.error || 'Kaydedilemedi.';
        if (err.response?.data?.errors) {
            const first = Object.values(err.response.data.errors).flat()[0];
            toast('error', first);
        } else {
            toast('error', msg);
        }
    });
}

function openAssignModal(assetId, assetName) {
    activeAssetId = assetId;
    document.getElementById('assignAssetName').textContent = assetName;
    document.getElementById('assignPersonelId').value = '';
    document.getElementById('assignNotes').value = '';
    document.getElementById('assignAssetModal').classList.remove('hidden');
}

function closeAssignModal() {
    document.getElementById('assignAssetModal').classList.add('hidden');
    activeAssetId = null;
}

function submitAssignment() {
    if (!activeAssetId) return;
    const personelId = document.getElementById('assignPersonelId').value;
    if (!personelId) { toast('warning', 'Personel seçimi zorunludur.'); return; }

    axios.post(ASSET_URLS.assign(activeAssetId), {
        personel_id: personelId,
        condition:   document.getElementById('assignCondition').value,
        notes:       document.getElementById('assignNotes').value,
    }).then(res => {
        activeAssignmentId = res.data.assignment?.id;
        closeAssignModal();
        loadAssets();
        loadKPIs();
        if (activeAssignmentId) {
            Swal.fire({
                icon: 'success', title: 'Zimmetlendi!',
                text: res.data.message,
                showCancelButton: true,
                confirmButtonText: 'Zimmet Belgesini İndir',
                cancelButtonText: 'Tamam',
                confirmButtonColor: '#02E0FB',
            }).then(r => { if (r.isConfirmed) window.open(ASSET_URLS.zimmetPdf(activeAssignmentId), '_blank'); });
        } else {
            toast('success', res.data.message);
        }
    }).catch(err => {
        const msg = err.response?.data?.message || err.response?.data?.error || 'Zimmetleme başarısız.';
        toast('error', msg);
    });
}

function openReturnModal(assetId, assetName) {
    activeAssetId = assetId;
    document.getElementById('returnAssetName').textContent = assetName;
    document.getElementById('returnAssetModal').classList.remove('hidden');
}

function submitReturn() {
    if (!activeAssetId) return;
    axios.post(ASSET_URLS.return(activeAssetId), {
        condition: document.getElementById('returnCondition').value,
        notes:     document.getElementById('returnNotes').value,
    }).then(res => {
        document.getElementById('returnAssetModal').classList.add('hidden');
        toast('success', res.data.message);
        loadAssets();
        loadKPIs();
        activeAssetId = null;
    }).catch(err => {
        const msg = err.response?.data?.message || err.response?.data?.error || 'İade alınamadı.';
        toast('error', msg);
    });
}

function downloadZimmet() {
    if (!activeAssignmentId) { toast('warning', 'Önce zimmetleme işlemini tamamlayın.'); return; }
    window.open(ASSET_URLS.zimmetPdf(activeAssignmentId), '_blank');
}
</script>
@endpush
