{{-- Generated by Cursor prompt — MİYSOFT PTS — date: 2026-03-15 --}}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

{{-- SEO Meta --}}
<meta name="description" content="@yield('meta_description', 'MİYSOFT PTS — Personel Takip Sistemi')">
<meta name="keywords" content="@yield('meta_keywords', 'personel takip, IK yönetimi, SaaS')">
<meta name="author" content="MİYSOFT">

{{-- Open Graph --}}
<meta property="og:title" content="@yield('title', 'Admin Panel') — {{ config('app.name') }}">
<meta property="og:description" content="@yield('meta_description', 'MİYSOFT PTS Admin Paneli')">
<meta property="og:type" content="website">
<meta property="og:image" content="{{ asset('images/og-image.png') }}">
<meta name="twitter:card" content="summary_large_image">

{{-- Favicon --}}
<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
<link rel="shortcut icon" href="{{ asset('favicon.ico') }}">

{{-- Vite Assets (Tailwind + App JS) --}}
@vite(['resources/css/app.css', 'resources/js/app.js'])

{{-- Extra Styles (her sayfa override edebilir) --}}
@stack('styles')

{{-- SweetAlert2 CDN --}}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/sweetalert2@11/dist/sweetalert2.min.css">

{{-- DataTables CDN --}}
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/dataTables.tailwindcss.min.css">

{{-- Font: Inter --}}
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
