{{-- Generated by Cursor prompt — MİYSOFT PTS Sidebar (Full) — date: 2026-03-15 --}}
<aside id="sidebar" class="w-64 min-h-screen bg-gray-900 text-gray-100 flex flex-col transition-all duration-300 shrink-0 lg:relative fixed top-16 left-0 z-40 transform -translate-x-full lg:translate-x-0" id="sidebarEl">

    {{-- Şirket Adı --}}
    <div class="px-4 py-3.5 border-b border-gray-700/50">
        <p class="text-[11px] text-gray-500 uppercase tracking-wider font-semibold">{{ auth()->user()?->company?->name ?? 'Yönetim Paneli' }}</p>
    </div>

    {{-- Navigation --}}
    <nav class="flex-1 overflow-y-auto py-3 px-2 space-y-0.5">

        @php
        $currentRoute = request()->route()?->getName() ?? '';
        function isActive(string $prefix): bool {
            return str_starts_with(request()->route()?->getName() ?? '', $prefix);
        }
        @endphp

        {{-- Dashboard --}}
        @can('dashboard.view')
        <a href="{{ route('admin.dashboard') }}" class="nav-item flex items-center gap-3 px-3 py-2.5 rounded-xl text-sm font-medium transition-all {{ isActive('admin.dashboard') ? 'bg-[#02E0FB] text-gray-900 shadow-lg shadow-cyan-500/30' : 'text-gray-400 hover:bg-gray-800 hover:text-white' }}">
            <svg class="w-4.5 h-4.5 shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 5a1 1 0 011-1h14a1 1 0 011 1v2a1 1 0 01-1 1H5a1 1 0 01-1-1V5zM4 13a1 1 0 011-1h6a1 1 0 011 1v6a1 1 0 01-1 1H5a1 1 0 01-1-1v-6zM16 13a1 1 0 011-1h2a1 1 0 011 1v6a1 1 0 01-1 1h-2a1 1 0 01-1-1v-6z"/></svg>
            Genel Bakış
        </a>
        @endcan

        {{-- ─── İNSAN KAYNAKLARI ─── --}}
        <div class="pt-3 pb-1 px-3">
            <p class="text-[10px] font-bold text-gray-600 uppercase tracking-widest">İnsan Kaynakları</p>
        </div>

        @can('personel.view')
        @include('partials._sidebar_item', ['route' => 'admin.personel.index', 'label' => 'Personel Yönetimi', 'icon' => 'M17 20h5v-2a3 3 0 00-5.356-1.857M17 20H7m10 0v-2c0-.656-.126-1.283-.356-1.857M7 20H2v-2a3 3 0 015.356-1.857M7 20v-2c0-.656.126-1.283.356-1.857m0 0a5.002 5.002 0 019.288 0M15 7a3 3 0 11-6 0 3 3 0 016 0z'])
        @endcan

        @can('leave.view')
        @include('partials._sidebar_item', ['route' => 'admin.leave.index', 'label' => 'İzin Yönetimi', 'icon' => 'M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z'])
        @endcan

        @can('attendance.view')
        @include('partials._sidebar_item', ['route' => 'admin.attendance.index', 'label' => 'Puantaj', 'icon' => 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z'])
        @endcan

        @can('shift.view')
        @include('partials._sidebar_item', ['route' => 'admin.shifts.index', 'label' => 'Vardiya Yönetimi', 'icon' => 'M9 5H7a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2V7a2 2 0 00-2-2h-2M9 5a2 2 0 002 2h2a2 2 0 002-2M9 5a2 2 0 012-2h2a2 2 0 012 2'])
        @endcan

        @can('personel.manage')
        @include('partials._sidebar_item', ['route' => 'admin.processes.index', 'label' => 'Süreç Yönetimi', 'icon' => 'M9 17V7m0 10a2 2 0 01-2 2H5a2 2 0 01-2-2V7a2 2 0 012-2h2a2 2 0 012 2m0 10a2 2 0 002 2h2a2 2 0 002-2M9 7a2 2 0 012-2h2a2 2 0 012 2m0 10V7m0 10a2 2 0 002 2h2a2 2 0 002-2V7a2 2 0 00-2-2h-2a2 2 0 00-2 2'])
        @endcan

        {{-- ─── ŞİRKET YÖNETİMİ ─── --}}
        <div class="pt-3 pb-1 px-3">
            <p class="text-[10px] font-bold text-gray-600 uppercase tracking-widest">Şirket</p>
        </div>

        @can('department.view')
        @include('partials._sidebar_item', ['route' => 'admin.companies.index', 'label' => 'Şirket Yapısı', 'icon' => 'M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4'])
        @endcan

        @can('holiday.view')
        @include('partials._sidebar_item', ['route' => 'admin.holidays.index', 'label' => 'Tatil Yönetimi', 'icon' => 'M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z'])
        @endcan

        {{-- ─── VARLIKLAR ─── --}}
        <div class="pt-3 pb-1 px-3">
            <p class="text-[10px] font-bold text-gray-600 uppercase tracking-widest">Varlıklar & Finans</p>
        </div>

        @can('asset.view')
        @include('partials._sidebar_item', ['route' => 'admin.assets.index', 'label' => 'Envanter & Zimmet', 'icon' => 'M20 7l-8-4-8 4m16 0l-8 4m8-4v10l-8 4m0-10L4 7m8 4v10M4 7v10l8 4'])
        @endcan

        @can('advance.view')
        @include('partials._sidebar_item', ['route' => 'admin.advance.index', 'label' => 'Avans Yönetimi', 'icon' => 'M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z'])
        @endcan

        @can('expense.view')
        @include('partials._sidebar_item', ['route' => 'admin.expense.index', 'label' => 'Masraf Yönetimi', 'icon' => 'M9 14l6-6m-5.5.5h.01m4.99 5h.01M19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16l3.5-2 3.5 2 3.5-2 3.5 2zM10 8.5a.5.5 0 11-1 0 .5.5 0 011 0zm5 5a.5.5 0 11-1 0 .5.5 0 011 0z'])
        @endcan

        @can('travel.view')
        @include('partials._sidebar_item', ['route' => 'admin.travel.index', 'label' => 'Seyahat', 'icon' => 'M3.055 11H5a2 2 0 012 2v1a2 2 0 002 2 2 2 0 012 2v2.945M8 3.935V5.5A2.5 2.5 0 0010.5 8h.5a2 2 0 012 2 2 2 0 104 0 2 2 0 012-2h1.064M15 20.488V18a2 2 0 012-2h3.064M21 12a9 9 0 11-18 0 9 9 0 0118 0z'])
        @endcan

        @can('vehicle.view')
        @include('partials._sidebar_item', ['route' => 'admin.vehicles.index', 'label' => 'Araç Yönetimi', 'icon' => 'M13 10V3L4 14h7v7l9-11h-7z'])
        @endcan

        {{-- ─── ETKİLEŞİM ─── --}}
        <div class="pt-3 pb-1 px-3">
            <p class="text-[10px] font-bold text-gray-600 uppercase tracking-widest">Etkileşim</p>
        </div>

        @include('partials._sidebar_item', ['route' => 'admin.interactions.index', 'label' => 'Duyurular & Anketler', 'icon' => 'M15 17h5l-1.405-1.405A2.032 2.032 0 0118 14.158V11a6.002 6.002 0 00-4-5.659V5a2 2 0 10-4 0v.341C7.67 6.165 6 8.388 6 11v3.159c0 .538-.214 1.055-.595 1.436L4 17h5m6 0v1a3 3 0 11-6 0v-1m6 0H9'])

        @can('visitor.view')
        @include('partials._sidebar_item', ['route' => 'admin.visitors.index', 'label' => 'Ziyaretçi Yönetimi', 'icon' => 'M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z'])
        @endcan

        {{-- ─── ANALİTİK ─── --}}
        <div class="pt-3 pb-1 px-3">
            <p class="text-[10px] font-bold text-gray-600 uppercase tracking-widest">Analitik</p>
        </div>

        @can('report.view')
        @include('partials._sidebar_item', ['route' => 'admin.reports.index', 'label' => 'Raporlar', 'icon' => 'M9 17v-2m3 2v-4m3 4v-6m2 10H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z'])
        @endcan

        {{-- ─── SİTE YÖNETİMİ ─── --}}
        @can('settings.manage')
        <div class="pt-3 pb-1 px-3">
            <p class="text-[10px] font-bold text-gray-600 uppercase tracking-widest">Site & İçerik</p>
        </div>

        @include('partials._sidebar_item', ['route' => 'admin.cms.index', 'label' => 'Site İçerik Yönetimi', 'icon' => 'M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z'])
        @endcan

        {{-- ─── SaaS ─── --}}
        @can('subscription.view')
        <div class="pt-3 pb-1 px-3">
            <p class="text-[10px] font-bold text-gray-600 uppercase tracking-widest">SaaS</p>
        </div>

        @include('partials._sidebar_item', ['route' => 'admin.subscriptions.index', 'label' => 'Abonelik', 'icon' => 'M3 10h18M7 15h1m4 0h1m-7 4h12a3 3 0 003-3V8a3 3 0 00-3-3H6a3 3 0 00-3 3v8a3 3 0 003 3z'])
        @endcan

        {{-- ─── SYSTEM ─── --}}
        <div class="border-t border-gray-700/50 mt-3 pt-3"></div>

        @can('settings.view')
        @include('partials._sidebar_item', ['route' => 'admin.settings.index', 'label' => 'Sistem Ayarları', 'icon' => 'M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.065 2.572c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.572 1.065c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.065-2.572c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z M15 12a3 3 0 11-6 0 3 3 0 016 0z'])
        @endcan

        @can('role.view')
        @include('partials._sidebar_item', ['route' => 'admin.roles.index', 'label' => 'Rol & Yetki', 'icon' => 'M9 12l2 2 4-4m5.618-4.016A11.955 11.955 0 0112 2.944a11.955 11.955 0 01-8.618 3.04A12.02 12.02 0 003 9c0 5.591 3.824 10.29 9 11.622 5.176-1.332 9-6.03 9-11.622 0-1.042-.133-2.052-.382-3.016z'])
        @endcan

    </nav>

    {{-- Sidebar Footer --}}
    <div class="px-4 py-3 border-t border-gray-700/50">
        <div class="flex items-center gap-2">
            <div class="w-2 h-2 rounded-full bg-green-400 animate-pulse"></div>
            <p class="text-[11px] text-gray-500">v{{ config('app.version', '1.0.0') }} • {{ now()->format('Y') }} MİYSOFT</p>
        </div>
    </div>
</aside>
