<?php
// Generated by Cursor prompt — module: Puantaj (TimeRecordController) — date: 2026-03-15

namespace App\Modules\Puantaj\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Puantaj\Models\TimeRecord;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class TimeRecordController extends Controller
{
    public function indexView()
    {
        $this->authorize('attendance.view');
        $companyId = auth()->user()->company_id;
        $personels = \App\Modules\Personel\Models\Personel::forCompany($companyId)->active()
            ->select('id', 'first_name', 'last_name')->get();
        return view('admin.attendance.index', compact('personels'));
    }

    /** Günlük puantaj özet listesi — Ajax DataTable */
    public function index(Request $request): JsonResponse
    {
        $this->authorize('attendance.view');
        $companyId = auth()->user()->company_id;

        $date     = $request->get('date', today()->toDateString());
        $dateFrom = $request->get('date_from', $date);
        $dateTo   = $request->get('date_to', $date);

        // Personel bazlı günlük özet
        $records = TimeRecord::with('personel')
            ->forCompany($companyId)
            ->forDateRange($dateFrom, $dateTo)
            ->when($request->filled('personel_id'), fn ($q) => $q->where('personel_id', $request->personel_id))
            ->when($request->filled('type'), fn ($q) => $q->where('type', $request->type))
            ->orderByDesc('recorded_at')
            ->paginate($request->get('per_page', 30));

        return response()->json([
            'data'  => $records->map(fn ($r) => [
                'id'            => $r->id,
                'personel_id'   => $r->personel_id,
                'personel_name' => $r->personel?->first_name . ' ' . $r->personel?->last_name,
                'type'          => $r->type,
                'type_label'    => $r->type_label,
                'recorded_at'   => $r->recorded_at?->format('d.m.Y H:i:s'),
                'source'        => $r->source,
                'source_color'  => $r->source_color,
                'note'          => $r->note,
                'is_manual'     => $r->source === 'manual',
            ]),
            'total' => $records->total(),
            'pages' => $records->lastPage(),
        ]);
    }

    /** Günlük özet — her personel için hesaplanmış giriş/çıkış/gecikme/mesai */
    public function dailySummary(Request $request): JsonResponse
    {
        $this->authorize('attendance.view');
        $companyId = auth()->user()->company_id;
        $date      = $request->get('date', today()->toDateString());

        // Şirket çalışma ayarlarından planlanan saati al
        $company       = DB::table('companies')->where('id', $companyId)->first();
        $settings      = json_decode($company?->settings ?? '{}', true);
        $shiftStart    = $settings['work_start'] ?? '09:00';
        $plannedMinutes= 480; // VARSAYIM: 8 saat

        $allRecords = TimeRecord::with('personel')
            ->forCompany($companyId)
            ->forDate($date)
            ->get()
            ->groupBy('personel_id');

        $summaries = $allRecords->map(function ($records, $personelId) use ($shiftStart, $plannedMinutes) {
            $personel = $records->first()?->personel;
            $calc     = TimeRecord::calculateOvertimeAndLate($records, $shiftStart, $plannedMinutes);

            $firstIn  = $records->where('type', 'in')->sortBy('recorded_at')->first();
            $lastOut  = $records->where('type', 'out')->sortByDesc('recorded_at')->first();

            return [
                'personel_id'      => $personelId,
                'personel_name'    => $personel?->first_name . ' ' . $personel?->last_name,
                'check_in'         => $firstIn?->recorded_at?->format('H:i'),
                'check_out'        => $lastOut?->recorded_at?->format('H:i'),
                'net_work_hours'   => round($calc['net_work_minutes'] / 60, 2),
                'late_minutes'     => $calc['late_minutes'],
                'overtime_minutes' => $calc['overtime_minutes'],
                'is_pair_complete' => $calc['is_pair_complete'],
                'status'           => $this->resolveStatus($calc),
            ];
        })->values();

        return response()->json(['data' => $summaries, 'date' => $date]);
    }

    private function resolveStatus(array $calc): string
    {
        if (!$calc['is_pair_complete']) return 'incomplete';
        if ($calc['late_minutes'] > 15) return 'late';
        if ($calc['overtime_minutes'] > 0) return 'overtime';
        if ($calc['net_work_minutes'] > 0) return 'present';
        return 'absent';
    }

    /** Manuel giriş/çıkış kaydı */
    public function storeRecord(Request $request): JsonResponse
    {
        $this->authorize('attendance.create');

        $data = $request->validate([
            'personel_id' => 'required|exists:personels,id',
            'type'        => 'required|in:in,out,break_start,break_end',
            'recorded_at' => 'required|date',
            'note'        => 'nullable|string|max:500',
        ]);

        $data['company_id'] = auth()->user()->company_id;
        $data['source']     = 'manual';
        $data['created_by'] = auth()->id();

        $record = TimeRecord::create($data);

        DB::table('audit_logs')->insert([
            'user_id'    => auth()->id(),
            'company_id' => $data['company_id'],
            'action'     => 'time_record.manual_entry',
            'model_type' => TimeRecord::class,
            'model_id'   => $record->id,
            'changes'    => json_encode($data),
            'ip'         => request()->ip(),
            'created_at' => now(),
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Kayıt manuel olarak eklendi.',
            'data'    => array_merge($record->toArray(), [
                'type_label'   => $record->type_label,
                'source_color' => $record->source_color,
            ]),
        ], 201);
    }

    /** Kaydı düzelt (sadece manual kayıtlar) */
    public function correct(Request $request, TimeRecord $timeRecord): JsonResponse
    {
        $this->authorize('attendance.correct');

        $data = $request->validate([
            'recorded_at' => 'required|date',
            'note'        => 'nullable|string|max:500',
        ]);

        $oldTime = $timeRecord->recorded_at;
        $timeRecord->update($data);

        DB::table('audit_logs')->insert([
            'user_id'    => auth()->id(),
            'company_id' => $timeRecord->company_id,
            'action'     => 'time_record.corrected',
            'model_type' => TimeRecord::class,
            'model_id'   => $timeRecord->id,
            'changes'    => json_encode(['old' => $oldTime, 'new' => $data['recorded_at']]),
            'ip'         => request()->ip(),
            'created_at' => now(),
        ]);

        return response()->json(['success' => true, 'message' => 'Kayıt düzeltildi.', 'data' => $timeRecord->fresh()]);
    }

    /** Kaydı sil */
    public function destroy(TimeRecord $timeRecord): JsonResponse
    {
        $this->authorize('attendance.correct');
        $timeRecord->delete();
        return response()->json(['success' => true, 'message' => 'Kayıt silindi.']);
    }

    /** Excel export — arka plan job */
    public function export(Request $request): JsonResponse
    {
        $this->authorize('attendance.export');
        \App\Jobs\ExportPersonelExcelJob::dispatch(
            auth()->user()->company_id,
            auth()->id(),
            array_merge($request->only(['date_from', 'date_to', 'personel_id']), ['module' => 'attendance'])
        );
        return response()->json(['success' => true, 'message' => 'Dışa aktarma başlatıldı. Tamamlandığında bildirim alacaksınız.']);
    }
}
