{{-- Generated by Cursor prompt — module: İzin — date: 2026-03-15 --}}
{{-- Hem yeni talep hem düzenleme için kullanılır --}}
<form id="leaveRequestForm" class="space-y-4" novalidate>
    @csrf

    {{-- Personel --}}
    <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">
            Personel <span class="text-red-500">*</span>
        </label>
        <select name="personel_id" id="leavePersonelSelect" required
            class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
            onchange="loadPersonelBalance()">
            <option value="">— Personel seçin —</option>
            @foreach($personels ?? [] as $p)
                <option value="{{ $p->id }}" {{ isset($leaveRequest) && $leaveRequest->personel_id == $p->id ? 'selected' : '' }}>
                    {{ $p->first_name }} {{ $p->last_name }}
                </option>
            @endforeach
        </select>
    </div>

    {{-- İzin Türü --}}
    <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">
            İzin Türü <span class="text-red-500">*</span>
        </label>
        <select name="leave_type_id" id="leaveTypeSelect" required
            class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
            onchange="loadPersonelBalance()">
            <option value="">— İzin türü seçin —</option>
            @foreach($leaveTypes ?? [] as $lt)
                <option value="{{ $lt->id }}" data-paid="{{ $lt->paid ? '1' : '0' }}" data-approval="{{ $lt->requires_approval ? '1' : '0' }}"
                    {{ isset($leaveRequest) && $leaveRequest->leave_type_id == $lt->id ? 'selected' : '' }}>
                    {{ $lt->name }}
                    @if($lt->paid) (Ücretli) @else (Ücretsiz) @endif
                    @if($lt->max_annual_days) — Max: {{ $lt->max_annual_days }} gün @endif
                </option>
            @endforeach
        </select>

        {{-- Bakiye bilgisi --}}
        <div id="balanceInfo" class="hidden mt-2 p-3 bg-[#02E0FB]/5 border border-[#02E0FB]/20 rounded-lg text-xs">
            <div class="flex items-center justify-between">
                <span class="text-gray-600">Mevcut Bakiye:</span>
                <span class="font-bold text-[#02E0FB]" id="balanceRemaining">—</span>
            </div>
            <div class="flex items-center justify-between mt-1">
                <span class="text-gray-600">Kullanılan:</span>
                <span class="text-gray-700" id="balanceUsed">—</span>
            </div>
        </div>

        {{-- Otomatik onay bildirimi --}}
        <div id="autoApproveNote" class="hidden mt-2 p-2 bg-green-50 border border-green-200 rounded-lg text-xs text-green-700">
            ✅ Bu izin türü otomatik onaylanır.
        </div>
    </div>

    {{-- Tarih Aralığı --}}
    <div class="grid grid-cols-2 gap-3">
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Başlangıç Tarihi <span class="text-red-500">*</span></label>
            <input type="date" name="start_date" id="leaveStartDate" required
                value="{{ isset($leaveRequest) ? $leaveRequest->start_date?->format('Y-m-d') : '' }}"
                min="{{ today()->toDateString() }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                onchange="calculateDays()">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Bitiş Tarihi <span class="text-red-500">*</span></label>
            <input type="date" name="end_date" id="leaveEndDate" required
                value="{{ isset($leaveRequest) ? $leaveRequest->end_date?->format('Y-m-d') : '' }}"
                min="{{ today()->toDateString() }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                onchange="calculateDays()">
        </div>
    </div>

    {{-- Gün Sayısı Hesaplama --}}
    <div id="dayCountBox" class="hidden p-3 bg-gray-50 border border-gray-200 rounded-lg">
        <div class="flex items-center justify-between text-sm">
            <span class="text-gray-600">Hesaplanan iş günü:</span>
            <span class="font-bold text-gray-900 text-lg" id="calculatedDays">—</span>
        </div>
        <div id="balanceWarning" class="hidden mt-2 p-2 bg-red-50 border border-red-200 rounded text-xs text-red-700">
            ⚠️ Bakiye yetersiz olabilir!
        </div>
    </div>

    {{-- Gerekçe --}}
    <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Açıklama / Gerekçe</label>
        <textarea name="reason" rows="3"
            class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
            placeholder="İzin talebinizin gerekçesini yazın...">{{ $leaveRequest->reason ?? '' }}</textarea>
    </div>

    {{-- Dosya Ekleme --}}
    <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Belge / Ek (isteğe bağlı)</label>
        <div class="flex items-center justify-center w-full border-2 border-dashed border-gray-200 rounded-lg p-4 cursor-pointer hover:border-[#02E0FB] hover:bg-[#02E0FB]/5 transition-colors"
            onclick="document.getElementById('leaveAttachment').click()">
            <div class="text-center">
                <svg class="w-8 h-8 text-gray-300 mx-auto mb-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/>
                </svg>
                <p class="text-xs text-gray-500">PDF, JPG, PNG — Max 5MB</p>
                <p class="text-xs text-[#02E0FB] font-medium mt-1" id="attachmentName">Dosya seçmek için tıklayın</p>
            </div>
        </div>
        <input type="file" id="leaveAttachment" name="attachment" accept=".pdf,.jpg,.jpeg,.png" class="hidden"
            onchange="document.getElementById('attachmentName').textContent = this.files[0]?.name || 'Dosya seçmek için tıklayın'">
    </div>
</form>

<script>
function loadPersonelBalance() {
    const personelId = document.getElementById('leavePersonelSelect').value;
    const typeId     = document.getElementById('leaveTypeSelect').value;
    const autoNote   = document.getElementById('autoApproveNote');
    const balanceBox = document.getElementById('balanceInfo');

    // Otomatik onay notu
    const typeOption = document.querySelector(`#leaveTypeSelect option[value="${typeId}"]`);
    if (typeOption?.dataset.approval === '0') {
        autoNote.classList.remove('hidden');
    } else {
        autoNote.classList.add('hidden');
    }

    if (!personelId || !typeId) {
        balanceBox.classList.add('hidden');
        return;
    }

    const year = new Date().getFullYear();
    axios.get(`/admin/leave/balances?personel_id=${personelId}&leave_type_id=${typeId}&year=${year}&per_page=1`)
        .then(res => {
            const balance = res.data.data?.[0];
            if (balance) {
                document.getElementById('balanceRemaining').textContent = `${balance.remaining_days} gün`;
                document.getElementById('balanceUsed').textContent = `${balance.used_days} gün`;
                balanceBox.classList.remove('hidden');
            } else {
                balanceBox.classList.add('hidden');
            }
        }).catch(() => balanceBox.classList.add('hidden'));
}

function calculateDays() {
    const start = document.getElementById('leaveStartDate').value;
    const end   = document.getElementById('leaveEndDate').value;

    if (!start || !end || new Date(start) > new Date(end)) {
        document.getElementById('dayCountBox').classList.add('hidden');
        return;
    }

    let count = 0;
    const s   = new Date(start);
    const e   = new Date(end);
    for (let d = new Date(s); d <= e; d.setDate(d.getDate() + 1)) {
        const day = d.getDay();
        if (day !== 0 && day !== 6) count++;
    }

    document.getElementById('calculatedDays').textContent = count + ' gün';
    document.getElementById('dayCountBox').classList.remove('hidden');

    // Bakiye uyarısı
    const remaining = parseFloat(document.getElementById('balanceRemaining')?.textContent) || Infinity;
    const warning   = document.getElementById('balanceWarning');
    if (count > remaining) {
        warning.classList.remove('hidden');
    } else {
        warning.classList.add('hidden');
    }
}
</script>
