{{-- Generated by Cursor prompt — module: İzin Yönetimi — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'İzin Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">İzin Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">İzin Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">İzin taleplerini görüntüleyin, onaylayın veya reddedin.</p>
    </div>
    <div class="flex items-center gap-2">
        <a href="{{ route('admin.leave.types.index') }}"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 10h16M4 14h16M4 18h7"/></svg>
            İzin Türleri
        </a>
        <a href="{{ route('admin.leave.balances') }}"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
            Bakiyeler
        </a>
        @can('leave.request')
        <button onclick="openCreateLeaveModal()"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
            Yeni Talep
        </button>
        @endcan
    </div>
@endsection

@section('content')

{{-- KPI Özet Kartları --}}
<div class="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-5">
    @foreach([
        ['id'=>'kpi-pending','label'=>'Bekleyen','icon'=>'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z','color'=>'yellow','status'=>'pending'],
        ['id'=>'kpi-approved','label'=>'Onaylanan (Bu Ay)','icon'=>'M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z','color'=>'green','status'=>'approved'],
        ['id'=>'kpi-rejected','label'=>'Reddedilen','icon'=>'M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z','color'=>'red','status'=>'rejected'],
        ['id'=>'kpi-cancelled','label'=>'İptal Edilen','icon'=>'M6 18L18 6M6 6l12 12','color'=>'gray','status'=>'cancelled'],
    ] as $card)
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-4 flex items-center gap-3">
        <div class="w-10 h-10 rounded-xl bg-{{ $card['color'] }}-50 flex items-center justify-center shrink-0">
            <svg class="w-5 h-5 text-{{ $card['color'] }}-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="{{ $card['icon'] }}"/>
            </svg>
        </div>
        <div>
            <p class="text-xs text-gray-500">{{ $card['label'] }}</p>
            <p class="text-2xl font-bold text-gray-900" id="{{ $card['id'] }}">—</p>
        </div>
    </div>
    @endforeach
</div>

{{-- Filtreler --}}
<div class="bg-white rounded-xl border border-gray-100 p-4 mb-4 shadow-sm">
    <div class="grid grid-cols-2 md:grid-cols-5 gap-3">
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Personel</label>
            <select id="filterPersonel" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($personels as $p)
                    <option value="{{ $p->id }}">{{ $p->first_name }} {{ $p->last_name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">İzin Türü</label>
            <select id="filterLeaveType" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($leaveTypes as $lt)
                    <option value="{{ $lt->id }}">{{ $lt->name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Durum</label>
            <select id="filterStatus" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                <option value="pending">Bekleyen</option>
                <option value="approved">Onaylanan</option>
                <option value="rejected">Reddedilen</option>
                <option value="cancelled">İptal</option>
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Tarih Başlangıç</label>
            <input type="date" id="filterDateFrom" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div class="flex items-end">
            <button onclick="loadLeaveRequests()" class="w-full px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Filtrele</button>
        </div>
    </div>
</div>

{{-- Tablo --}}
<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Personel</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">İzin Türü</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Tarih Aralığı</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Gün</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Durum</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Onaylayan</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">İşlemler</th>
                </tr>
            </thead>
            <tbody id="leaveTableBody" class="divide-y divide-gray-50">
                <tr><td colspan="7" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
            </tbody>
        </table>
    </div>
    <div class="px-4 py-3 border-t border-gray-100 flex items-center justify-between">
        <div class="text-xs text-gray-500" id="leaveTableInfo">—</div>
        <div id="leavePagination" class="flex gap-1"></div>
    </div>
</div>

{{-- Onay/Ret Modal (inline, hızlı işlem için) --}}
<div id="approvalModal" class="hidden fixed inset-0 z-[110] flex items-center justify-center p-4">
    <div class="absolute inset-0 bg-black/50" onclick="closeApprovalModal()"></div>
    <div class="relative bg-white rounded-2xl shadow-2xl w-full max-w-md z-10 p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-4" id="approvalModalTitle">İzin Onayla</h3>
        <div id="approvalModalContent"></div>
        <div class="flex justify-end gap-3 mt-5">
            <button onclick="closeApprovalModal()" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button id="approvalModalBtn" class="px-4 py-2 text-sm text-white rounded-lg font-medium"></button>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
const LEAVE_URLS = {
    list:    '{{ route("admin.leave.requests.index") }}',
    create:  '{{ route("admin.leave.requests.create") }}',
    store:   '{{ route("admin.leave.requests.store") }}',
    edit:    id => `/admin/leave/requests/${id}/edit`,
    update:  id => `/admin/leave/requests/${id}`,
    destroy: id => `/admin/leave/requests/${id}`,
    approve: id => `/admin/leave/requests/${id}/approve`,
    reject:  id => `/admin/leave/requests/${id}/reject`,
    cancel:  id => `/admin/leave/requests/${id}/cancel`,
};

document.addEventListener('DOMContentLoaded', () => {
    loadLeaveRequests();
    loadKpiCounts();
});

function loadLeaveRequests(page = 1) {
    const params = {
        page,
        personel_id:    document.getElementById('filterPersonel').value,
        leave_type_id:  document.getElementById('filterLeaveType').value,
        status:         document.getElementById('filterStatus').value,
        date_from:      document.getElementById('filterDateFrom').value,
        per_page: 15,
    };
    axios.get(LEAVE_URLS.list, { params }).then(res => renderLeaveTable(res.data));
}

function loadKpiCounts() {
    ['pending','approved','rejected','cancelled'].forEach(s => {
        axios.get(LEAVE_URLS.list, { params: { status: s, per_page: 1 } }).then(res => {
            const el = document.getElementById(`kpi-${s}`);
            if (el) el.textContent = res.data.total;
        });
    });
}

const statusConfig = {
    pending:   { label: 'Bekliyor',     bg: 'bg-yellow-100', text: 'text-yellow-700' },
    approved:  { label: 'Onaylandı',    bg: 'bg-green-100',  text: 'text-green-700' },
    rejected:  { label: 'Reddedildi',   bg: 'bg-red-100',    text: 'text-red-700' },
    cancelled: { label: 'İptal',        bg: 'bg-gray-100',   text: 'text-gray-600' },
};

function renderLeaveTable(data) {
    const tbody = document.getElementById('leaveTableBody');
    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="7" class="px-4 py-8 text-center text-gray-400 text-sm">Kayıt bulunamadı</td></tr>`;
        return;
    }
    tbody.innerHTML = data.data.map(r => {
        const sc = statusConfig[r.status] || { label: r.status, bg: 'bg-gray-100', text: 'text-gray-600' };
        const isPending = r.status === 'pending';
        const startDate = new Date(r.start_date).toLocaleDateString('tr-TR');
        const endDate   = new Date(r.end_date).toLocaleDateString('tr-TR');

        return `
        <tr class="hover:bg-gray-50 transition-colors ${isPending ? 'bg-yellow-50/30' : ''}">
            <td class="px-4 py-3">
                <div class="flex items-center gap-2">
                    <div class="w-8 h-8 rounded-full bg-[#02E0FB]/15 text-[#02E0FB] font-bold text-xs flex items-center justify-center">
                        ${(r.personel?.first_name?.[0] || '') + (r.personel?.last_name?.[0] || '')}
                    </div>
                    <span class="font-medium text-gray-800 text-sm">${r.personel?.first_name || ''} ${r.personel?.last_name || ''}</span>
                </div>
            </td>
            <td class="px-4 py-3 text-gray-600 text-sm">${r.leave_type?.name || '—'}</td>
            <td class="px-4 py-3 text-gray-600 text-sm">
                <span>${startDate}</span>
                <span class="text-gray-300 mx-1">→</span>
                <span>${endDate}</span>
            </td>
            <td class="px-4 py-3 text-center">
                <span class="inline-flex items-center justify-center w-8 h-8 rounded-full bg-gray-100 text-gray-800 text-xs font-bold">${r.total_days}</span>
            </td>
            <td class="px-4 py-3">
                <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${sc.bg} ${sc.text}">${sc.label}</span>
            </td>
            <td class="px-4 py-3 text-gray-500 text-sm">${r.approver ? `${r.approver.name}` : '—'}</td>
            <td class="px-4 py-3">
                <div class="flex items-center justify-end gap-1">
                    ${isPending ? `
                    <button onclick="openApproveModal(${r.id})" class="p-1.5 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded-lg" title="Onayla">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
                    </button>
                    <button onclick="openRejectModal(${r.id})" class="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg" title="Reddet">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>
                    ` : ''}
                    ${r.status !== 'cancelled' ? `
                    <button onclick="cancelLeave(${r.id})" class="p-1.5 text-gray-400 hover:text-orange-500 hover:bg-orange-50 rounded-lg" title="İptal Et">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M18.364 18.364A9 9 0 005.636 5.636m12.728 12.728A9 9 0 015.636 5.636m12.728 12.728L5.636 5.636"/></svg>
                    </button>
                    ` : ''}
                </div>
            </td>
        </tr>`;
    }).join('');

    document.getElementById('leaveTableInfo').textContent = `${data.total} kayıttan ${data.data.length} gösteriliyor`;
}

// ─── Onay / Ret Modalleri ─────────────────────────────────────────────────────

function openApproveModal(id) {
    document.getElementById('approvalModalTitle').textContent = '✅ İzni Onayla';
    document.getElementById('approvalModalContent').innerHTML = `
        <p class="text-sm text-gray-600 mb-3">Bu izin talebini onaylamak istiyor musunuz?</p>
        <label class="block text-sm font-medium text-gray-700 mb-1">Not (isteğe bağlı)</label>
        <textarea id="approvalNote" rows="2" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]" placeholder="Onay notu..."></textarea>
    `;
    const btn = document.getElementById('approvalModalBtn');
    btn.textContent = 'Onayla';
    btn.className = 'px-4 py-2 text-sm text-white bg-green-600 hover:bg-green-700 rounded-lg font-medium';
    btn.onclick = () => submitApproval(id, 'approve');
    document.getElementById('approvalModal').classList.remove('hidden');
}

function openRejectModal(id) {
    document.getElementById('approvalModalTitle').textContent = '❌ İzni Reddet';
    document.getElementById('approvalModalContent').innerHTML = `
        <p class="text-sm text-gray-600 mb-3">Red gerekçesini belirtiniz.</p>
        <label class="block text-sm font-medium text-gray-700 mb-1">Ret Gerekçesi <span class="text-red-500">*</span></label>
        <textarea id="approvalNote" rows="3" required class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-red-400" placeholder="Reddetme gerekçesini yazınız..."></textarea>
    `;
    const btn = document.getElementById('approvalModalBtn');
    btn.textContent = 'Reddet';
    btn.className = 'px-4 py-2 text-sm text-white bg-red-600 hover:bg-red-700 rounded-lg font-medium';
    btn.onclick = () => submitApproval(id, 'reject');
    document.getElementById('approvalModal').classList.remove('hidden');
}

function submitApproval(id, action) {
    const note = document.getElementById('approvalNote')?.value;
    if (action === 'reject' && !note?.trim()) {
        toast('warning', 'Ret gerekçesi zorunludur.');
        return;
    }

    const url     = action === 'approve' ? LEAVE_URLS.approve(id) : LEAVE_URLS.reject(id);
    const payload = action === 'approve' ? { note } : { reason: note };

    axios.post(url, payload).then(res => {
        closeApprovalModal();
        toast(res.data.success ? 'success' : 'error', res.data.message);
        loadLeaveRequests();
        loadKpiCounts();
    });
}

function cancelLeave(id) {
    Swal.fire({
        title: 'İzni İptal Et',
        input: 'textarea',
        inputPlaceholder: 'İptal gerekçesi (isteğe bağlı)...',
        showCancelButton: true,
        confirmButtonColor: '#FA6001',
        cancelButtonColor: '#6B7280',
        confirmButtonText: 'İptal Et',
        cancelButtonText: 'Vazgeç',
    }).then(result => {
        if (result.isConfirmed) {
            axios.post(LEAVE_URLS.cancel(id), { reason: result.value }).then(res => {
                toast(res.data.success ? 'success' : 'error', res.data.message);
                loadLeaveRequests();
                loadKpiCounts();
            });
        }
    });
}

function closeApprovalModal() {
    document.getElementById('approvalModal').classList.add('hidden');
}

// ─── Create / Edit ────────────────────────────────────────────────────────────

function openCreateLeaveModal() {
    axios.get(LEAVE_URLS.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni İzin Talebi';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitLeaveForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Talep Oluştur</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function submitLeaveForm(url = LEAVE_URLS.store, method = 'POST') {
    const form = document.getElementById('leaveRequestForm');
    const data = Object.fromEntries(new FormData(form).entries());
    axios({ method, url, data }).then(res => {
        document.getElementById('globalModal').classList.add('hidden');
        toast(res.data.auto_approved ? 'success' : 'info', res.data.message);
        loadLeaveRequests();
        loadKpiCounts();
    });
}
</script>
@endpush
