<?php
// Generated by Cursor prompt — module: Sirket (Company) — date: 2026-03-15

namespace App\Modules\Sirket\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Company extends Model
{
    use SoftDeletes;

    protected $table = 'companies';

    protected $fillable = [
        'name',
        'domain',
        'tax_number',
        'tax_office',
        'phone',
        'email',
        'address',
        'city',
        'country',
        'timezone',
        'locale',
        'logo_path',
        'status',
        'trial_ends_at',
        'settings',
        'created_by',
    ];

    protected $casts = [
        'trial_ends_at' => 'date',
        'settings'      => 'array',
    ];

    public function departments(): HasMany
    {
        return $this->hasMany(Department::class);
    }

    public function rootDepartments(): HasMany
    {
        return $this->hasMany(Department::class)->whereNull('parent_department_id');
    }

    public function positions(): HasMany
    {
        return $this->hasMany(Position::class);
    }

    public function teams(): HasMany
    {
        return $this->hasMany(Team::class);
    }

    public function personels(): HasMany
    {
        return $this->hasMany(\App\Modules\Personel\Models\Personel::class);
    }

    public function activePersonels(): HasMany
    {
        return $this->hasMany(\App\Modules\Personel\Models\Personel::class)->where('is_active', true);
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'created_by');
    }

    public function isOnTrial(): bool
    {
        return $this->status === 'trial' && $this->trial_ends_at?->isFuture();
    }

    public function isActive(): bool
    {
        return $this->status === 'active';
    }

    public function getWorkingDaysAttribute(): array
    {
        return $this->settings['working_days'] ?? [1, 2, 3, 4, 5];
    }

    public function getWorkStartAttribute(): string
    {
        return $this->settings['work_start'] ?? '09:00';
    }

    public function getWorkEndAttribute(): string
    {
        return $this->settings['work_end'] ?? '18:00';
    }
}
