<?php
// Generated by Cursor prompt — module: Sirket (Team) — date: 2026-03-15

namespace App\Modules\Sirket\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;

class Team extends Model
{
    protected $table = 'teams';

    protected $fillable = [
        'department_id',
        'name',
        'lead_id',
        'description',
    ];

    public function department(): BelongsTo
    {
        return $this->belongsTo(Department::class);
    }

    public function lead(): BelongsTo
    {
        return $this->belongsTo(\App\Modules\Personel\Models\Personel::class, 'lead_id');
    }

    public function scopeForCompany($query, int $companyId)
    {
        return $query->whereHas('department', fn ($q) => $q->where('company_id', $companyId));
    }
}
