<?php
// Generated by Cursor prompt — module: Puantaj (TimeRecord) — date: 2026-03-15

namespace App\Modules\Puantaj\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Carbon\Carbon;
use Illuminate\Support\Collection;

class TimeRecord extends Model
{
    protected $table = 'time_records';

    protected $fillable = [
        'company_id', 'personel_id', 'type', 'recorded_at',
        'source', 'geo', 'note', 'created_by',
    ];

    protected $casts = [
        'recorded_at' => 'datetime',
        'geo'         => 'array',
    ];

    const TYPE_IN           = 'in';
    const TYPE_OUT          = 'out';
    const TYPE_BREAK_START  = 'break_start';
    const TYPE_BREAK_END    = 'break_end';

    const SOURCE_WEB        = 'web';
    const SOURCE_MOBILE     = 'mobile';
    const SOURCE_BIOMETRIC  = 'biometric';
    const SOURCE_MANUAL     = 'manual';

    // ─── Relations ───────────────────────────────────────────────────────────

    public function personel(): BelongsTo
    {
        return $this->belongsTo(\App\Modules\Personel\Models\Personel::class);
    }

    public function company(): BelongsTo
    {
        return $this->belongsTo(\App\Modules\Sirket\Models\Company::class);
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'created_by');
    }

    // ─── Hesaplama Mantığı ───────────────────────────────────────────────────

    /**
     * Bir günün giriş/çıkış kayıtlarından net çalışma süresini hesapla (dakika).
     * @param Collection $dayRecords — bir personelin tek gündeki tüm kayıtları (sıralı)
     */
    public static function calculateWorkMinutes(Collection $dayRecords): array
    {
        $totalWork   = 0;
        $totalBreak  = 0;
        $lastIn      = null;
        $lastBreak   = null;

        foreach ($dayRecords->sortBy('recorded_at') as $record) {
            switch ($record->type) {
                case self::TYPE_IN:
                    $lastIn = $record->recorded_at;
                    break;

                case self::TYPE_OUT:
                    if ($lastIn) {
                        $totalWork += $lastIn->diffInMinutes($record->recorded_at);
                        $lastIn = null;
                    }
                    break;

                case self::TYPE_BREAK_START:
                    $lastBreak = $record->recorded_at;
                    break;

                case self::TYPE_BREAK_END:
                    if ($lastBreak) {
                        $totalBreak += $lastBreak->diffInMinutes($record->recorded_at);
                        $lastBreak = null;
                    }
                    break;
            }
        }

        $netWork = max(0, $totalWork - $totalBreak);

        return [
            'total_work_minutes'  => $totalWork,
            'total_break_minutes' => $totalBreak,
            'net_work_minutes'    => $netWork,
            'total_work_hours'    => round($netWork / 60, 2),
            'is_pair_complete'    => $lastIn === null,  // eşsiz giriş var mı?
        ];
    }

    /**
     * Planlanan mesai saatine göre gecikme/fazla mesai hesapla.
     * @param int $plannedMinutes — şirket ayarlarından planlanan süre
     */
    public static function calculateOvertimeAndLate(Collection $dayRecords, string $shiftStart, int $plannedMinutes): array
    {
        $firstIn = $dayRecords->where('type', self::TYPE_IN)->sortBy('recorded_at')->first();
        $work    = self::calculateWorkMinutes($dayRecords);

        $lateMinutes = 0;
        if ($firstIn) {
            $plannedStart = Carbon::parse($firstIn->recorded_at->format('Y-m-d') . ' ' . $shiftStart);
            $actualStart  = $firstIn->recorded_at;
            if ($actualStart->gt($plannedStart)) {
                $lateMinutes = $plannedStart->diffInMinutes($actualStart);
            }
        }

        $overtimeMinutes = max(0, $work['net_work_minutes'] - $plannedMinutes);

        return [
            'late_minutes'     => $lateMinutes,
            'overtime_minutes' => $overtimeMinutes,
            'net_work_minutes' => $work['net_work_minutes'],
            'is_pair_complete' => $work['is_pair_complete'],
        ];
    }

    /** Kaynak badge rengi */
    public function getSourceColorAttribute(): string
    {
        return match ($this->source) {
            'web'       => 'blue',
            'mobile'    => 'purple',
            'biometric' => 'green',
            'manual'    => 'orange',
            default     => 'gray',
        };
    }

    /** Tür Türkçe label */
    public function getTypeLabelAttribute(): string
    {
        return match ($this->type) {
            'in'          => 'Giriş',
            'out'         => 'Çıkış',
            'break_start' => 'Mola Başlangıç',
            'break_end'   => 'Mola Bitiş',
            default       => $this->type,
        };
    }

    // ─── Scopes ──────────────────────────────────────────────────────────────

    public function scopeForCompany($query, int $companyId)
    {
        return $query->where('company_id', $companyId);
    }

    public function scopeForPersonel($query, int $personelId)
    {
        return $query->where('personel_id', $personelId);
    }

    public function scopeForDate($query, string $date)
    {
        return $query->whereDate('recorded_at', $date);
    }

    public function scopeForDateRange($query, string $from, string $to)
    {
        return $query->whereBetween(\DB::raw('DATE(recorded_at)'), [$from, $to]);
    }
}
