{{-- Generated by Cursor prompt — module: Vardiya _form — date: 2026-03-15 --}}
<form id="shiftForm" class="space-y-4" novalidate>
    @csrf
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="md:col-span-2">
            <label class="block text-sm font-medium text-gray-700 mb-1">Vardiya Adı <span class="text-red-500">*</span></label>
            <input type="text" name="name" value="{{ $shift->name ?? '' }}" required
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="Örn: Sabah Vardiyası">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Başlangıç Saati <span class="text-red-500">*</span></label>
            <input type="time" name="start_time" value="{{ $shift->start_time ?? '09:00' }}" required
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Bitiş Saati <span class="text-red-500">*</span></label>
            <input type="time" name="end_time" value="{{ $shift->end_time ?? '18:00' }}" required
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Renk</label>
            <div class="flex items-center gap-2">
                <input type="color" name="color" value="{{ $shift->color ?? '#02E0FB' }}"
                    class="w-10 h-10 border border-gray-200 rounded-lg cursor-pointer p-0.5">
                <span class="text-xs text-gray-400">Takvimde gösterim rengi</span>
            </div>
        </div>
        <div class="flex flex-col justify-end gap-3">
            <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                <div>
                    <p class="text-sm font-medium text-gray-700">Gece Vardiyası</p>
                    <p class="text-xs text-gray-400">Bitiş saati ertesi güne geçer.</p>
                </div>
                <label class="relative inline-flex items-center cursor-pointer">
                    <input type="checkbox" name="is_night_shift" class="sr-only peer" {{ isset($shift) && $shift->is_night_shift ? 'checked' : '' }}>
                    <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-checked:bg-indigo-500 transition-colors after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
                </label>
            </div>
            <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                <p class="text-sm font-medium text-gray-700">Aktif</p>
                <label class="relative inline-flex items-center cursor-pointer">
                    <input type="checkbox" name="is_active" class="sr-only peer" {{ !isset($shift) || $shift->is_active ? 'checked' : '' }}>
                    <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-checked:bg-green-500 transition-colors after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
                </label>
            </div>
        </div>
    </div>

    {{-- Mola Tanımları --}}
    <div>
        <div class="flex items-center justify-between mb-2">
            <label class="block text-sm font-medium text-gray-700">Mola Süreleri</label>
            <button type="button" onclick="addBreak()" class="text-xs text-[#02E0FB] hover:underline">+ Mola Ekle</button>
        </div>
        <div id="breaksList" class="space-y-2">
            @foreach($shift->breaks ?? [] as $i => $brk)
            <div class="flex items-center gap-2 break-item">
                <input type="text" name="breaks[{{ $i }}][label]" value="{{ $brk['label'] ?? '' }}" placeholder="Mola adı"
                    class="flex-1 px-2 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <input type="number" name="breaks[{{ $i }}][duration_minutes]" value="{{ $brk['duration_minutes'] ?? 30 }}" min="1" max="120" placeholder="Dk"
                    class="w-20 px-2 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <span class="text-xs text-gray-400">dk</span>
                <button type="button" onclick="this.closest('.break-item').remove()" class="text-red-400 hover:text-red-600">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
            </div>
            @endforeach
        </div>
    </div>
</form>
<script>
let breakCount = {{ isset($shift) ? count($shift->breaks ?? []) : 0 }};
function addBreak() {
    const div = document.createElement('div');
    div.className = 'flex items-center gap-2 break-item';
    div.innerHTML = `
        <input type="text" name="breaks[${breakCount}][label]" placeholder="Mola adı"
            class="flex-1 px-2 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        <input type="number" name="breaks[${breakCount}][duration_minutes]" value="30" min="1" max="120" placeholder="Dk"
            class="w-20 px-2 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        <span class="text-xs text-gray-400">dk</span>
        <button type="button" onclick="this.closest('.break-item').remove()" class="text-red-400 hover:text-red-600">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
        </button>`;
    document.getElementById('breaksList').appendChild(div);
    breakCount++;
}
</script>
