<?php
// Generated by Cursor prompt — Notification: Advance Request — date: 2026-03-15

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Notification;

class AdvanceRequestNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        public readonly int    $advanceId,
        public readonly string $personelName,
        public readonly float  $amount,
        public readonly string $currency,
        public readonly string $reason
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'broadcast'];
    }

    public function toArray(object $notifiable): array
    {
        return [
            'type'         => 'advance_request',
            'icon'         => '💰',
            'title'        => 'Yeni Avans Talebi',
            'message'      => "{$this->personelName} — " . number_format($this->amount, 2) . " {$this->currency}",
            'subtitle'     => mb_substr($this->reason, 0, 80) . (mb_strlen($this->reason) > 80 ? '...' : ''),
            'action_url'   => "/admin/advances",
            'action_label' => 'Avansı İncele',
            'model_id'     => $this->advanceId,
            'model_type'   => 'advance_request',
            'color'        => 'orange',
        ];
    }

    public function toBroadcast(object $notifiable): array
    {
        return $this->toArray($notifiable);
    }
}
