<?php
// Generated by Cursor prompt — Notification: Leave Request — date: 2026-03-15

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Notifications\Notification;

class LeaveRequestNotification extends Notification implements ShouldQueue
{
    use Queueable;

    public function __construct(
        public readonly int    $leaveRequestId,
        public readonly string $personelName,
        public readonly string $leaveTypeName,
        public readonly float  $totalDays,
        public readonly string $startDate,
        public readonly string $endDate,
        public readonly string $requestedBy
    ) {}

    public function via(object $notifiable): array
    {
        return ['database', 'broadcast'];
    }

    public function toArray(object $notifiable): array
    {
        return [
            'type'           => 'leave_request',
            'icon'           => '📅',
            'title'          => 'Yeni İzin Talebi',
            'message'        => "{$this->personelName} — {$this->leaveTypeName} ({$this->totalDays} gün)",
            'subtitle'       => "{$this->startDate} → {$this->endDate}",
            'action_url'     => "/admin/leave",
            'action_label'   => 'İzni İncele',
            'model_id'       => $this->leaveRequestId,
            'model_type'     => 'leave_request',
            'requested_by'   => $this->requestedBy,
            'color'          => 'yellow',
        ];
    }

    public function toBroadcast(object $notifiable): array
    {
        return $this->toArray($notifiable);
    }
}
