{{-- Generated by Cursor prompt — module: CMS Dashboard — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Site İçerik Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Site İçerik Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Site İçerik Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">Kurumsal web sitesinin tüm içeriklerini buradan yönetin.</p>
    </div>
    <a href="{{ route('home') }}" target="_blank"
        class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-50">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 6H6a2 2 0 00-2 2v10a2 2 0 002 2h10a2 2 0 002-2v-4M14 4h6m0 0v6m0-6L10 14"/></svg>
        Siteyi Önizle
    </a>
@endsection

@section('content')

{{-- Sekme Navigasyonu --}}
<div class="flex gap-1 border-b border-gray-200 mb-6" x-data="{ tab: 'hero' }">
    @foreach([
        ['hero','🎯 Hero'],
        ['features','⚡ Özellikler'],
        ['contact','📞 İletişim'],
        ['about','ℹ️ Hakkımızda'],
        ['blog','📝 Blog'],
        ['partners','🤝 İş Ortakları'],
    ] as [$key,$label])
    <button @click="tab = '{{ $key }}'; loadSection('{{ $key }}')"
        :class="tab === '{{ $key }}' ? 'border-[#02E0FB] text-[#02E0FB] bg-[#02E0FB]/5' : 'border-transparent text-gray-500 hover:text-gray-700'"
        class="px-4 py-3 text-sm font-medium border-b-2 transition-all whitespace-nowrap rounded-t-lg">
        {{ $label }}
    </button>
    @endforeach
</div>

{{-- Hero Section Editor --}}
<div id="section-hero" class="cms-section">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-6">Hero Bölümü İçerikleri</h3>
        <div class="grid grid-cols-1 gap-5" id="hero-fields">
            <div class="animate-pulse bg-gray-100 h-10 rounded-lg"></div>
            <div class="animate-pulse bg-gray-100 h-20 rounded-lg"></div>
        </div>
        <div class="flex justify-end mt-6">
            <button onclick="saveSection('hero')" class="px-6 py-2.5 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg transition-colors">
                💾 Kaydet
            </button>
        </div>
    </div>
</div>

{{-- Features Editor --}}
<div id="section-features" class="cms-section hidden">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-6">Özellikler Bölümü</h3>
        <div id="features-fields"></div>
        <div class="flex justify-end mt-6">
            <button onclick="saveSection('features')" class="px-6 py-2.5 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg transition-colors">💾 Kaydet</button>
        </div>
    </div>
</div>

{{-- Contact Editor --}}
<div id="section-contact" class="cms-section hidden">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-6">İletişim Bilgileri</h3>
        <div id="contact-fields"></div>
        <div class="flex justify-end mt-6">
            <button onclick="saveSection('contact')" class="px-6 py-2.5 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg transition-colors">💾 Kaydet</button>
        </div>
    </div>
</div>

{{-- About Editor --}}
<div id="section-about" class="cms-section hidden">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm p-6">
        <h3 class="text-lg font-semibold text-gray-800 mb-6">Hakkımızda İçeriği</h3>
        <div id="about-fields"></div>
        <div class="flex justify-end mt-6">
            <button onclick="saveSection('about')" class="px-6 py-2.5 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg transition-colors">💾 Kaydet</button>
        </div>
    </div>
</div>

{{-- Blog Editor --}}
<div id="section-blog" class="cms-section hidden">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div class="flex items-center justify-between p-5 border-b border-gray-100">
            <h3 class="text-lg font-semibold text-gray-800">Blog Yazıları</h3>
            <div class="flex items-center gap-3">
                <span class="text-sm text-gray-400">{{ $blogCount }} yazı</span>
                <button onclick="openBlogCreate()" class="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
                    Yeni Yazı
                </button>
            </div>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50 border-b border-gray-100">
                    <tr>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Başlık</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Kategori</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Durum</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Görüntüleme</th>
                        <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">İşlem</th>
                    </tr>
                </thead>
                <tbody id="blogTableBody" class="divide-y divide-gray-50">
                    <tr><td colspan="5" class="px-4 py-6 text-center text-gray-400">Yükleniyor...</td></tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

{{-- Partners Editor --}}
<div id="section-partners" class="cms-section hidden">
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div class="flex items-center justify-between p-5 border-b border-gray-100">
            <h3 class="text-lg font-semibold text-gray-800">İş Ortakları Logoları</h3>
            <div class="flex items-center gap-3">
                <span class="text-sm text-gray-400">{{ $partnerCount }} logo</span>
                <button onclick="openPartnerCreate()" class="flex items-center gap-2 px-4 py-2 text-sm font-semibold text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg">
                    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
                    Logo Ekle
                </button>
            </div>
        </div>
        <div id="partnerGrid" class="p-5 grid grid-cols-2 sm:grid-cols-4 lg:grid-cols-6 gap-4">
            <div class="animate-pulse bg-gray-100 h-20 rounded-xl"></div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
const CMS_URLS = {
    contents: '{{ route("admin.cms.contents") }}',
    upsert:   '{{ route("admin.cms.upsert") }}',
    blog: {
        list:    '{{ route("admin.cms.blog.index") }}',
        create:  '{{ route("admin.cms.blog.create") }}',
        store:   '{{ route("admin.cms.blog.store") }}',
        edit:    id => `/admin/cms/blog/${id}/edit`,
        update:  id => `/admin/cms/blog/${id}`,
        destroy: id => `/admin/cms/blog/${id}`,
    },
    partners: {
        list:    '{{ route("admin.cms.partners") }}',
        store:   '{{ route("admin.cms.partners.store") }}',
        destroy: id => `/admin/cms/partners/${id}`,
    },
};

// CMS içerik alanları tanımı
const SECTIONS = {
    hero: [
        { key: 'hero.title',    label: 'Ana Başlık',    type: 'text' },
        { key: 'hero.subtitle', label: 'Alt Başlık',    type: 'textarea' },
        { key: 'hero.cta_primary', label: 'Birincil Buton', type: 'text' },
        { key: 'hero.cta_secondary', label: 'İkincil Buton', type: 'text' },
    ],
    features: [
        { key: 'features.title',    label: 'Bölüm Başlığı', type: 'text' },
        { key: 'features.subtitle', label: 'Alt Başlık',     type: 'textarea' },
    ],
    contact: [
        { key: 'contact.address', label: 'Adres',   type: 'textarea' },
        { key: 'contact.phone',   label: 'Telefon', type: 'text' },
        { key: 'contact.email',   label: 'E-posta', type: 'text' },
        { key: 'contact.map_url', label: 'Harita URL', type: 'url' },
    ],
    about: [
        { key: 'about.title',   label: 'Başlık',    type: 'text' },
        { key: 'about.content', label: 'İçerik',    type: 'html' },
        { key: 'about.vision',  label: 'Vizyon',    type: 'textarea' },
        { key: 'about.mission', label: 'Misyon',    type: 'textarea' },
    ],
};

let sectionData = {};
let loadedSection = null;

document.addEventListener('DOMContentLoaded', () => loadSection('hero'));

function loadSection(section) {
    // Sekmeleri göster/gizle
    document.querySelectorAll('.cms-section').forEach(el => el.classList.add('hidden'));
    const target = document.getElementById(`section-${section}`);
    if (target) target.classList.remove('hidden');

    if (section === 'blog') { loadBlogs(); return; }
    if (section === 'partners') { loadPartners(); return; }

    const def = SECTIONS[section];
    if (!def) return;

    axios.get(CMS_URLS.contents, { params: { section } }).then(res => {
        const data = {};
        res.data.data.forEach(item => data[item.key] = item.value);
        sectionData[section] = data;

        const container = document.getElementById(`${section}-fields`);
        if (!container) return;

        container.innerHTML = def.map(field => `
            <div>
                <label class="block text-sm font-medium text-gray-700 mb-1">${field.label}</label>
                ${field.type === 'textarea' || field.type === 'html'
                    ? `<textarea name="${field.key}" rows="${field.type === 'html' ? 8 : 3}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">${data[field.key] || ''}</textarea>`
                    : `<input type="${field.type === 'url' ? 'url' : 'text'}" name="${field.key}" value="${(data[field.key] || '').replace(/"/g, '&quot;')}" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">`
                }
            </div>
        `).join('');
    });
}

function saveSection(section) {
    const def = SECTIONS[section];
    if (!def) return;

    const items = def.map(field => {
        const el = document.querySelector(`[name="${field.key}"]`);
        return { key: field.key, value: el?.value || '', type: field.type };
    });

    axios.post(CMS_URLS.upsert, { items }).then(res => {
        toast('success', res.data.message);
    });
}

// ─── Blog ────────────────────────────────────────────────────────────────────

function loadBlogs() {
    axios.get(CMS_URLS.blog.list, { params: { per_page: 20 } }).then(res => {
        const tbody = document.getElementById('blogTableBody');
        if (!res.data.data.length) {
            tbody.innerHTML = `<tr><td colspan="5" class="px-4 py-8 text-center text-gray-400">Henüz yazı yok</td></tr>`;
            return;
        }
        tbody.innerHTML = res.data.data.map(b => `
            <tr class="hover:bg-gray-50 transition-colors">
                <td class="px-4 py-3">
                    <div>
                        <p class="font-medium text-gray-800 text-sm line-clamp-1">${b.title}</p>
                        <p class="text-xs text-gray-400 font-mono">${b.slug}</p>
                    </div>
                </td>
                <td class="px-4 py-3 text-sm text-gray-600">${b.category?.name || '—'}</td>
                <td class="px-4 py-3 text-center">
                    <span class="inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${b.is_published ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'}">
                        ${b.is_published ? 'Yayında' : 'Taslak'}
                    </span>
                </td>
                <td class="px-4 py-3 text-center text-sm text-gray-500">${b.views_count}</td>
                <td class="px-4 py-3 text-right">
                    <div class="flex items-center justify-end gap-1">
                        <button onclick="openBlogEdit(${b.id})" class="p-1.5 text-gray-400 hover:text-amber-500 hover:bg-amber-50 rounded-lg">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                        </button>
                        <button onclick="confirmDelete(CMS_URLS.blog.destroy(${b.id}), loadBlogs)" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                        </button>
                    </div>
                </td>
            </tr>`).join('');
    });
}

function openBlogCreate() {
    axios.get(CMS_URLS.blog.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni Blog Yazısı';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitBlogForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Yayımla</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function openBlogEdit(id) {
    axios.get(CMS_URLS.blog.edit(id)).then(res => {
        document.getElementById('modalTitle').textContent = 'Blog Yazısını Düzenle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitBlogForm('${CMS_URLS.blog.update(id)}','PUT')" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Güncelle</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function submitBlogForm(url = CMS_URLS.blog.store, method = 'POST') {
    const form = document.getElementById('blogForm');
    const editor = document.getElementById('contentEditor');
    const hidden = document.getElementById('contentHidden');
    if (editor && hidden) hidden.value = editor.innerHTML;

    const fd = new FormData(form);
    fd.delete('is_published');
    fd.append('is_published', form.querySelector('[name="is_published"]')?.checked ? '1' : '0');

    const progressWrap = document.getElementById('uploadProgress');
    const progressBar = document.getElementById('progressBar');
    const cfg = {
        headers: { 'Content-Type': 'multipart/form-data', 'Accept': 'application/json', 'X-Requested-With': 'XMLHttpRequest' },
        onUploadProgress: (e) => {
            if (!e.total || !progressWrap || !progressBar) return;
            progressWrap.classList.remove('hidden');
            progressBar.style.width = Math.round((e.loaded * 100) / e.total) + '%';
        },
    };

    const run = method === 'PUT'
        ? (() => { fd.append('_method', 'PUT'); return axios.post(url, fd, cfg); })()
        : axios.post(url, fd, cfg);

    run.then(res => {
        if (progressWrap) { progressWrap.classList.add('hidden'); progressBar.style.width = '0%'; }
        document.getElementById('globalModal').classList.add('hidden');
        toast('success', res.data.message);
        loadBlogs();
    }).catch(err => {
        if (progressWrap) { progressWrap.classList.add('hidden'); if (progressBar) progressBar.style.width = '0%'; }
        const d = err.response?.data;
        const msg = d?.message || (d?.errors && Object.values(d.errors).flat().join(' ')) || 'Kayıt başarısız';
        toast('error', msg);
    });
}

// ─── Partners ────────────────────────────────────────────────────────────────

function loadPartners() {
    axios.get(CMS_URLS.partners.list).then(res => {
        const grid = document.getElementById('partnerGrid');
        grid.innerHTML = res.data.data.map(p => `
            <div class="relative group rounded-xl border-2 border-gray-100 p-4 flex flex-col items-center justify-center min-h-20 hover:border-[#02E0FB] transition-colors">
                ${p.logo_path
                    ? `<img src="/storage/${p.logo_path}" alt="${p.name}" class="max-h-10 object-contain">`
                    : `<span class="font-bold text-gray-400 text-sm">${p.name}</span>`}
                <p class="text-xs text-gray-400 mt-1 truncate w-full text-center">${p.name}</p>
                <button onclick="confirmDelete(CMS_URLS.partners.destroy(${p.id}), loadPartners)"
                    class="absolute top-1 right-1 opacity-0 group-hover:opacity-100 p-1 text-red-400 hover:bg-red-50 rounded transition-all">
                    <svg class="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                </button>
            </div>`).join('') + `
            <button onclick="openPartnerCreate()" class="rounded-xl border-2 border-dashed border-gray-200 hover:border-[#02E0FB] min-h-20 flex flex-col items-center justify-center gap-1 text-gray-400 hover:text-[#02E0FB] transition-colors">
                <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
                <span class="text-xs font-medium">Ekle</span>
            </button>`;
    });
}

function openPartnerCreate() {
    Swal.fire({
        title: 'İş Ortağı Ekle',
        html: `
            <input type="text" id="pName" placeholder="Şirket Adı" class="swal2-input w-full" style="display:flex">
            <input type="url" id="pUrl" placeholder="Website URL" class="swal2-input w-full" style="display:flex">
            <input type="text" id="pAlt" placeholder="Alt Text" class="swal2-input w-full" style="display:flex">`,
        showCancelButton: true,
        confirmButtonColor: '#02E0FB',
        confirmButtonText: 'Ekle',
        cancelButtonText: 'İptal',
        preConfirm: () => {
            const name = document.getElementById('pName').value;
            if (!name) { Swal.showValidationMessage('Şirket adı zorunludur.'); return false; }
            return { name, website_url: document.getElementById('pUrl').value, alt_text: document.getElementById('pAlt').value };
        }
    }).then(r => {
        if (r.isConfirmed) {
            axios.post(CMS_URLS.partners.store, r.value).then(res => {
                toast('success', res.data.message);
                loadPartners();
            });
        }
    });
}
</script>
@endpush
