{{-- Generated by Cursor prompt — module: Abonelik Yönetimi — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Abonelik & Faturalar')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Abonelik & Faturalar</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Abonelik Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">Mevcut paketinizi ve fatura geçmişinizi yönetin.</p>
    </div>
    <a href="{{ route('admin.subscriptions.billing') }}" class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 7h6m0 10v-3m-3 3h.01M9 17h.01M9 14h.01M12 14h.01M15 11h.01M12 11h.01M9 11h.01M7 21h10a2 2 0 002-2V5a2 2 0 00-2-2H7a2 2 0 00-2 2v14a2 2 0 002 2z"/></svg>
        Faturalar
    </a>
@endsection

@section('content')

{{-- Mevcut Abonelik --}}
@if($subscription)
<div class="bg-gradient-to-r from-gray-900 to-gray-800 rounded-2xl p-6 mb-8 text-white">
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
            <p class="text-xs text-gray-400 uppercase tracking-wider mb-1">Mevcut Paket</p>
            <h2 class="text-2xl font-black mb-1">{{ $subscription->plan?->name ?? 'Bilinmeyen Plan' }}</h2>
            <div class="flex items-center gap-3">
                <span class="inline-flex px-3 py-1 rounded-full text-xs font-semibold
                    {{ $subscription->status === 'active' ? 'bg-green-500/20 text-green-400' : ($subscription->status === 'trial' ? 'bg-blue-500/20 text-blue-400' : 'bg-gray-500/20 text-gray-400') }}">
                    {{ $subscription->status_label }}
                </span>
                @if($subscription->ends_at)
                <span class="text-sm text-gray-400">
                    {{ $subscription->days_remaining }} gün kaldı ({{ $subscription->ends_at->format('d.m.Y') }})
                </span>
                @endif
            </div>
        </div>
        <div class="text-right">
            <p class="text-3xl font-black text-[#02E0FB]">
                {{ number_format($subscription->price, 0, ',', '.') }} {{ $subscription->plan?->currency ?? 'TRY' }}
            </p>
            <p class="text-gray-400 text-sm">/ {{ $subscription->billing_cycle === 'yearly' ? 'yıl' : 'ay' }}</p>
        </div>
    </div>

    @if($subscription->isOnTrial())
    <div class="mt-4 p-3 bg-yellow-500/20 border border-yellow-500/30 rounded-xl">
        <p class="text-yellow-300 text-sm font-medium">⏰ Deneme süreniz {{ $subscription->trial_ends_at?->diffForHumans() }} bitiyor. Ücretli plana geçin!</p>
    </div>
    @endif

    <div class="mt-5 flex gap-3">
        <button onclick="document.getElementById('upgradePlan').classList.toggle('hidden')"
            class="px-5 py-2.5 bg-[#02E0FB] text-gray-900 font-bold text-sm rounded-xl hover:bg-cyan-300 transition-colors">
            Plan Değiştir
        </button>
        <button class="px-5 py-2.5 border border-gray-600 text-gray-300 font-medium text-sm rounded-xl hover:border-gray-400 transition-colors">
            Aboneliği Yönet
        </button>
    </div>
</div>
@endif

{{-- Plan Değiştirme Bölümü --}}
<div id="upgradePlan" class="{{ $subscription ? 'hidden' : '' }} mb-8">
    <h2 class="text-xl font-bold text-gray-900 mb-6">{{ $subscription ? 'Plan Değiştir' : 'Paket Seç' }}</h2>
    <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
        @foreach($plans as $plan)
        <div class="bg-white rounded-2xl border-2 p-6 card-hover {{ $plan->is_popular ? 'border-[#02E0FB] shadow-lg' : 'border-gray-100' }}">
            @if($plan->is_popular)
            <div class="text-xs font-black text-[#02E0FB] mb-2">⭐ EN POPÜLER</div>
            @endif
            <h3 class="text-xl font-black text-gray-900 mb-1">{{ $plan->name }}</h3>
            <p class="text-sm text-gray-500 mb-4">{{ $plan->description }}</p>
            <div class="mb-5">
                <span class="text-4xl font-black text-gray-900">{{ number_format($plan->price_monthly, 0, ',', '.') }}</span>
                <span class="text-gray-400 text-sm"> TRY/ay</span>
            </div>
            <ul class="space-y-2 mb-6">
                @foreach($plan->features ?? ['Temel özellikler'] as $feature)
                <li class="flex items-center gap-2 text-sm text-gray-600">
                    <svg class="w-4 h-4 text-[#02E0FB] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 13l4 4L19 7"/></svg>
                    {{ is_string($feature) ? $feature : ($feature['label'] ?? '') }}
                </li>
                @endforeach
                @if($plan->max_personel)
                <li class="flex items-center gap-2 text-sm text-gray-600">
                    <svg class="w-4 h-4 text-[#02E0FB] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 13l4 4L19 7"/></svg>
                    Maks. {{ $plan->max_personel }} personel
                </li>
                @else
                <li class="flex items-center gap-2 text-sm text-gray-600">
                    <svg class="w-4 h-4 text-[#02E0FB] shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M5 13l4 4L19 7"/></svg>
                    Sınırsız personel
                </li>
                @endif
            </ul>
            <button onclick="upgradeToPlan({{ $plan->id }}, '{{ $plan->name }}')"
                class="{{ $plan->is_popular ? 'btn-primary' : 'border-2 border-[#02E0FB] text-[#02E0FB] hover:bg-[#02E0FB] hover:text-gray-900 transition-all' }} w-full py-3 rounded-xl text-sm font-bold"
                {{ $subscription && $subscription->plan_id == $plan->id ? 'disabled' : '' }}>
                {{ $subscription && $subscription->plan_id == $plan->id ? '✓ Mevcut Plan' : 'Bu Pakete Geç' }}
            </button>
        </div>
        @endforeach
    </div>
</div>

@endsection

@push('scripts')
<script>
function upgradeToPlan(planId, planName) {
    Swal.fire({
        title: `${planName} Paketine Geç`,
        html: `
            <p class="text-sm text-gray-600 mb-4">Fatura döngüsünü seçin:</p>
            <div class="flex gap-3 justify-center">
                <label class="flex items-center gap-2 cursor-pointer px-4 py-2 border-2 border-gray-200 rounded-xl has-[:checked]:border-[#02E0FB] transition-colors">
                    <input type="radio" name="billing_cycle" value="monthly" checked class="text-[#02E0FB]">
                    <span class="text-sm font-medium">Aylık</span>
                </label>
                <label class="flex items-center gap-2 cursor-pointer px-4 py-2 border-2 border-gray-200 rounded-xl has-[:checked]:border-[#02E0FB] transition-colors">
                    <input type="radio" name="billing_cycle" value="yearly" class="text-[#02E0FB]">
                    <span class="text-sm font-medium">Yıllık <span class="text-green-600 font-bold">%20 indirim</span></span>
                </label>
            </div>`,
        showCancelButton: true,
        confirmButtonColor: '#02E0FB',
        confirmButtonText: 'Geçişi Onayla',
        cancelButtonText: 'İptal',
        preConfirm: () => ({
            plan_id: planId,
            billing_cycle: document.querySelector('[name="billing_cycle"]:checked')?.value || 'monthly',
        })
    }).then(r => {
        if (r.isConfirmed) {
            axios.post('{{ route("admin.subscriptions.upgrade") }}', r.value).then(res => {
                Swal.fire({ icon: 'success', title: 'Başarılı!', text: res.data.message });
                setTimeout(() => location.reload(), 2000);
            });
        }
    });
}
</script>
@endpush
