{{-- Generated by Cursor prompt — module: Masraf Yönetimi — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Masraf Yönetimi')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Masraf Yönetimi</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Masraf Yönetimi</h1>
        <p class="text-sm text-gray-500 mt-0.5">Personel masraf taleplerini ve fiş/belge yüklemelerini yönetin.</p>
    </div>
    @can('expense.request')
    <button onclick="openCreateExpenseModal()"
        class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
        Yeni Masraf Talebi
    </button>
    @endcan
@endsection

@section('content')

{{-- Filtreler --}}
<div class="bg-white rounded-xl border border-gray-100 p-4 mb-4 shadow-sm">
    <div class="grid grid-cols-2 md:grid-cols-5 gap-3">
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Personel</label>
            <select id="expPersonel" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($personels as $p)
                    <option value="{{ $p->id }}">{{ $p->first_name }} {{ $p->last_name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Kategori</label>
            <select id="expCategory" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                @foreach($categories as $c)
                    <option value="{{ $c->id }}">{{ $c->name }}</option>
                @endforeach
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Durum</label>
            <select id="expStatus" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                <option value="pending">Bekleyen</option>
                <option value="approved">Onaylanan</option>
                <option value="rejected">Reddedilen</option>
                <option value="paid">Ödenen</option>
                <option value="cancelled">İptal</option>
            </select>
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Tarih Aralığı</label>
            <input type="date" id="expDateFrom" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div class="flex items-end">
            <button onclick="loadExpenses()" class="w-full px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Filtrele</button>
        </div>
    </div>
</div>

{{-- Tablo --}}
<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Personel</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Kategori</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">Tutar</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Açıklama</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Tarih</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Belge</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Durum</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">İşlem</th>
                </tr>
            </thead>
            <tbody id="expTableBody" class="divide-y divide-gray-50">
                <tr><td colspan="8" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
            </tbody>
        </table>
    </div>
</div>

@endsection

@push('scripts')
<script>
const EXP_URLS = {
    list:    '{{ route("admin.expense.index") }}',
    create:  '{{ route("admin.expense.create") }}',
    store:   '{{ route("admin.expense.store") }}',
    approve: id => `/admin/expenses/requests/${id}/approve`,
    reject:  id => `/admin/expenses/requests/${id}/reject`,
    paid:    id => `/admin/expenses/requests/${id}/paid`,
    destroy: id => `/admin/expenses/requests/${id}`,
};

const statusMap = {
    pending:   { label: 'Bekliyor',    bg: 'bg-yellow-100', text: 'text-yellow-700' },
    approved:  { label: 'Onaylandı',   bg: 'bg-green-100',  text: 'text-green-700' },
    rejected:  { label: 'Reddedildi',  bg: 'bg-red-100',    text: 'text-red-700' },
    paid:      { label: 'Ödendi',      bg: 'bg-blue-100',   text: 'text-blue-700' },
    cancelled: { label: 'İptal',       bg: 'bg-gray-100',   text: 'text-gray-600' },
};

document.addEventListener('DOMContentLoaded', loadExpenses);

function loadExpenses(page = 1) {
    axios.get(EXP_URLS.list, { params: {
        page,
        personel_id:  document.getElementById('expPersonel').value,
        category_id:  document.getElementById('expCategory').value,
        status:       document.getElementById('expStatus').value,
        date_from:    document.getElementById('expDateFrom').value,
        per_page: 15,
    }}).then(res => renderExpTable(res.data));
}

function renderExpTable(data) {
    const tbody = document.getElementById('expTableBody');
    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="8" class="px-4 py-8 text-center text-gray-400">Kayıt bulunamadı</td></tr>`;
        return;
    }
    tbody.innerHTML = data.data.map(e => {
        const sc = statusMap[e.status] || { label: e.status, bg: 'bg-gray-100', text: 'text-gray-600' };
        const amount = new Intl.NumberFormat('tr-TR', { style:'currency', currency: e.currency||'TRY' }).format(e.amount);
        const date   = e.expense_date ? new Date(e.expense_date).toLocaleDateString('tr-TR') : '—';
        const attachCount = Array.isArray(e.attachments) ? e.attachments.length : 0;
        return `
        <tr class="hover:bg-gray-50 transition-colors ${e.exceeds_limit ? 'bg-orange-50/30' : ''}">
            <td class="px-4 py-3">
                <div class="flex items-center gap-2">
                    <div class="w-7 h-7 rounded-full bg-[#02E0FB]/15 text-[#02E0FB] text-xs font-bold flex items-center justify-center">
                        ${(e.personel?.first_name?.[0]||'') + (e.personel?.last_name?.[0]||'')}
                    </div>
                    <span class="font-medium text-gray-800">${e.personel?.first_name||''} ${e.personel?.last_name||''}</span>
                </div>
            </td>
            <td class="px-4 py-3 text-gray-600 text-sm">${e.category?.name || '—'}</td>
            <td class="px-4 py-3 text-right font-bold ${e.exceeds_limit ? 'text-orange-600' : 'text-gray-800'}">
                ${amount} ${e.exceeds_limit ? '<span class="text-xs">⚠</span>' : ''}
            </td>
            <td class="px-4 py-3 text-gray-600 text-sm max-w-xs truncate">${e.description || '—'}</td>
            <td class="px-4 py-3 text-gray-500 text-sm">${date}</td>
            <td class="px-4 py-3 text-center">
                ${attachCount > 0
                    ? `<button class="flex items-center gap-1 mx-auto text-xs text-[#02E0FB] hover:underline">
                        <svg class="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"/></svg>
                        ${attachCount} dosya
                       </button>`
                    : '<span class="text-gray-300 text-xs">—</span>'}
            </td>
            <td class="px-4 py-3 text-center">
                <span class="inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${sc.bg} ${sc.text}">${sc.label}</span>
            </td>
            <td class="px-4 py-3">
                <div class="flex items-center justify-end gap-1">
                    ${e.status === 'pending' ? `
                    <button onclick="approveExpense(${e.id})" class="p-1.5 text-gray-400 hover:text-green-600 hover:bg-green-50 rounded-lg" title="Onayla">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
                    </button>
                    <button onclick="rejectExpense(${e.id})" class="p-1.5 text-gray-400 hover:text-red-600 hover:bg-red-50 rounded-lg" title="Reddet">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12"/></svg>
                    </button>` : ''}
                    ${e.status === 'approved' ? `
                    <button onclick="markPaid(${e.id})" class="p-1.5 text-gray-400 hover:text-blue-600 hover:bg-blue-50 rounded-lg" title="Ödenmiş İşaretle">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 9V7a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2m2 4h10a2 2 0 002-2v-6a2 2 0 00-2-2H9a2 2 0 00-2 2v6a2 2 0 002 2zm7-5a2 2 0 11-4 0 2 2 0 014 0z"/></svg>
                    </button>` : ''}
                </div>
            </td>
        </tr>`;
    }).join('');
}

function openCreateExpenseModal() {
    axios.get(EXP_URLS.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni Masraf Talebi';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitExpenseForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Talep Oluştur</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function submitExpenseForm() {
    const form = document.getElementById('expenseForm');
    const data = Object.fromEntries(new FormData(form).entries());
    axios.post(EXP_URLS.store, data).then(res => {
        document.getElementById('globalModal').classList.add('hidden');
        if (res.data.exceeds_limit) {
            toast('warning', res.data.message);
        } else {
            toast('success', res.data.message);
        }
        loadExpenses();
    });
}

function approveExpense(id) {
    Swal.fire({ title: 'Masrafı Onayla', text: 'Bu masraf talebini onaylıyor musunuz?', icon: 'question',
        showCancelButton: true, confirmButtonColor: '#02E0FB', cancelButtonColor: '#6B7280',
        confirmButtonText: 'Onayla', cancelButtonText: 'İptal'
    }).then(r => {
        if (r.isConfirmed) axios.post(EXP_URLS.approve(id)).then(res => { toast('success', res.data.message); loadExpenses(); });
    });
}

function rejectExpense(id) {
    Swal.fire({ title: 'Masrafı Reddet', input: 'textarea', inputPlaceholder: 'Ret gerekçesi...',
        showCancelButton: true, confirmButtonColor: '#FA6001', confirmButtonText: 'Reddet', cancelButtonText: 'İptal',
        inputValidator: v => !v && 'Gerekçe zorunludur!'
    }).then(r => {
        if (r.isConfirmed) axios.post(EXP_URLS.reject(id), { reason: r.value }).then(res => { toast('success', res.data.message); loadExpenses(); });
    });
}

function markPaid(id) {
    Swal.fire({ title: 'Ödendi Olarak İşaretle?', icon: 'question',
        showCancelButton: true, confirmButtonColor: '#02E0FB', confirmButtonText: 'Evet, Ödendi', cancelButtonText: 'İptal'
    }).then(r => {
        if (r.isConfirmed) axios.post(EXP_URLS.paid(id)).then(res => { toast('success', res.data.message); loadExpenses(); });
    });
}
</script>
@endpush
