<?php
// Generated by Cursor prompt — module: Personel — date: 2026-03-15

namespace App\Modules\Personel\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StorePersonelRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        $companyId = auth()->user()->company_id;

        return [
            'first_name'     => 'required|string|max:100',
            'last_name'      => 'required|string|max:100',
            'email'          => [
                'nullable',
                'email',
                'max:191',
                Rule::unique('personels')->where('company_id', $companyId),
            ],
            'phone'          => ['nullable', 'string', 'regex:/^\+?[0-9\s\-\(\)]{7,20}$/'],
            'national_id'    => 'nullable|string|max:20',
            'birth_date'     => 'nullable|date|before:today',
            'gender'         => 'nullable|in:M,F,other',
            'blood_type'     => 'nullable|string|max:5',
            'position_id'    => 'nullable|exists:positions,id',
            'department_id'  => 'nullable|exists:departments,id',
            'salary'         => 'nullable|numeric|min:0|max:9999999',
            'currency'       => 'nullable|string|size:3',
            'hire_date'      => 'nullable|date',
            'status'         => 'nullable|in:active,terminated,on_leave,suspended',
            'attributes'     => 'nullable|array',
        ];
    }

    public function messages(): array
    {
        return [
            'first_name.required' => 'Ad alanı zorunludur.',
            'last_name.required'  => 'Soyad alanı zorunludur.',
            'email.unique'        => 'Bu e-posta adresi şirketinizde zaten kayıtlıdır.',
            'email.email'         => 'Geçerli bir e-posta adresi giriniz.',
            'phone.regex'         => 'Geçerli bir telefon numarası giriniz.',
            'salary.numeric'      => 'Maaş sayısal bir değer olmalıdır.',
        ];
    }
}
