<?php
// Generated by Cursor prompt — module: Personel — date: 2026-03-15

namespace Tests\Feature;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;
use App\Models\User;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;

class PersonelCrudTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    protected User $admin;

    protected function setUp(): void
    {
        parent::setUp();

        // Temel roller ve izinler oluştur
        Permission::firstOrCreate(['name' => 'access_admin', 'guard_name' => 'web']);
        Permission::firstOrCreate(['name' => 'personel.view', 'guard_name' => 'web']);
        Permission::firstOrCreate(['name' => 'personel.create', 'guard_name' => 'web']);
        Permission::firstOrCreate(['name' => 'personel.update', 'guard_name' => 'web']);
        Permission::firstOrCreate(['name' => 'personel.delete', 'guard_name' => 'web']);

        $role = Role::firstOrCreate(['name' => 'company_admin', 'guard_name' => 'web']);
        $role->givePermissionTo(['access_admin', 'personel.view', 'personel.create', 'personel.update', 'personel.delete']);

        $this->admin = User::factory()->create(['company_id' => 1]);
        $this->admin->assignRole('company_admin');
    }

    /** @test */
    public function it_can_list_personels(): void
    {
        $response = $this->actingAs($this->admin)
            ->getJson(route('admin.personel.index'));

        $response->assertStatus(200)
            ->assertJsonStructure(['data', 'total', 'pages']);
    }

    /** @test */
    public function it_can_create_a_personel(): void
    {
        $payload = [
            'first_name'    => 'Ahmet',
            'last_name'     => 'Yılmaz',
            'email'         => 'ahmet.yilmaz@test.com',
            'phone'         => '+90 555 123 4567',
            'hire_date'     => '2025-01-15',
            'status'        => 'active',
        ];

        $response = $this->actingAs($this->admin)
            ->postJson(route('admin.personel.store'), $payload);

        $response->assertStatus(201)
            ->assertJsonPath('success', true)
            ->assertJsonPath('data.first_name', 'Ahmet');

        $this->assertDatabaseHas('personels', [
            'first_name' => 'Ahmet',
            'last_name'  => 'Yılmaz',
        ]);
    }

    /** @test */
    public function it_validates_required_fields(): void
    {
        $response = $this->actingAs($this->admin)
            ->postJson(route('admin.personel.store'), []);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['first_name', 'last_name']);
    }

    /** @test */
    public function it_prevents_duplicate_email_in_same_company(): void
    {
        $this->actingAs($this->admin)
            ->postJson(route('admin.personel.store'), [
                'first_name' => 'Ali',
                'last_name'  => 'Veli',
                'email'      => 'duplicate@test.com',
            ]);

        $response = $this->actingAs($this->admin)
            ->postJson(route('admin.personel.store'), [
                'first_name' => 'Ayşe',
                'last_name'  => 'Kaya',
                'email'      => 'duplicate@test.com',
            ]);

        $response->assertStatus(422)
            ->assertJsonValidationErrors(['email']);
    }

    /** @test */
    public function it_can_update_a_personel(): void
    {
        $createResponse = $this->actingAs($this->admin)
            ->postJson(route('admin.personel.store'), [
                'first_name' => 'Test',
                'last_name'  => 'Personel',
            ]);

        $personelId = $createResponse->json('data.id');

        $response = $this->actingAs($this->admin)
            ->putJson(route('admin.personel.update', $personelId), [
                'first_name' => 'Güncel',
                'last_name'  => 'Personel',
            ]);

        $response->assertStatus(200)
            ->assertJsonPath('data.first_name', 'Güncel');
    }

    /** @test */
    public function it_can_soft_delete_a_personel(): void
    {
        $createResponse = $this->actingAs($this->admin)
            ->postJson(route('admin.personel.store'), [
                'first_name' => 'Silinecek',
                'last_name'  => 'Personel',
            ]);

        $personelId = $createResponse->json('data.id');

        $response = $this->actingAs($this->admin)
            ->deleteJson(route('admin.personel.destroy', $personelId));

        $response->assertStatus(200)
            ->assertJsonPath('success', true);

        $this->assertSoftDeleted('personels', ['id' => $personelId]);
    }

    /** @test */
    public function unauthenticated_user_cannot_access_personel_routes(): void
    {
        $response = $this->getJson(route('admin.personel.index'));
        $response->assertStatus(401);
    }
}
