{{-- Generated by Cursor prompt — module: İzin Bakiyeleri — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'İzin Bakiyeleri')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <a href="{{ route('admin.leave.index') }}" class="hover:text-[#02E0FB]">İzin Yönetimi</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">İzin Bakiyeleri</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">İzin Bakiyeleri</h1>
        <p class="text-sm text-gray-500 mt-0.5">Personellerin yıllık izin bakiyelerini görüntüleyin.</p>
    </div>
    <div class="flex items-center gap-2">
        <select id="balanceYear" onchange="loadBalances()"
            class="text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
            @for($y = now()->year + 1; $y >= now()->year - 2; $y--)
                <option value="{{ $y }}" {{ $y == now()->year ? 'selected' : '' }}>{{ $y }}</option>
            @endfor
        </select>
        @can('leave.manage')
        <button onclick="recalculateAll()"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#FA6001] rounded-lg hover:bg-orange-500 transition-colors shadow-sm">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
            Bakiyeleri Yeniden Hesapla
        </button>
        @endcan
    </div>
@endsection

@section('content')

{{-- Tablo --}}
<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase sticky left-0 bg-gray-50">Personel</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">İzin Türü</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Hak (gün)</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Kullanılan</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Kalan</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">Kullanım Oranı</th>
                </tr>
            </thead>
            <tbody id="balancesBody" class="divide-y divide-gray-50">
                <tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
            </tbody>
        </table>
    </div>
    <div class="px-4 py-3 border-t border-gray-100 flex items-center justify-between">
        <div class="text-xs text-gray-500" id="balancesInfo">—</div>
        <div id="balancesPagination" class="flex gap-1"></div>
    </div>
</div>

@endsection

@push('scripts')
<script>
const BALANCE_URLS = {
    list:        '{{ route("admin.leave.balances") }}',
    recalculate: '/admin/leave/balances/recalculate',
};

document.addEventListener('DOMContentLoaded', loadBalances);

function loadBalances(page = 1) {
    const year = document.getElementById('balanceYear').value;
    axios.get(BALANCE_URLS.list, { params: { year, page, per_page: 25 } }).then(res => {
        renderBalances(res.data);
    });
}

function renderBalances(data) {
    const tbody = document.getElementById('balancesBody');
    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400 text-sm">Bakiye kaydı bulunamadı</td></tr>`;
        return;
    }

    tbody.innerHTML = data.data.map(b => {
        const pct     = b.entitled_days > 0 ? Math.round((b.used_days / b.entitled_days) * 100) : 0;
        const barColor = pct >= 90 ? 'bg-red-400' : pct >= 70 ? 'bg-yellow-400' : 'bg-[#02E0FB]';
        const remaining = parseFloat(b.remaining_days);
        const remainColor = remaining <= 0 ? 'text-red-600 font-bold' : remaining <= 3 ? 'text-yellow-600 font-semibold' : 'text-green-700 font-semibold';

        return `
        <tr class="hover:bg-gray-50 transition-colors">
            <td class="px-4 py-3 sticky left-0 bg-white">
                <div class="flex items-center gap-2">
                    <div class="w-7 h-7 rounded-full bg-[#02E0FB]/15 text-[#02E0FB] text-xs font-bold flex items-center justify-center">
                        ${(b.personel?.first_name?.[0] || '') + (b.personel?.last_name?.[0] || '')}
                    </div>
                    <span class="font-medium text-gray-800">${b.personel?.first_name || ''} ${b.personel?.last_name || ''}</span>
                </div>
            </td>
            <td class="px-4 py-3 text-gray-600">${b.leave_type?.name || '—'}</td>
            <td class="px-4 py-3 text-center font-medium text-gray-800">${b.entitled_days}</td>
            <td class="px-4 py-3 text-center text-gray-600">${b.used_days}</td>
            <td class="px-4 py-3 text-center ${remainColor}">${b.remaining_days}</td>
            <td class="px-4 py-3">
                <div class="flex items-center gap-2">
                    <div class="flex-1 bg-gray-100 rounded-full h-2 overflow-hidden">
                        <div class="h-2 rounded-full ${barColor} transition-all" style="width: ${Math.min(pct, 100)}%"></div>
                    </div>
                    <span class="text-xs text-gray-500 w-8 text-right">${pct}%</span>
                </div>
            </td>
        </tr>`;
    }).join('');

    document.getElementById('balancesInfo').textContent = `${data.total} kayıt`;
}

function recalculateAll() {
    Swal.fire({
        title: 'Bakiyeleri Yeniden Hesapla',
        text: 'Tüm personellerin izin bakiyeleri güncel onaylı izinlere göre hesaplanacak.',
        icon: 'question',
        showCancelButton: true,
        confirmButtonColor: '#FA6001',
        confirmButtonText: 'Hesapla',
        cancelButtonText: 'İptal',
    }).then(result => {
        if (result.isConfirmed) {
            const year = document.getElementById('balanceYear').value;
            axios.post(BALANCE_URLS.recalculate, { year }).then(res => {
                toast('success', 'Bakiyeler yeniden hesaplandı.');
                loadBalances();
            });
        }
    });
}
</script>
@endpush
