<?php
// Generated by Cursor prompt — module: Sirket (CompanyController) — date: 2026-03-15

namespace App\Modules\Sirket\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Sirket\Models\Company;
use App\Modules\Sirket\Requests\StoreCompanyRequest;
use App\Modules\Sirket\Requests\UpdateCompanyRequest;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    /** Şirket listesi — Ajax DataTable JSON */
    public function index(Request $request): JsonResponse
    {
        $this->authorize('company.view');

        $query = Company::withCount('personels')
            ->withTrashed(false);

        if ($request->filled('search')) {
            $s = $request->search;
            $query->where(fn ($q) => $q->where('name', 'like', "%{$s}%")
                ->orWhere('domain', 'like', "%{$s}%")
                ->orWhere('city', 'like', "%{$s}%"));
        }

        if ($request->filled('status')) {
            $query->where('status', $request->status);
        }

        $companies = $query
            ->orderBy($request->get('sort_by', 'name'), $request->get('sort_dir', 'asc'))
            ->paginate($request->get('per_page', 15));

        return response()->json([
            'data'  => $companies->items(),
            'total' => $companies->total(),
            'pages' => $companies->lastPage(),
        ]);
    }

    /** Şirket listesi sayfasını render et */
    public function indexView()
    {
        $this->authorize('company.view');
        return view('admin.companies.index');
    }

    /** Create form HTML */
    public function create(): JsonResponse
    {
        $this->authorize('company.manage');
        return response()->json([
            'html' => view('admin.companies._form')->render(),
        ]);
    }

    /** Yeni şirket kaydet */
    public function store(StoreCompanyRequest $request): JsonResponse
    {
        $this->authorize('company.manage');

        $data              = $request->validated();
        $data['created_by'] = auth()->id();

        if ($request->hasFile('logo')) {
            $data['logo_path'] = $request->file('logo')->store('companies/logos', 'public');
        }

        $company = Company::create($data);

        $this->auditLog('company.created', $company);

        return response()->json([
            'success' => true,
            'message' => 'Şirket başarıyla oluşturuldu.',
            'data'    => $company,
        ], 201);
    }

    /** Edit form HTML */
    public function edit(Company $company): JsonResponse
    {
        $this->authorize('company.manage');
        return response()->json([
            'html' => view('admin.companies._form', compact('company'))->render(),
        ]);
    }

    /** Şirket güncelle */
    public function update(UpdateCompanyRequest $request, Company $company): JsonResponse
    {
        $this->authorize('company.manage');

        $data = $request->validated();

        if ($request->hasFile('logo')) {
            if ($company->logo_path) Storage::disk('public')->delete($company->logo_path);
            $data['logo_path'] = $request->file('logo')->store('companies/logos', 'public');
        }

        $company->update($data);

        $this->auditLog('company.updated', $company);

        return response()->json([
            'success' => true,
            'message' => 'Şirket güncellendi.',
            'data'    => $company->fresh(),
        ]);
    }

    /** Şirket sil (soft) */
    public function destroy(Company $company): JsonResponse
    {
        $this->authorize('company.manage');

        // Aktif personel varsa silme
        if ($company->personels()->where('is_active', true)->exists()) {
            return response()->json([
                'success' => false,
                'message' => 'Aktif personeli olan şirket silinemez.',
            ], 422);
        }

        $company->delete();

        $this->auditLog('company.deleted', $company);

        return response()->json([
            'success' => true,
            'message' => 'Şirket silindi.',
        ]);
    }

    /** Şirket detay */
    public function show(Company $company): JsonResponse
    {
        $this->authorize('company.view');
        return response()->json([
            'data' => $company->load(['departments', 'positions']),
        ]);
    }

    /** Organizasyon ağacı JSON */
    public function orgTree(Company $company): JsonResponse
    {
        $this->authorize('company.view');
        $departments = $company->rootDepartments()
            ->with('allChildren.personels', 'manager')
            ->withCount('personels')
            ->get();
        return response()->json(['data' => $departments]);
    }

    private function auditLog(string $action, Company $company): void
    {
        DB::table('audit_logs')->insert([
            'user_id'    => auth()->id(),
            'company_id' => $company->id,
            'action'     => $action,
            'model_type' => Company::class,
            'model_id'   => $company->id,
            'ip'         => request()->ip(),
            'created_at' => now(),
        ]);
    }
}
