{{-- Generated by Cursor prompt — module: Şirket — date: 2026-03-15 --}}
<form id="companyForm" class="space-y-5" novalidate>
    @csrf

    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">

        {{-- Şirket Adı --}}
        <div class="md:col-span-2">
            <label class="block text-sm font-medium text-gray-700 mb-1">Şirket Adı <span class="text-red-500">*</span></label>
            <input type="text" name="name" value="{{ $company->name ?? '' }}" required
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="Şirket Adı A.Ş.">
        </div>

        {{-- Alan Adı --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Alan Adı (Domain)</label>
            <input type="text" name="domain" value="{{ $company->domain ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
                placeholder="sirket.com.tr">
        </div>

        {{-- Durum --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Durum</label>
            <select name="status" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                <option value="active" {{ (isset($company) && $company->status === 'active') ? 'selected' : '' }}>Aktif</option>
                <option value="trial" {{ (!isset($company) || $company->status === 'trial') ? 'selected' : '' }}>Deneme</option>
                <option value="inactive" {{ (isset($company) && $company->status === 'inactive') ? 'selected' : '' }}>Pasif</option>
                <option value="suspended" {{ (isset($company) && $company->status === 'suspended') ? 'selected' : '' }}>Askıda</option>
            </select>
        </div>

        {{-- Vergi No --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Vergi Numarası</label>
            <input type="text" name="tax_number" value="{{ $company->tax_number ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="1234567890" maxlength="11">
        </div>

        {{-- Vergi Dairesi --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Vergi Dairesi</label>
            <input type="text" name="tax_office" value="{{ $company->tax_office ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="Ataşehir">
        </div>

        {{-- Telefon --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Telefon</label>
            <input type="text" name="phone" value="{{ $company->phone ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="+90 216 000 0000">
        </div>

        {{-- E-posta --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">E-posta</label>
            <input type="email" name="email" value="{{ $company->email ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="info@sirket.com">
        </div>

        {{-- Adres --}}
        <div class="md:col-span-2">
            <label class="block text-sm font-medium text-gray-700 mb-1">Adres</label>
            <input type="text" name="address" value="{{ $company->address ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="Mahalle, cadde, no...">
        </div>

        {{-- Şehir --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Şehir</label>
            <input type="text" name="city" value="{{ $company->city ?? '' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]"
                placeholder="İstanbul">
        </div>

        {{-- Zaman Dilimi --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Zaman Dilimi</label>
            <select name="timezone" class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
                @foreach(['Europe/Istanbul' => 'Türkiye (UTC+3)', 'UTC' => 'UTC', 'Europe/London' => 'Londra (UTC+0)', 'America/New_York' => 'New York (UTC-5)'] as $tz => $label)
                    <option value="{{ $tz }}" {{ (isset($company) && $company->timezone === $tz) ? 'selected' : ($tz === 'Europe/Istanbul' && !isset($company) ? 'selected' : '') }}>{{ $label }}</option>
                @endforeach
            </select>
        </div>

        {{-- Çalışma Günleri --}}
        <div class="md:col-span-2">
            <label class="block text-sm font-medium text-gray-700 mb-2">Çalışma Günleri</label>
            <div class="flex flex-wrap gap-2">
                @foreach([1=>'Pzt',2=>'Sal',3=>'Çar',4=>'Per',5=>'Cum',6=>'Cmt',7=>'Paz'] as $day => $label)
                    @php $checked = isset($company) ? in_array($day, $company->settings['working_days'] ?? [1,2,3,4,5]) : $day <= 5; @endphp
                    <label class="flex items-center gap-1.5 cursor-pointer">
                        <input type="checkbox" name="settings[working_days][]" value="{{ $day }}" {{ $checked ? 'checked' : '' }}
                            class="w-4 h-4 rounded text-[#02E0FB] border-gray-300 focus:ring-[#02E0FB]">
                        <span class="text-sm text-gray-700">{{ $label }}</span>
                    </label>
                @endforeach
            </div>
        </div>

        {{-- Mesai Başlangıç / Bitiş --}}
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Mesai Başlangıç</label>
            <input type="time" name="settings[work_start]" value="{{ $company->settings['work_start'] ?? '09:00' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Mesai Bitiş</label>
            <input type="time" name="settings[work_end]" value="{{ $company->settings['work_end'] ?? '18:00' }}"
                class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB]">
        </div>
    </div>
</form>
