{{-- Generated by Cursor prompt — module: Şirket Yapısı — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Şirket Yapısı')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Şirket Yapısı</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Şirket Yapısı</h1>
        <p class="text-sm text-gray-500 mt-0.5">Şirketleri, departmanları ve pozisyonları yönetin.</p>
    </div>
    @can('company.manage')
    <button onclick="openCreateCompanyModal()"
        class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
        Yeni Şirket
    </button>
    @endcan
@endsection

@section('content')

{{-- Sekmeler --}}
<div class="border-b border-gray-200 mb-5" x-data="{ tab: 'companies' }">
    <div class="flex gap-1">
        @foreach([['companies','Şirketler','19 21V5a2 2 0 00-2-2H7a2 2 0 00-2 2v16m14 0h2m-2 0h-5m-9 0H3m2 0h5M9 7h1m-1 4h1m4-4h1m-1 4h1m-5 10v-5a1 1 0 011-1h2a1 1 0 011 1v5m-4 0h4'],
            ['departments','Departmanlar','3 7h18M3 12h18M3 17h18'],
            ['positions','Pozisyonlar','21 13.255A23.931 23.931 0 0112 15c-3.183 0-6.22-.62-9-1.745M16 6a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z']] as [$key, $label, $icon]]
        <button @click="tab = '{{ $key }}'"
            :class="tab === '{{ $key }}' ? 'border-[#02E0FB] text-[#02E0FB] bg-[#02E0FB]/5' : 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'"
            class="flex items-center gap-2 px-4 py-3 text-sm font-medium border-b-2 transition-all rounded-t-lg">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="{{ $icon }}"/></svg>
            {{ $label }}
        </button>
        @endforeach
    </div>
</div>

{{-- Şirketler Tab --}}
<div id="tab-companies">

    {{-- Filtreler --}}
    <div class="bg-white rounded-xl border border-gray-100 p-4 mb-4 shadow-sm">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-3">
            <div>
                <label class="block text-xs font-medium text-gray-500 mb-1">Arama</label>
                <input type="text" id="searchCompany" placeholder="Şirket adı, alan adı..." class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
            </div>
            <div>
                <label class="block text-xs font-medium text-gray-500 mb-1">Durum</label>
                <select id="filterCompanyStatus" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                    <option value="">Tümü</option>
                    <option value="active">Aktif</option>
                    <option value="trial">Deneme</option>
                    <option value="inactive">Pasif</option>
                    <option value="suspended">Askıda</option>
                </select>
            </div>
            <div class="flex items-end">
                <button onclick="loadCompanies()" class="w-full px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Filtrele</button>
            </div>
        </div>
    </div>

    {{-- Tablo --}}
    <div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50 border-b border-gray-100">
                    <tr>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Şirket</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Alan Adı</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Şehir</th>
                        <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Personel</th>
                        <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Durum</th>
                        <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">İşlemler</th>
                    </tr>
                </thead>
                <tbody id="companyTableBody" class="divide-y divide-gray-50">
                    <tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
                </tbody>
            </table>
        </div>
        <div class="px-4 py-3 border-t border-gray-100 flex items-center justify-between">
            <div class="text-xs text-gray-500" id="companyTableInfo">—</div>
            <div id="companyTablePagination" class="flex gap-1"></div>
        </div>
    </div>
</div>

@endsection

@push('scripts')
<script>
const COMPANY_URLS = {
    list:    '{{ route("admin.companies.index") }}',
    create:  '{{ route("admin.companies.create") }}',
    store:   '{{ route("admin.companies.store") }}',
    edit:    id => `/admin/companies/${id}/edit`,
    update:  id => `/admin/companies/${id}`,
    destroy: id => `/admin/companies/${id}`,
    orgTree: id => `/admin/companies/${id}/org-tree`,
};

let companyCurrentPage = 1;

document.addEventListener('DOMContentLoaded', () => loadCompanies());

function loadCompanies(page = 1) {
    companyCurrentPage = page;
    const params = {
        page,
        search: document.getElementById('searchCompany').value,
        status: document.getElementById('filterCompanyStatus').value,
        per_page: 15,
    };
    axios.get(COMPANY_URLS.list, { params }).then(res => renderCompanyTable(res.data));
}

function renderCompanyTable(data) {
    const tbody = document.getElementById('companyTableBody');
    const statusMap = { active: ['Aktif','bg-green-100 text-green-700'], trial: ['Deneme','bg-blue-100 text-blue-700'], inactive: ['Pasif','bg-gray-100 text-gray-600'], suspended: ['Askıda','bg-red-100 text-red-700'] };

    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400 text-sm">Kayıt bulunamadı</td></tr>`;
        return;
    }

    tbody.innerHTML = data.data.map(c => {
        const [statusLabel, statusClass] = statusMap[c.status] ?? ['—', 'bg-gray-100 text-gray-600'];
        return `
        <tr class="hover:bg-gray-50 transition-colors">
            <td class="px-4 py-3">
                <div class="flex items-center gap-3">
                    <div class="w-9 h-9 rounded-lg bg-[#02E0FB]/10 flex items-center justify-center text-[#02E0FB] font-bold text-sm">${c.name[0]}</div>
                    <div>
                        <p class="font-medium text-gray-800">${c.name}</p>
                        <p class="text-xs text-gray-400">${c.email || '—'}</p>
                    </div>
                </div>
            </td>
            <td class="px-4 py-3 text-gray-600 text-sm">${c.domain || '—'}</td>
            <td class="px-4 py-3 text-gray-600 text-sm">${c.city || '—'}</td>
            <td class="px-4 py-3 text-center">
                <span class="font-semibold text-gray-800">${c.personels_count ?? 0}</span>
            </td>
            <td class="px-4 py-3">
                <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${statusClass}">${statusLabel}</span>
            </td>
            <td class="px-4 py-3">
                <div class="flex items-center justify-end gap-1">
                    <button onclick="openEditCompanyModal(${c.id})" class="p-1.5 text-gray-400 hover:text-amber-500 hover:bg-amber-50 rounded-lg" title="Düzenle">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                    </button>
                    <button onclick="confirmDelete(COMPANY_URLS.destroy(${c.id}), () => loadCompanies())" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg" title="Sil">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                    </button>
                </div>
            </td>
        </tr>`;
    }).join('');

    document.getElementById('companyTableInfo').textContent = `${data.total} kayıttan ${data.data.length} gösteriliyor`;
}

function openCreateCompanyModal() {
    axios.get(COMPANY_URLS.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni Şirket Ekle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitCompanyForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Kaydet</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function openEditCompanyModal(id) {
    axios.get(COMPANY_URLS.edit(id)).then(res => {
        document.getElementById('modalTitle').textContent = 'Şirketi Düzenle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitCompanyForm('${COMPANY_URLS.update(id)}','PUT')" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Güncelle</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function submitCompanyForm(url = COMPANY_URLS.store, method = 'POST') {
    const form = document.getElementById('companyForm');
    const data = Object.fromEntries(new FormData(form).entries());
    axios({ method, url, data }).then(res => {
        document.getElementById('globalModal').classList.add('hidden');
        toast('success', res.data.message);
        loadCompanies();
    });
}
</script>
@endpush
