<?php
// Generated by Cursor prompt — module: Personel — date: 2026-03-15

namespace App\Modules\Personel\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Facades\Crypt;

class Personel extends Model
{
    use SoftDeletes;

    protected $table = 'personels';

    protected $fillable = [
        'company_id',
        'first_name',
        'last_name',
        'email',
        'phone',
        'national_id_enc',
        'national_id_hash',
        'birth_date',
        'gender',
        'blood_type',
        'position_id',
        'department_id',
        'salary',
        'currency',
        'hire_date',
        'termination_date',
        'status',
        'attributes',
        'is_active',
        'user_id',
        'created_by',
        'updated_by',
    ];

    protected $casts = [
        'birth_date'       => 'date',
        'hire_date'        => 'date',
        'termination_date' => 'date',
        'is_active'        => 'boolean',
        'salary'           => 'decimal:2',
        'attributes'       => 'array',
    ];

    protected $hidden = [
        'national_id_enc',
        'national_id_hash',
    ];

    // PII: Şifreli ulusal kimlik numarasını ayarla
    public function setNationalIdAttribute(string $value): void
    {
        $this->attributes['national_id_enc'] = Crypt::encryptString($value);
        $this->attributes['national_id_hash'] = hash('sha256', $value);
    }

    // PII: Şifreli ulusal kimlik numarasını çöz
    public function getNationalIdAttribute(): ?string
    {
        if (empty($this->attributes['national_id_enc'])) {
            return null;
        }
        return Crypt::decryptString($this->attributes['national_id_enc']);
    }

    // Sadece son 4 haneyi göster (UI maskeleme)
    public function getMaskedNationalIdAttribute(): string
    {
        $plain = $this->national_id;
        if (!$plain) return '****';
        return str_repeat('*', strlen($plain) - 4) . substr($plain, -4);
    }

    public function getFullNameAttribute(): string
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    // Relations
    public function company(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Company::class);
    }

    public function department(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Department::class);
    }

    public function position(): BelongsTo
    {
        return $this->belongsTo(\App\Models\Position::class);
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'created_by');
    }

    public function updatedBy(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'updated_by');
    }

    public function leaveRequests(): HasMany
    {
        return $this->hasMany(\App\Models\LeaveRequest::class);
    }

    public function timeRecords(): HasMany
    {
        return $this->hasMany(\App\Models\TimeRecord::class);
    }

    public function documents(): HasMany
    {
        return $this->hasMany(\App\Models\PersonelDocument::class);
    }

    // Scope: aktif personeller
    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    // Scope: şirkete göre filtrele
    public function scopeForCompany($query, int $companyId)
    {
        return $query->where('company_id', $companyId);
    }
}
