{{-- Generated by Cursor prompt — module: Departman — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'Departmanlar')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <a href="{{ route('admin.companies.index') }}" class="hover:text-[#02E0FB]">Şirket Yapısı</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">Departmanlar</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">Departmanlar</h1>
        <p class="text-sm text-gray-500 mt-0.5">Şirket departman yapısını yönetin.</p>
    </div>
    <div class="flex items-center gap-2">
        <button onclick="toggleView()" id="viewToggleBtn"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-200 rounded-lg hover:bg-gray-50 transition-colors">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 10h18M3 6h18M3 14h18M3 18h18"/></svg>
            Ağaç Görünümü
        </button>
        @can('department.create')
        <button onclick="openCreateDeptModal()"
            class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
            Yeni Departman
        </button>
        @endcan
    </div>
@endsection

@section('content')

{{-- Filtreler --}}
<div class="bg-white rounded-xl border border-gray-100 p-4 mb-4 shadow-sm">
    <div class="grid grid-cols-1 md:grid-cols-4 gap-3">
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Arama</label>
            <input type="text" id="searchDept" placeholder="Departman adı veya kod..." class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
        </div>
        <div>
            <label class="block text-xs font-medium text-gray-500 mb-1">Üst Departman</label>
            <select id="filterParent" class="w-full text-sm border border-gray-200 rounded-lg px-3 py-2 focus:outline-none focus:border-[#02E0FB]">
                <option value="">Tümü</option>
                <option value="root">Yalnızca Kök</option>
            </select>
        </div>
        <div class="flex items-end gap-2 md:col-span-2">
            <button onclick="loadDepartments()" class="flex-1 px-4 py-2 text-sm bg-gray-100 hover:bg-gray-200 text-gray-700 rounded-lg transition-colors">Filtrele</button>
            <label class="flex items-center gap-2 cursor-pointer">
                <input type="checkbox" id="activeOnly" class="w-4 h-4 rounded text-[#02E0FB]" onchange="loadDepartments()">
                <span class="text-sm text-gray-600">Yalnızca Aktif</span>
            </label>
        </div>
    </div>
</div>

{{-- Liste Görünümü --}}
<div id="listView" class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Departman</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Üst Departman</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Yönetici</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase tracking-wider">Personel</th>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase tracking-wider">Durum</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase tracking-wider">İşlemler</th>
                </tr>
            </thead>
            <tbody id="deptTableBody" class="divide-y divide-gray-50">
                <tr><td colspan="6" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
            </tbody>
        </table>
    </div>
    <div class="px-4 py-3 border-t border-gray-100 flex flex-col sm:flex-row items-center justify-between gap-2">
        <div class="text-xs text-gray-500" id="deptTableInfo">—</div>
        <div id="deptPagination" class="flex gap-1"></div>
    </div>
</div>

{{-- Ağaç Görünümü (gizli başlangıçta) --}}
<div id="treeView" class="hidden bg-white rounded-xl border border-gray-100 shadow-sm p-5">
    <h3 class="font-semibold text-gray-800 mb-4">Organizasyon Ağacı</h3>
    <div id="orgTreeContainer" class="font-mono text-sm"></div>
</div>

@endsection

@push('scripts')
<script>
const DEPT_URLS = {
    list:    '{{ route("admin.departments.index") }}',
    tree:    '{{ route("admin.departments.tree") }}',
    create:  '{{ route("admin.departments.create") }}',
    store:   '{{ route("admin.departments.store") }}',
    edit:    id => `/admin/departments/${id}/edit`,
    update:  id => `/admin/departments/${id}`,
    destroy: id => `/admin/departments/${id}`,
    assign:  id => `/admin/departments/${id}/assign-personel`,
};

let isTreeView = false;

document.addEventListener('DOMContentLoaded', () => {
    loadDepartments();
    loadParentDepartments();
});

function loadParentDepartments() {
    axios.get(DEPT_URLS.list, { params: { per_page: 1000, active_only: true } }).then(res => {
        const sel = document.getElementById('filterParent');
        res.data.data.forEach(d => {
            const opt = document.createElement('option');
            opt.value = d.id;
            opt.textContent = d.name;
            sel.appendChild(opt);
        });
    });
}

function loadDepartments(page = 1) {
    const params = {
        page,
        search:    document.getElementById('searchDept').value,
        parent_id: document.getElementById('filterParent').value,
        active_only: document.getElementById('activeOnly').checked,
        per_page: 20,
    };
    axios.get(DEPT_URLS.list, { params }).then(res => renderDeptTable(res.data));
}

function renderDeptTable(data) {
    const tbody = document.getElementById('deptTableBody');
    if (!data.data.length) {
        tbody.innerHTML = `<tr><td colspan="6" class="px-4 py-8 text-center text-gray-400 text-sm">Kayıt bulunamadı</td></tr>`;
        return;
    }
    tbody.innerHTML = data.data.map(d => `
        <tr class="hover:bg-gray-50 transition-colors">
            <td class="px-4 py-3">
                <div>
                    <p class="font-medium text-gray-800">${d.name}</p>
                    ${d.code ? `<p class="text-xs text-gray-400 font-mono">${d.code}</p>` : ''}
                </div>
            </td>
            <td class="px-4 py-3 text-gray-600 text-sm">${d.parent?.name || '<span class="text-gray-300">—</span>'}</td>
            <td class="px-4 py-3 text-gray-600 text-sm">${d.manager ? `${d.manager.first_name} ${d.manager.last_name}` : '<span class="text-gray-300">—</span>'}</td>
            <td class="px-4 py-3 text-center">
                <span class="inline-flex items-center justify-center w-8 h-8 rounded-full bg-[#02E0FB]/10 text-[#02E0FB] text-xs font-bold">${d.personels_count ?? 0}</span>
            </td>
            <td class="px-4 py-3">
                <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${d.is_active ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'}">
                    ${d.is_active ? 'Aktif' : 'Pasif'}
                </span>
            </td>
            <td class="px-4 py-3">
                <div class="flex items-center justify-end gap-1">
                    <button onclick="openEditDeptModal(${d.id})" class="p-1.5 text-gray-400 hover:text-amber-500 hover:bg-amber-50 rounded-lg" title="Düzenle">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                    </button>
                    <button onclick="confirmDelete(DEPT_URLS.destroy(${d.id}), () => loadDepartments())" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg" title="Sil">
                        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                    </button>
                </div>
            </td>
        </tr>`).join('');

    document.getElementById('deptTableInfo').textContent = `${data.total} kayıttan ${data.data.length} gösteriliyor`;
}

function toggleView() {
    isTreeView = !isTreeView;
    document.getElementById('listView').classList.toggle('hidden', isTreeView);
    document.getElementById('treeView').classList.toggle('hidden', !isTreeView);
    document.getElementById('viewToggleBtn').textContent = isTreeView ? '📋 Liste Görünümü' : '🌲 Ağaç Görünümü';
    if (isTreeView) loadOrgTree();
}

function loadOrgTree() {
    axios.get(DEPT_URLS.tree).then(res => {
        const container = document.getElementById('orgTreeContainer');
        container.innerHTML = renderTree(res.data.data, 0);
    });
}

function renderTree(nodes, depth) {
    return nodes.map(node => {
        const indent = '  '.repeat(depth);
        const icon = node.children?.length ? '📁' : '📂';
        let html = `<div class="py-1 hover:bg-gray-50 px-2 rounded" style="padding-left: ${depth * 20 + 8}px">
            <span class="mr-2">${icon}</span>
            <span class="font-medium text-gray-800">${node.name}</span>
            <span class="ml-2 text-xs text-gray-400">(${node.personels_count ?? 0} personel)</span>
            <button onclick="openEditDeptModal(${node.id})" class="ml-2 text-xs text-[#02E0FB] hover:underline">düzenle</button>
        </div>`;
        if (node.all_children?.length) {
            html += renderTree(node.all_children, depth + 1);
        }
        return html;
    }).join('');
}

function openCreateDeptModal() {
    axios.get(DEPT_URLS.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni Departman Ekle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitDeptForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Kaydet</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function openEditDeptModal(id) {
    axios.get(DEPT_URLS.edit(id)).then(res => {
        document.getElementById('modalTitle').textContent = 'Departmanı Düzenle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitDeptForm('${DEPT_URLS.update(id)}','PUT')" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Güncelle</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function submitDeptForm(url = DEPT_URLS.store, method = 'POST') {
    const form = document.getElementById('deptForm');
    const data = Object.fromEntries(new FormData(form).entries());
    axios({ method, url, data }).then(res => {
        document.getElementById('globalModal').classList.add('hidden');
        toast('success', res.data.message);
        loadDepartments();
        if (isTreeView) loadOrgTree();
    });
}
</script>
@endpush
