<?php
// Generated by Cursor prompt — module: Finans — date: 2026-03-15

namespace App\Modules\Finans\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreAdvanceRequest extends FormRequest
{
    public function authorize(): bool { return true; }

    public function rules(): array
    {
        return [
            'personel_id'    => 'required|exists:personels,id',
            'amount'         => 'required|numeric|min:1|max:9999999',
            'currency'       => 'nullable|string|size:3',
            'reason'         => 'required|string|max:1000',
            'repayment_plan' => 'nullable|array',
        ];
    }

    public function messages(): array
    {
        return [
            'personel_id.required' => 'Personel seçimi zorunludur.',
            'amount.required'      => 'Avans tutarı zorunludur.',
            'amount.min'           => 'Avans tutarı 0\'dan büyük olmalıdır.',
            'reason.required'      => 'Avans gerekçesi zorunludur.',
        ];
    }
}
