<?php
// Generated by Cursor prompt — module: Envanter — date: 2026-03-15

namespace App\Modules\Envanter\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreAssetRequest extends FormRequest
{
    public function authorize(): bool { return true; }

    public function rules(): array
    {
        return [
            'asset_type_id'    => 'required|exists:asset_types,id',
            'name'             => 'required|string|max:191',
            'serial'           => 'nullable|string|max:100',
            'barcode'          => 'nullable|string|max:100',
            'purchase_date'    => 'nullable|date',
            'warranty_end'     => 'nullable|date|after_or_equal:purchase_date',
            'price'            => 'nullable|numeric|min:0',
            'status'           => 'nullable|in:available,assigned,maintenance,retired',
            'location'         => 'nullable|string|max:191',
            'custom_attributes'=> 'nullable|array',
        ];
    }

    public function messages(): array
    {
        return [
            'asset_type_id.required' => 'Varlık türü seçimi zorunludur.',
            'name.required'          => 'Varlık adı zorunludur.',
        ];
    }
}
