<?php
// Generated by Cursor prompt — Trait: NotifiesManagers — date: 2026-03-15

namespace App\Traits;

use App\Models\User;
use Illuminate\Support\Facades\DB;

trait NotifiesManagers
{
    /**
     * Şirketteki tüm yöneticilere (hr_manager + company_admin + super_admin) bildirim gönder.
     * $notification: hazır Notification nesnesi
     */
    protected function notifyManagers(int $companyId, object $notification): void
    {
        $managers = User::where('company_id', $companyId)
            ->where('is_active', true)
            ->whereNull('deleted_at')
            ->whereHas('roles', fn ($q) => $q->whereIn('name', ['super_admin', 'company_admin', 'hr_manager', 'manager', 'finance']))
            ->get();

        foreach ($managers as $manager) {
            $manager->notify($notification);
        }
    }

    /**
     * Belirli rollere sahip kullanıcılara bildirim gönder.
     */
    protected function notifyRoles(int $companyId, array $roles, object $notification): void
    {
        $users = User::where('company_id', $companyId)
            ->where('is_active', true)
            ->whereNull('deleted_at')
            ->whereHas('roles', fn ($q) => $q->whereIn('name', $roles))
            ->get();

        foreach ($users as $user) {
            $user->notify($notification);
        }
    }

    /**
     * Belirli permission'a sahip kullanıcılara bildirim gönder.
     */
    protected function notifyByPermission(int $companyId, string $permission, object $notification): void
    {
        $users = User::where('company_id', $companyId)
            ->where('is_active', true)
            ->whereNull('deleted_at')
            ->whereHas('permissions', fn ($q) => $q->where('name', $permission))
            ->orWhereHas('roles.permissions', fn ($q) => $q->where('name', $permission))
            ->get();

        foreach ($users->unique('id') as $user) {
            $user->notify($notification);
        }
    }
}
