<?php
// Generated by Cursor prompt — 1 file = 1 table — date: 2026-03-15

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('companies', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('domain', 100)->nullable()->unique()->index();
            $table->string('tax_number', 20)->nullable();
            $table->string('tax_office', 100)->nullable();
            $table->string('phone', 20)->nullable();
            $table->string('email')->nullable();
            $table->string('address')->nullable();
            $table->string('city', 100)->nullable();
            $table->string('country', 100)->default('TR');
            $table->string('timezone', 100)->default('Europe/Istanbul');
            $table->string('locale', 10)->default('tr');
            $table->string('logo_path')->nullable();
            $table->enum('status', ['active', 'inactive', 'trial', 'suspended'])->default('trial');
            $table->date('trial_ends_at')->nullable();
            $table->json('settings')->nullable();
            $table->unsignedBigInteger('created_by')->nullable();
            $table->timestamps();
            $table->softDeletes();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('companies');
    }
};
