<?php
// Generated by Cursor prompt — PersonelDocumentController — date: 2026-03-15

namespace App\Modules\Personel\Controllers;

use App\Http\Controllers\Controller;
use App\Modules\Personel\Models\Personel;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\DB;

class PersonelDocumentController extends Controller
{
    /** Belge listesi */
    public function index(Personel $personel): JsonResponse
    {
        $this->authorize('personel.view');

        $docs = DB::table('personel_documents')
            ->where('personel_id', $personel->id)
            ->orderByDesc('created_at')
            ->get()
            ->map(fn ($d) => [
                'id'           => $d->id,
                'type'         => $d->type,
                'original_name'=> $d->original_name,
                'file_path'    => $d->file_path,
                'mime'         => $d->mime,
                'file_size'    => $d->file_size,
                'expiry_at'    => $d->expiry_at,
                'is_expired'   => $d->expiry_at && now()->isAfter($d->expiry_at),
                'expiring_soon'=> $d->expiry_at && !now()->isAfter($d->expiry_at) && now()->diffInDays($d->expiry_at) <= 30,
                'created_at'   => $d->created_at,
                'download_url' => route('admin.personel.documents.download', $d->id),
            ]);

        return response()->json(['data' => $docs]);
    }

    /** Belge yükle */
    public function store(Request $request, Personel $personel): JsonResponse
    {
        $this->authorize('personel.update');

        $request->validate([
            'file'      => 'required|file|max:10240|mimes:pdf,jpg,jpeg,png,docx,doc',
            'type'      => 'required|string|max:100',
            'expiry_at' => 'nullable|date|after:today',
        ]);

        $file = $request->file('file');
        $path = $file->store("personel-docs/{$personel->company_id}/{$personel->id}", 'local');

        $docId = DB::table('personel_documents')->insertGetId([
            'personel_id'   => $personel->id,
            'type'          => $request->type,
            'file_path'     => $path,
            'original_name' => $file->getClientOriginalName(),
            'mime'          => $file->getMimeType(),
            'file_size'     => $file->getSize(),
            'expiry_at'     => $request->expiry_at,
            'created_by'    => auth()->id(),
            'created_at'    => now(),
            'updated_at'    => now(),
        ]);

        DB::table('audit_logs')->insert([
            'user_id'    => auth()->id(),
            'company_id' => $personel->company_id,
            'action'     => 'personel_document.uploaded',
            'model_type' => 'PersonelDocument',
            'model_id'   => $docId,
            'changes'    => json_encode(['type' => $request->type, 'personel_id' => $personel->id]),
            'ip'         => request()->ip(),
            'created_at' => now(),
        ]);

        return response()->json([
            'success' => true,
            'message' => 'Belge başarıyla yüklendi.',
            'data'    => ['id' => $docId, 'type' => $request->type],
        ], 201);
    }

    /** Belge indir (signed URL / stream) */
    public function download(int $id)
    {
        $this->authorize('personel.view');

        $doc = DB::table('personel_documents')->find($id);

        if (!$doc || !Storage::disk('local')->exists($doc->file_path)) {
            abort(404, 'Belge bulunamadı.');
        }

        return Storage::disk('local')->download(
            $doc->file_path,
            $doc->original_name ?? basename($doc->file_path),
            ['Content-Type' => $doc->mime ?? 'application/octet-stream']
        );
    }

    /** Belge sil */
    public function destroy(int $id): JsonResponse
    {
        $this->authorize('personel.update');

        $doc = DB::table('personel_documents')->find($id);
        if (!$doc) {
            return response()->json(['success' => false, 'message' => 'Belge bulunamadı.'], 404);
        }

        Storage::disk('local')->delete($doc->file_path);
        DB::table('personel_documents')->where('id', $id)->delete();

        return response()->json(['success' => true, 'message' => 'Belge silindi.']);
    }
}
