<?php
// Generated by Cursor prompt — module: Surec (ProcessTemplate) — date: 2026-03-15

namespace App\Modules\Surec\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class ProcessTemplate extends Model
{
    use SoftDeletes;

    protected $table = 'process_templates';

    protected $fillable = [
        'company_id', 'name', 'type', 'description', 'steps', 'is_active', 'created_by',
    ];

    protected $casts = [
        'steps'     => 'array',
        'is_active' => 'boolean',
    ];

    const TYPE_ONBOARDING  = 'onboarding';
    const TYPE_OFFBOARDING = 'offboarding';
    const TYPE_CUSTOM      = 'custom';

    public function company(): BelongsTo
    {
        return $this->belongsTo(\App\Modules\Sirket\Models\Company::class);
    }

    public function instances(): HasMany
    {
        return $this->hasMany(ProcessInstance::class, 'template_id');
    }

    public function getStepsCountAttribute(): int
    {
        return count($this->steps ?? []);
    }

    public function getTypeLabelAttribute(): string
    {
        return match ($this->type) {
            'onboarding'  => 'İşe Giriş',
            'offboarding' => 'İşten Çıkış',
            default       => 'Özel Süreç',
        };
    }

    /** Şablondan yeni süreç örneği başlat */
    public function instantiate(int $personelId, ?int $assignedTo = null, ?string $dueDate = null): ProcessInstance
    {
        return $this->instances()->create([
            'personel_id'    => $personelId,
            'company_id'     => $this->company_id,
            'status'         => 'in_progress',
            'context'        => [],
            'completed_steps'=> [],
            'assigned_to'    => $assignedTo,
            'due_date'       => $dueDate,
            'created_by'     => auth()->id(),
        ]);
    }

    public function scopeForCompany($query, int $companyId)
    {
        return $query->where('company_id', $companyId);
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}
