<?php
// Generated by Cursor prompt — module: Izin (LeaveType) — date: 2026-03-15

namespace App\Modules\Izin\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreLeaveTypeRequest extends FormRequest
{
    public function authorize(): bool { return true; }

    public function rules(): array
    {
        $companyId = auth()->user()->company_id;
        return [
            'name'               => ['required', 'string', 'max:191',
                Rule::unique('leave_types')->where('company_id', $companyId)->whereNull('deleted_at')],
            'paid'               => 'nullable|boolean',
            'max_annual_days'    => 'nullable|numeric|min:0|max:365',
            'requires_approval'  => 'nullable|boolean',
            'is_active'          => 'nullable|boolean',
            'accrual_rule'       => 'nullable|array',
        ];
    }

    public function messages(): array
    {
        return [
            'name.required' => 'İzin türü adı zorunludur.',
            'name.unique'   => 'Bu izin türü adı zaten kullanılıyor.',
        ];
    }
}
