<?php
// Generated by Cursor prompt — module: Sirket (Company) — date: 2026-03-15

namespace App\Modules\Sirket\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreCompanyRequest extends FormRequest
{
    public function authorize(): bool { return true; }

    public function rules(): array
    {
        return [
            'name'       => 'required|string|max:191',
            'domain'     => ['nullable', 'string', 'max:100', Rule::unique('companies', 'domain')->whereNull('deleted_at')],
            'tax_number' => 'nullable|string|max:20',
            'tax_office' => 'nullable|string|max:100',
            'phone'      => 'nullable|string|max:20',
            'email'      => 'nullable|email|max:191',
            'address'    => 'nullable|string|max:255',
            'city'       => 'nullable|string|max:100',
            'country'    => 'nullable|string|max:100',
            'timezone'   => 'nullable|string|max:100',
            'locale'     => 'nullable|string|max:10',
            'status'     => 'nullable|in:active,inactive,trial,suspended',
            'settings'   => 'nullable|array',
            'settings.working_days'   => 'nullable|array',
            'settings.work_start'     => 'nullable|date_format:H:i',
            'settings.work_end'       => 'nullable|date_format:H:i',
        ];
    }

    public function messages(): array
    {
        return [
            'name.required'   => 'Şirket adı zorunludur.',
            'domain.unique'   => 'Bu alan adı zaten kullanılmaktadır.',
            'email.email'     => 'Geçerli bir e-posta adresi giriniz.',
        ];
    }
}
