<?php
// Generated by Cursor prompt — module: Sirket (Position) — date: 2026-03-15

namespace App\Modules\Sirket\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StorePositionRequest extends FormRequest
{
    public function authorize(): bool { return true; }

    public function rules(): array
    {
        $companyId = auth()->user()->company_id;
        return [
            'title'        => ['required', 'string', 'max:191',
                Rule::unique('positions')->where('company_id', $companyId)->whereNull('deleted_at')],
            'code'         => 'nullable|string|max:50',
            'salary_grade' => 'nullable|string|max:20',
            'level'        => 'nullable|integer|min:1|max:99',
            'description'  => 'nullable|string|max:1000',
            'is_active'    => 'nullable|boolean',
        ];
    }

    public function messages(): array
    {
        return [
            'title.required' => 'Pozisyon adı zorunludur.',
            'title.unique'   => 'Bu pozisyon adı şirketinizde zaten mevcut.',
        ];
    }
}
