<?php
// Generated by Cursor prompt — module: Sirket (Department) — date: 2026-03-15

namespace App\Modules\Sirket\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StoreDepartmentRequest extends FormRequest
{
    public function authorize(): bool { return true; }

    public function rules(): array
    {
        $companyId = auth()->user()->company_id;
        return [
            'name'                   => ['required', 'string', 'max:191',
                Rule::unique('departments')->where('company_id', $companyId)->whereNull('deleted_at')],
            'code'                   => 'nullable|string|max:50',
            'parent_department_id'   => 'nullable|exists:departments,id',
            'manager_id'             => 'nullable|exists:personels,id',
            'is_active'              => 'nullable|boolean',
            'metadata'               => 'nullable|array',
        ];
    }

    public function messages(): array
    {
        return [
            'name.required' => 'Departman adı zorunludur.',
            'name.unique'   => 'Bu departman adı şirketinizde zaten mevcut.',
        ];
    }
}
