<?php
// Generated by Cursor prompt — Mailable: LeaveApprovedMail — date: 2026-03-15

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Mail\Mailables\Content;
use Illuminate\Mail\Mailables\Envelope;
use Illuminate\Queue\SerializesModels;

class LeaveApprovedMail extends Mailable implements ShouldQueue
{
    use Queueable, SerializesModels;

    public function __construct(
        public readonly string $personelName,
        public readonly string $leaveTypeName,
        public readonly string $startDate,
        public readonly string $endDate,
        public readonly float  $totalDays,
        public readonly string $approverName,
        public readonly ?string $note = null,
    ) {}

    public function envelope(): Envelope
    {
        return new Envelope(
            subject: '✅ İzin Talebiniz Onaylandı — MİYSOFT PTS',
        );
    }

    public function content(): Content
    {
        return new Content(
            view: 'emails.leave-approved',
        );
    }
}
