{{-- Generated by Cursor prompt — module: İzin Türleri — date: 2026-03-15 --}}
<form id="leaveTypeForm" class="space-y-4" novalidate>
    @csrf

    {{-- Ad --}}
    <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">İzin Türü Adı <span class="text-red-500">*</span></label>
        <input type="text" name="name" value="{{ $leaveType->name ?? '' }}" required
            class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
            placeholder="Örn: Yıllık İzin">
    </div>

    {{-- Max Yıllık Gün --}}
    <div>
        <label class="block text-sm font-medium text-gray-700 mb-1">Maksimum Yıllık Gün</label>
        <input type="number" name="max_annual_days" value="{{ $leaveType->max_annual_days ?? '' }}" min="0" max="365" step="0.5"
            class="w-full px-3 py-2 text-sm border border-gray-200 rounded-lg focus:outline-none focus:border-[#02E0FB] focus:ring-1 focus:ring-[#02E0FB]"
            placeholder="Örn: 14">
        <p class="mt-1 text-xs text-gray-400">Boş bırakılırsa sınırsız olarak işlenir.</p>
    </div>

    {{-- Toggle Seçenekleri --}}
    <div class="space-y-3 pt-1">

        {{-- Ücretli --}}
        <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
            <div>
                <p class="text-sm font-medium text-gray-700">Ücretli İzin</p>
                <p class="text-xs text-gray-400">Çalışan bu izinde maaş almaya devam eder.</p>
            </div>
            <label class="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" name="paid" class="sr-only peer"
                    {{ !isset($leaveType) || $leaveType->paid ? 'checked' : '' }}>
                <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-checked:bg-[#02E0FB] transition-colors after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
            </label>
        </div>

        {{-- Onay Gerekli --}}
        <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
            <div>
                <p class="text-sm font-medium text-gray-700">Yönetici Onayı Gerekli</p>
                <p class="text-xs text-gray-400">Kapalıysa talep otomatik onaylanır.</p>
            </div>
            <label class="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" name="requires_approval" class="sr-only peer"
                    {{ !isset($leaveType) || $leaveType->requires_approval ? 'checked' : '' }}>
                <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-checked:bg-[#FA6001] transition-colors after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
            </label>
        </div>

        {{-- Aktif --}}
        <div class="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
            <div>
                <p class="text-sm font-medium text-gray-700">Aktif</p>
                <p class="text-xs text-gray-400">Pasif türler yeni talepte gösterilmez.</p>
            </div>
            <label class="relative inline-flex items-center cursor-pointer">
                <input type="checkbox" name="is_active" class="sr-only peer"
                    {{ !isset($leaveType) || $leaveType->is_active ? 'checked' : '' }}>
                <div class="w-11 h-6 bg-gray-200 rounded-full peer peer-checked:bg-green-500 transition-colors after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:after:translate-x-full"></div>
            </label>
        </div>
    </div>
</form>
