{{-- Generated by Cursor prompt — module: İzin Türleri — date: 2026-03-15 --}}
@extends('layouts.app')
@section('title', 'İzin Türleri')

@section('breadcrumbs')
    <a href="{{ route('admin.dashboard') }}" class="hover:text-[#02E0FB]">Dashboard</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <a href="{{ route('admin.leave.index') }}" class="hover:text-[#02E0FB]">İzin Yönetimi</a>
    <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7"/></svg>
    <span class="text-gray-800 font-medium">İzin Türleri</span>
@endsection

@section('page_header')
    <div>
        <h1 class="text-2xl font-bold text-gray-900">İzin Türleri</h1>
        <p class="text-sm text-gray-500 mt-0.5">Şirketinizin izin türlerini tanımlayın.</p>
    </div>
    @can('leave.manage')
    <button onclick="openCreateTypeModal()"
        class="flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-[#02E0FB] rounded-lg hover:bg-cyan-400 transition-colors shadow-sm">
        <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4"/></svg>
        Yeni İzin Türü
    </button>
    @endcan
@endsection

@section('content')

<div class="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
        <table class="w-full text-sm">
            <thead class="bg-gray-50 border-b border-gray-100">
                <tr>
                    <th class="px-4 py-3 text-left text-xs font-semibold text-gray-500 uppercase">İzin Türü</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Ücretli</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Max Yıllık Gün</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Onay Gerekli</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Kullanım Sayısı</th>
                    <th class="px-4 py-3 text-center text-xs font-semibold text-gray-500 uppercase">Durum</th>
                    <th class="px-4 py-3 text-right text-xs font-semibold text-gray-500 uppercase">İşlemler</th>
                </tr>
            </thead>
            <tbody id="leaveTypesBody" class="divide-y divide-gray-50">
                <tr><td colspan="7" class="px-4 py-8 text-center text-gray-400">Yükleniyor...</td></tr>
            </tbody>
        </table>
    </div>
</div>

@endsection

@push('scripts')
<script>
const LT_URLS = {
    list:    '{{ route("admin.leave.types.index") }}',
    create:  '{{ route("admin.leave.types.create") }}',
    store:   '{{ route("admin.leave.types.store") }}',
    edit:    id => `/admin/leave/types/${id}/edit`,
    update:  id => `/admin/leave/types/${id}`,
    destroy: id => `/admin/leave/types/${id}`,
};

document.addEventListener('DOMContentLoaded', loadLeaveTypes);

function loadLeaveTypes() {
    axios.get(LT_URLS.list, { params: { per_page: 50 } }).then(res => {
        const tbody = document.getElementById('leaveTypesBody');
        if (!res.data.data.length) {
            tbody.innerHTML = `<tr><td colspan="7" class="px-4 py-8 text-center text-gray-400 text-sm">Henüz izin türü tanımlanmamış</td></tr>`;
            return;
        }
        tbody.innerHTML = res.data.data.map(t => `
            <tr class="hover:bg-gray-50 transition-colors">
                <td class="px-4 py-3">
                    <div class="flex items-center gap-2">
                        <div class="w-2.5 h-2.5 rounded-full ${t.paid ? 'bg-green-400' : 'bg-gray-300'}"></div>
                        <span class="font-medium text-gray-800">${t.name}</span>
                    </div>
                </td>
                <td class="px-4 py-3 text-center">
                    <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${t.paid ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-600'}">
                        ${t.paid ? 'Evet' : 'Hayır'}
                    </span>
                </td>
                <td class="px-4 py-3 text-center text-gray-700 font-medium">${t.max_annual_days || '—'}</td>
                <td class="px-4 py-3 text-center">
                    <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${t.requires_approval ? 'bg-orange-100 text-orange-700' : 'bg-blue-100 text-blue-700'}">
                        ${t.requires_approval ? 'Gerekli' : 'Otomatik'}
                    </span>
                </td>
                <td class="px-4 py-3 text-center">
                    <span class="text-gray-600">${t.leave_requests_count ?? 0}</span>
                </td>
                <td class="px-4 py-3 text-center">
                    <span class="inline-flex items-center px-2 py-0.5 rounded-full text-xs font-medium ${t.is_active ? 'bg-green-100 text-green-700' : 'bg-gray-100 text-gray-500'}">
                        ${t.is_active ? 'Aktif' : 'Pasif'}
                    </span>
                </td>
                <td class="px-4 py-3">
                    <div class="flex items-center justify-end gap-1">
                        <button onclick="openEditTypeModal(${t.id})" class="p-1.5 text-gray-400 hover:text-amber-500 hover:bg-amber-50 rounded-lg" title="Düzenle">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"/></svg>
                        </button>
                        <button onclick="confirmDelete(LT_URLS.destroy(${t.id}), loadLeaveTypes)" class="p-1.5 text-gray-400 hover:text-red-500 hover:bg-red-50 rounded-lg" title="Sil">
                            <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"/></svg>
                        </button>
                    </div>
                </td>
            </tr>`).join('');
    });
}

function openCreateTypeModal() {
    axios.get(LT_URLS.create).then(res => {
        document.getElementById('modalTitle').textContent = 'Yeni İzin Türü';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitLeaveTypeForm()" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Kaydet</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function openEditTypeModal(id) {
    axios.get(LT_URLS.edit(id)).then(res => {
        document.getElementById('modalTitle').textContent = 'İzin Türünü Düzenle';
        document.getElementById('modalBody').innerHTML = res.data.html;
        document.getElementById('modalFooter').innerHTML = `
            <button onclick="document.getElementById('globalModal').classList.add('hidden')" class="px-4 py-2 text-sm text-gray-600 hover:bg-gray-100 rounded-lg">İptal</button>
            <button onclick="submitLeaveTypeForm('${LT_URLS.update(id)}','PUT')" class="px-4 py-2 text-sm text-white bg-[#02E0FB] hover:bg-cyan-400 rounded-lg font-medium">Güncelle</button>`;
        document.getElementById('globalModal').classList.remove('hidden');
    });
}

function submitLeaveTypeForm(url = LT_URLS.store, method = 'POST') {
    const form = document.getElementById('leaveTypeForm');
    const data = Object.fromEntries(new FormData(form).entries());
    data.paid = form.querySelector('[name="paid"]')?.checked ? 1 : 0;
    data.requires_approval = form.querySelector('[name="requires_approval"]')?.checked ? 1 : 0;
    data.is_active = form.querySelector('[name="is_active"]')?.checked ? 1 : 0;
    axios({ method, url, data }).then(res => {
        document.getElementById('globalModal').classList.add('hidden');
        toast('success', res.data.message);
        loadLeaveTypes();
    });
}
</script>
@endpush
