<?php
// Generated by Cursor prompt — MİYSOFT PTS — date: 2026-03-15

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Department extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'company_id', 'parent_department_id', 'name',
        'code', 'manager_id', 'metadata', 'is_active', 'created_by',
    ];

    protected $casts = [
        'is_active' => 'boolean',
        'metadata'  => 'array',
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class);
    }

    public function parent(): BelongsTo
    {
        return $this->belongsTo(Department::class, 'parent_department_id');
    }

    public function children(): HasMany
    {
        return $this->hasMany(Department::class, 'parent_department_id');
    }

    public function manager(): BelongsTo
    {
        return $this->belongsTo(\App\Modules\Personel\Models\Personel::class, 'manager_id');
    }

    public function personels(): HasMany
    {
        return $this->hasMany(\App\Modules\Personel\Models\Personel::class);
    }

    public function scopeForCompany($query, int $companyId)
    {
        return $query->where('company_id', $companyId);
    }

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }
}
