<?php
// Generated by Cursor prompt — Admin PermissionController — date: 2026-03-15

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\JsonResponse;
use Spatie\Permission\Models\Permission;

class PermissionController extends Controller
{
    /** Tüm izinleri modüle göre gruplu getir */
    public function index(): JsonResponse
    {
        $this->authorize('permission.view');

        $permissions = Permission::orderBy('name')->get()
            ->map(fn ($p) => [
                'id'     => $p->id,
                'name'   => $p->name,
                'module' => explode('.', $p->name)[0] ?? 'genel',
                'action' => explode('.', $p->name)[1] ?? $p->name,
            ]);

        return response()->json(['data' => $permissions]);
    }
}
