<?php
// Generated by Cursor prompt — Admin RoleController (Production Ready) — date: 2026-03-15

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\JsonResponse;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use App\Models\User;

class RoleController extends Controller
{
    public function indexView()
    {
        $this->authorize('role.view');
        return view('admin.roles.index');
    }

    /** Tüm rolleri listele (user sayısı ile) */
    public function index(): JsonResponse
    {
        $this->authorize('role.view');

        $roles = Role::withCount('users')->orderBy('name')->get();

        return response()->json(['data' => $roles]);
    }

    /** Yeni rol oluştur */
    public function store(Request $request): JsonResponse
    {
        $this->authorize('role.manage');

        $data = $request->validate([
            'name'        => 'required|string|max:100|unique:roles,name|regex:/^[a-z_]+$/',
            'description' => 'nullable|string|max:191',
        ]);

        $role = Role::create(['name' => $data['name'], 'guard_name' => 'web']);

        return response()->json(['success' => true, 'message' => 'Rol oluşturuldu.', 'data' => $role], 201);
    }

    /** Rolü sil */
    public function destroy(Role $role): JsonResponse
    {
        $this->authorize('role.manage');

        // Sistem rollerini koruma
        $systemRoles = ['super_admin', 'company_admin', 'hr_manager', 'manager', 'employee'];
        if (in_array($role->name, $systemRoles)) {
            return response()->json(['success' => false, 'message' => 'Sistem rolleri silinemez.'], 422);
        }

        if ($role->users()->count() > 0) {
            return response()->json(['success' => false, 'message' => 'Kullanıcısı olan rol silinemez.'], 422);
        }

        $role->delete();
        return response()->json(['success' => true, 'message' => 'Rol silindi.']);
    }

    /** Rolün mevcut izinlerini getir */
    public function permissions(Role $role): JsonResponse
    {
        $this->authorize('role.view');
        return response()->json([
            'role'           => $role,
            'permission_ids' => $role->permissions()->pluck('id'),
        ]);
    }

    /** Rol izinlerini senkronize et */
    public function syncPermissions(Request $request, Role $role): JsonResponse
    {
        $this->authorize('role.manage');

        $request->validate([
            'permission_ids'   => 'required|array',
            'permission_ids.*' => 'integer|exists:permissions,id',
        ]);

        $permissions = Permission::whereIn('id', $request->permission_ids)->get();
        $role->syncPermissions($permissions);

        // Permission cache temizle
        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        return response()->json([
            'success' => true,
            'message' => "{$role->name} rolüne {$permissions->count()} izin atandı.",
        ]);
    }

    /** Kullanıcıya rol ata */
    public function assignToUser(Request $request): JsonResponse
    {
        $this->authorize('role.manage');

        $data = $request->validate([
            'user_id' => 'required|exists:users,id',
            'role_id' => 'required|exists:roles,id',
        ]);

        $user = User::findOrFail($data['user_id']);
        $role = Role::findOrFail($data['role_id']);

        $user->assignRole($role);

        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        return response()->json([
            'success' => true,
            'message' => "{$user->name} kullanıcısına {$role->name} rolü atandı.",
        ]);
    }

    /** Kullanıcıdan rol kaldır */
    public function revokeFromUser(Request $request): JsonResponse
    {
        $this->authorize('role.manage');

        $data = $request->validate([
            'user_id' => 'required|exists:users,id',
            'role_id' => 'required|exists:roles,id',
        ]);

        $user = User::findOrFail($data['user_id']);
        $role = Role::findOrFail($data['role_id']);
        $user->removeRole($role);

        app()[\Spatie\Permission\PermissionRegistrar::class]->forgetCachedPermissions();

        return response()->json(['success' => true, 'message' => 'Rol kaldırıldı.']);
    }

    /** Tüm kullanıcıları rollerle birlikte listele */
    public function users(): JsonResponse
    {
        $this->authorize('role.view');

        $companyId = auth()->user()->company_id;
        $users = User::with('roles')
            ->where('company_id', $companyId)
            ->orderBy('name')
            ->get()
            ->map(fn($u) => [
                'id'    => $u->id,
                'name'  => $u->name,
                'email' => $u->email,
                'roles' => $u->getRoleNames(),
            ]);

        return response()->json(['data' => $users]);
    }

    /** Rolün kullanıcılarını getir */
    public function usersByRole(Role $role): JsonResponse
    {
        $this->authorize('role.view');

        $companyId = auth()->user()->company_id;
        $users = User::where('company_id', $companyId)
            ->role($role->name)
            ->orderBy('name')
            ->get(['id', 'name', 'email']);

        return response()->json(['data' => $users]);
    }
}
