<?php
// Generated by Cursor prompt — module: Frontend (Public Site) — date: 2026-03-15

namespace App\Http\Controllers\Public;

use App\Http\Controllers\Controller;
use App\Models\Company;
use App\Models\User;
use App\Modules\CMS\Models\Content;
use App\Modules\CMS\Models\Blog;
use App\Modules\CMS\Models\BlogCategory;
use App\Modules\CMS\Models\PartnerLogo;
use App\Modules\Abonelik\Models\SubscriptionPlan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;

class FrontendController extends Controller
{
    public function index()
    {
        $hero      = Content::section('hero');
        $features  = Content::section('features');
        $partners  = PartnerLogo::active()->get();
        $plans     = SubscriptionPlan::active()->get();
        $latestPosts = Blog::with('category')
            ->published()
            ->latest()
            ->take(3)
            ->get();

        $how_it_works = [
            ['icon' => '📝', 'step' => '01', 'title' => 'Ücretsiz Kaydol', 'desc' => '5 dakikada hesabınızı oluşturun. Kredi kartı gerekmez.'],
            ['icon' => '🏢', 'step' => '02', 'title' => 'Şirketinizi Kurun', 'desc' => 'Departmanlarınızı ve personellerinizi sisteme ekleyin.'],
            ['icon' => '⚙️', 'step' => '03', 'title' => 'Modülleri Yapılandırın', 'desc' => 'İhtiyacınıza göre izin, puantaj ve diğer modülleri aktifleştirin.'],
            ['icon' => '🚀', 'step' => '04', 'title' => 'Kullanmaya Başlayın', 'desc' => 'Tüm ekibinizle verimliliği artırmaya hemen başlayın.'],
        ];

        $trust_badges = [
            ['icon' => '🔒', 'title' => 'SSL Güvenli', 'desc' => '256-bit şifreleme'],
            ['icon' => '☁️', 'title' => 'Bulut Tabanlı', 'desc' => '99.9% uptime garantisi'],
            ['icon' => '🛡️', 'title' => 'KVKK Uyumlu', 'desc' => 'Verileriniz güvende'],
            ['icon' => '📊', 'title' => 'Anlık Raporlar', 'desc' => 'Gerçek zamanlı analitik'],
        ];

        $testimonials = [
            ['name' => 'Ahmet Kaya', 'role' => 'HR Müdürü, TeknoFirm A.Ş.', 'quote' => 'MİYSOFT PTS ile personel yönetimimiz %60 daha verimli hale geldi. Artık izin onayları saniyeler içinde yapılıyor.', 'avatar' => 'AK'],
            ['name' => 'Zeynep Arslan', 'role' => 'Genel Müdür, Arslan Holding', 'quote' => 'Tüm modüllerin tek bir platformda olması inanılmaz kolaylık sağlıyor. Raporlar artık tek tuşla hazır.', 'avatar' => 'ZA'],
            ['name' => 'Mehmet Yıldız', 'role' => 'IT Direktörü, GlobalTech', 'quote' => 'Kurulum süreci çok hızlıydı. Destek ekibi her aşamada yanımızdaydı. Kesinlikle tavsiye ediyorum.', 'avatar' => 'MY'],
        ];

        return view('frontend.index', compact(
            'hero', 'features', 'partners', 'plans',
            'latestPosts', 'how_it_works', 'trust_badges', 'testimonials'
        ));
    }

    public function about()
    {
        $about = Content::section('about');
        return view('frontend.about', compact('about'));
    }

    public function blog(Request $request)
    {
        $categories = BlogCategory::where('is_active', true)->get();
        $posts = Blog::with('category')
            ->published()
            ->when($request->filled('category'), fn ($q) => $q->whereHas('category', fn ($cq) => $cq->where('slug', $request->category)))
            ->when($request->filled('tag'), fn ($q) => $q->whereJsonContains('tags', $request->tag))
            ->latest()
            ->paginate(9);

        return view('frontend.blog.index', compact('posts', 'categories'));
    }

    public function blogShow(string $slug)
    {
        $post = Blog::with(['category', 'author'])->where('slug', $slug)->published()->firstOrFail();
        $post->increment('views_count');

        $relatedPosts = Blog::with('category')
            ->published()
            ->where('id', '!=', $post->id)
            ->when($post->category_id, fn ($q) => $q->where('category_id', $post->category_id))
            ->latest()
            ->take(3)
            ->get();

        return view('frontend.blog_show', compact('post', 'relatedPosts'));
    }

    public function pricing()
    {
        $plans = SubscriptionPlan::active()->get();
        return view('frontend.pricing', compact('plans'));
    }

    public function contact()
    {
        $contact = Content::section('contact');
        return view('frontend.contact', compact('contact'));
    }

    public function storeContact(Request $request)
    {
        $data = $request->validate([
            'name'    => 'required|string|max:100',
            'email'   => 'required|email',
            'phone'   => 'nullable|string|max:20',
            'company' => 'nullable|string|max:191',
            'message' => 'required|string|max:2000',
            'consent' => 'required|accepted',
        ]);

        // Mail gönder (VARSAYIM: queue ile)
        // Mail::to(config('mail.admin_address'))->queue(new ContactFormMail($data));

        return back()->with('success', 'Mesajınız alındı. En kısa sürede dönüş yapacağız.');
    }

    public function freeTrial()
    {
        $plans = SubscriptionPlan::active()->get();
        return view('frontend.free_trial', compact('plans'));
    }

    public function storeFreeTrial(Request $request)
    {
        $data = $request->validate([
            'name'           => 'required|string|max:100',
            'email'          => 'required|email',
            'password'       => 'required|string|min:8|confirmed',
            'company_name'   => 'required|string|max:191',
            'phone'          => 'nullable|string|max:20',
            'employee_count' => 'nullable|integer|min:1',
            'agree_terms'    => 'required|accepted',
        ]);

        if (User::where('email', $data['email'])->exists()) {
            return back()->withErrors(['email' => 'Bu e-posta zaten kullanımda'])->withInput();
        }

        $company = Company::create([
            'name'         => $data['company_name'],
            'status'       => 'trial',
            'trial_ends_at' => now()->addDays(14),
        ]);

        $user = User::create([
            'name'              => $data['name'],
            'email'             => $data['email'],
            'password'          => Hash::make($data['password']),
            'company_id'        => $company->id,
            'is_active'         => true,
            'email_verified_at' => now(), // Free trial: immediate access
        ]);

        $isFirstUser = User::count() === 1;
        if ($isFirstUser && \Spatie\Permission\Models\Role::where('name', 'super_admin')->exists()) {
            $user->assignRole('super_admin');
        } else {
            $user->assignRole('company_admin');
        }
        Auth::login($user);

        return redirect()->route('admin.dashboard')
            ->with('success', '14 günlük ücretsiz denemeniz başlatıldı!');
    }
}
