<?php
// Generated by Cursor prompt — module: Personel — date: 2026-03-15

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class ExportPersonelExcelJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $tries = 3;
    public int $timeout = 300;

    public function __construct(
        public readonly int   $companyId,
        public readonly int   $userId,
        public readonly array $filters = []
    ) {}

    public function handle(): void
    {
        $exportId = DB::table('exports')->insertGetId([
            'company_id'  => $this->companyId,
            'user_id'     => $this->userId,
            'module'      => 'personel',
            'parameters'  => json_encode($this->filters),
            'status'      => 'processing',
            'started_at'  => now(),
            'created_at'  => now(),
            'updated_at'  => now(),
        ]);

        try {
            $query = DB::table('personels')
                ->join('departments', 'personels.department_id', '=', 'departments.id', 'left')
                ->join('positions', 'personels.position_id', '=', 'positions.id', 'left')
                ->where('personels.company_id', $this->companyId)
                ->whereNull('personels.deleted_at')
                ->select([
                    'personels.id',
                    'personels.first_name',
                    'personels.last_name',
                    'personels.email',
                    'personels.phone',
                    'personels.hire_date',
                    'personels.status',
                    'departments.name as department',
                    'positions.title as position',
                ]);

            if (!empty($this->filters['department_id'])) {
                $query->where('personels.department_id', $this->filters['department_id']);
            }

            $rows = $query->get();

            // CSV oluştur (SpreadsheetWriter kullanılabilir — VARSAYIM: CSV export)
            $csvContent = "ID,Ad,Soyad,E-posta,Telefon,İşe Giriş,Durum,Departman,Pozisyon\n";
            foreach ($rows as $row) {
                $csvContent .= implode(',', [
                    $row->id,
                    $row->first_name,
                    $row->last_name,
                    $row->email ?? '',
                    $row->phone ?? '',
                    $row->hire_date ?? '',
                    $row->status,
                    $row->department ?? '',
                    $row->position ?? '',
                ]) . "\n";
            }

            $path = "exports/personel_{$this->companyId}_" . now()->format('YmdHis') . '.csv';
            Storage::put($path, $csvContent);

            DB::table('exports')->where('id', $exportId)->update([
                'status'      => 'completed',
                'file_path'   => $path,
                'finished_at' => now(),
                'rows_count'  => $rows->count(),
                'updated_at'  => now(),
            ]);

            // Kullanıcıya bildirim gönder
            // Notification::send(User::find($this->userId), new ExportReadyNotification($path));

        } catch (\Throwable $e) {
            DB::table('exports')->where('id', $exportId)->update([
                'status'        => 'failed',
                'error_message' => $e->getMessage(),
                'finished_at'   => now(),
                'updated_at'    => now(),
            ]);
            throw $e;
        }
    }
}
