<?php
// Generated by Cursor prompt — module: Izin — date: 2026-03-15

namespace App\Jobs;

use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Facades\DB;

class RecalculateLeaveBalancesJob implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    public int $tries = 3;
    public int $timeout = 600;

    public function __construct(
        public readonly ?int $companyId = null,
        public readonly int  $year = 0
    ) {}

    public function handle(): void
    {
        $year = $this->year ?: now()->year;

        $query = DB::table('personels')
            ->where('is_active', true)
            ->whereNull('deleted_at');

        if ($this->companyId) {
            $query->where('company_id', $this->companyId);
        }

        $personels = $query->select(['id', 'company_id', 'hire_date'])->get();

        $leaveTypes = DB::table('leave_types')
            ->whereNull('deleted_at')
            ->get()
            ->keyBy('id');

        foreach ($personels as $personel) {
            foreach ($leaveTypes as $leaveType) {
                // Yıllık hak hesaplama (VARSAYIM: sabit gün, gerçek hesaplama iş kuralına göre değişir)
                $entitledDays = $leaveType->max_annual_days ?? 14;

                // Kullanılan günleri topla
                $usedDays = DB::table('leave_requests')
                    ->where('personel_id', $personel->id)
                    ->where('leave_type_id', $leaveType->id)
                    ->where('status', 'approved')
                    ->whereYear('start_date', $year)
                    ->sum('total_days');

                DB::table('leave_balances')->updateOrInsert(
                    ['personel_id' => $personel->id, 'leave_type_id' => $leaveType->id, 'year' => $year],
                    [
                        'entitled_days'  => $entitledDays,
                        'used_days'      => $usedDays,
                        'remaining_days' => max(0, $entitledDays - $usedDays),
                        'updated_at'     => now(),
                        'created_at'     => now(),
                    ]
                );
            }
        }
    }
}
