<?php
// Generated by Cursor prompt — module: Envanter (AssetAssignment) — date: 2026-03-15

namespace App\Modules\Envanter\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class AssetAssignment extends Model
{
    protected $table = 'asset_assignments';

    protected $fillable = [
        'asset_id', 'personel_id', 'assigned_at', 'returned_at',
        'condition', 'notes', 'assigned_by',
    ];

    protected $casts = [
        'assigned_at' => 'datetime',
        'returned_at' => 'datetime',
    ];

    public function asset(): BelongsTo
    {
        return $this->belongsTo(Asset::class);
    }

    public function personel(): BelongsTo
    {
        return $this->belongsTo(\App\Modules\Personel\Models\Personel::class);
    }

    public function assignedBy(): BelongsTo
    {
        return $this->belongsTo(\App\Models\User::class, 'assigned_by');
    }

    /** Aktif zimmet mi? (iade edilmemiş) */
    public function isActive(): bool
    {
        return $this->returned_at === null;
    }

    /** Zimmet süresi (gün) */
    public function getDaysAssignedAttribute(): int
    {
        $end = $this->returned_at ?? now();
        return (int) $this->assigned_at->diffInDays($end);
    }

    public function scopeActive($query)
    {
        return $query->whereNull('returned_at');
    }

    public function scopeForPersonel($query, int $personelId)
    {
        return $query->where('personel_id', $personelId);
    }
}
